/*
 * OpenMPTL - C++ Microprocessor Template Library
 *
 * This program is a derivative representation of a CMSIS System View
 * Description (SVD) file, and is subject to the corresponding license
 * (see "License.txt" in the parent directory).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

////////////////////////////////////////////////////////////////////////
//
//  Import from CMSIS-SVD: "Spansion/MB9AF15xM.svd"
//
//  name: MB9AF15xM
//  version: 1.7
//  description: MB9AF15xM
//  --------------------------------------------------------------------
//
//  C++ Header file, containing architecture specific register
//  declarations for use in OpenMPTL. It has been converted directly
//  from a CMSIS-SVD file.
//
//  https://digint.ch/openmptl
//  https://github.com/posborne/cmsis-svd
//

#ifndef ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
#define ARCH_REG_ADDRESS_MAP_HPP_INCLUDED

#warning "using untested register declarations"

#include <register_type.hpp>

namespace mptl {

template<reg_addr_t addr>
struct address_map {
  static constexpr const char * name_str = nullptr;
};

template<> struct address_map< 0x40000004 > { static constexpr const char * name_str = "FLASH_IF::FRWTR"; };
template<> struct address_map< 0x40000008 > { static constexpr const char * name_str = "FLASH_IF::FSTR"; };
template<> struct address_map< 0x40000020 > { static constexpr const char * name_str = "FLASH_IF::FICR"; };
template<> struct address_map< 0x40000024 > { static constexpr const char * name_str = "FLASH_IF::FISR"; };
template<> struct address_map< 0x40000028 > { static constexpr const char * name_str = "FLASH_IF::FICLR"; };
template<> struct address_map< 0x40000100 > { static constexpr const char * name_str = "FLASH_IF::CRTRMM"; };
template<> struct address_map< 0x40010000 > { static constexpr const char * name_str = "CRG::SCM_CTL"; };
template<> struct address_map< 0x40010004 > { static constexpr const char * name_str = "CRG::SCM_STR"; };
template<> struct address_map< 0x40010008 > { static constexpr const char * name_str = "CRG::STB_CTL"; };
template<> struct address_map< 0x4001000c > { static constexpr const char * name_str = "CRG::RST_STR"; };
template<> struct address_map< 0x40010010 > { static constexpr const char * name_str = "CRG::BSC_PSR"; };
template<> struct address_map< 0x40010014 > { static constexpr const char * name_str = "CRG::APBC0_PSR"; };
template<> struct address_map< 0x40010018 > { static constexpr const char * name_str = "CRG::APBC1_PSR"; };
template<> struct address_map< 0x4001001c > { static constexpr const char * name_str = "CRG::APBC2_PSR"; };
template<> struct address_map< 0x40010020 > { static constexpr const char * name_str = "CRG::SWC_PSR"; };
template<> struct address_map< 0x40010028 > { static constexpr const char * name_str = "CRG::TTC_PSR"; };
template<> struct address_map< 0x40010030 > { static constexpr const char * name_str = "CRG::CSW_TMR"; };
template<> struct address_map< 0x40010034 > { static constexpr const char * name_str = "CRG::PSW_TMR"; };
template<> struct address_map< 0x40010038 > { static constexpr const char * name_str = "CRG::PLL_CTL1"; };
template<> struct address_map< 0x4001003c > { static constexpr const char * name_str = "CRG::PLL_CTL2"; };
template<> struct address_map< 0x40010040 > { static constexpr const char * name_str = "CRG::CSV_CTL"; };
template<> struct address_map< 0x40010044 > { static constexpr const char * name_str = "CRG::CSV_STR"; };
template<> struct address_map< 0x40010048 > { static constexpr const char * name_str = "CRG::FCSWH_CTL"; };
template<> struct address_map< 0x4001004c > { static constexpr const char * name_str = "CRG::FCSWL_CTL"; };
template<> struct address_map< 0x40010050 > { static constexpr const char * name_str = "CRG::FCSWD_CTL"; };
template<> struct address_map< 0x40010054 > { static constexpr const char * name_str = "CRG::DBWDT_CTL"; };
template<> struct address_map< 0x40010060 > { static constexpr const char * name_str = "CRG::INT_ENR"; };
template<> struct address_map< 0x40010064 > { static constexpr const char * name_str = "CRG::INT_STR"; };
template<> struct address_map< 0x40010068 > { static constexpr const char * name_str = "CRG::INT_CLR"; };
template<> struct address_map< 0x40011000 > { static constexpr const char * name_str = "HWWDT::WDG_LDR"; };
template<> struct address_map< 0x40011004 > { static constexpr const char * name_str = "HWWDT::WDG_VLR"; };
template<> struct address_map< 0x40011008 > { static constexpr const char * name_str = "HWWDT::WDG_CTL"; };
template<> struct address_map< 0x4001100c > { static constexpr const char * name_str = "HWWDT::WDG_ICL"; };
template<> struct address_map< 0x40011010 > { static constexpr const char * name_str = "HWWDT::WDG_RIS"; };
template<> struct address_map< 0x40011c00 > { static constexpr const char * name_str = "HWWDT::WDG_LCK"; };
template<> struct address_map< 0x40012000 > { static constexpr const char * name_str = "SWWDT::WDOGLOAD"; };
template<> struct address_map< 0x40012004 > { static constexpr const char * name_str = "SWWDT::WDOGVALUE"; };
template<> struct address_map< 0x40012008 > { static constexpr const char * name_str = "SWWDT::WDOGCONTROL"; };
template<> struct address_map< 0x4001200c > { static constexpr const char * name_str = "SWWDT::WDOGINTCLR"; };
template<> struct address_map< 0x40012010 > { static constexpr const char * name_str = "SWWDT::WDOGRIS"; };
template<> struct address_map< 0x40012c00 > { static constexpr const char * name_str = "SWWDT::WDOGLOCK"; };
template<> struct address_map< 0x40015000 > { static constexpr const char * name_str = "DTIM::TIMER1LOAD"; };
template<> struct address_map< 0x40015004 > { static constexpr const char * name_str = "DTIM::TIMER1VALUE"; };
template<> struct address_map< 0x40015008 > { static constexpr const char * name_str = "DTIM::TIMER1CONTROL"; };
template<> struct address_map< 0x4001500c > { static constexpr const char * name_str = "DTIM::TIMER1INTCLR"; };
template<> struct address_map< 0x40015010 > { static constexpr const char * name_str = "DTIM::TIMER1RIS"; };
template<> struct address_map< 0x40015014 > { static constexpr const char * name_str = "DTIM::TIMER1MIS"; };
template<> struct address_map< 0x40015018 > { static constexpr const char * name_str = "DTIM::TIMER1BGLOAD"; };
template<> struct address_map< 0x40015020 > { static constexpr const char * name_str = "DTIM::TIMER2LOAD"; };
template<> struct address_map< 0x40015024 > { static constexpr const char * name_str = "DTIM::TIMER2VALUE"; };
template<> struct address_map< 0x40015028 > { static constexpr const char * name_str = "DTIM::TIMER2CONTROL"; };
template<> struct address_map< 0x4001502c > { static constexpr const char * name_str = "DTIM::TIMER2INTCLR"; };
template<> struct address_map< 0x40015030 > { static constexpr const char * name_str = "DTIM::TIMER2RIS"; };
template<> struct address_map< 0x40015034 > { static constexpr const char * name_str = "DTIM::TIMER2MIS"; };
template<> struct address_map< 0x40015038 > { static constexpr const char * name_str = "DTIM::TIMER2BGLOAD"; };
template<> struct address_map< 0x40020000 > { static constexpr const char * name_str = "MFT0::OCU_OCCP0"; };
template<> struct address_map< 0x40020004 > { static constexpr const char * name_str = "MFT0::OCU_OCCP1"; };
template<> struct address_map< 0x40020008 > { static constexpr const char * name_str = "MFT0::OCU_OCCP2"; };
template<> struct address_map< 0x4002000c > { static constexpr const char * name_str = "MFT0::OCU_OCCP3"; };
template<> struct address_map< 0x40020010 > { static constexpr const char * name_str = "MFT0::OCU_OCCP4"; };
template<> struct address_map< 0x40020014 > { static constexpr const char * name_str = "MFT0::OCU_OCCP5"; };
template<> struct address_map< 0x40020018 > { static constexpr const char * name_str = "MFT0::OCU_OCSA10"; };
template<> struct address_map< 0x40020019 > { static constexpr const char * name_str = "MFT0::OCU_OCSB10"; };
template<> struct address_map< 0x4002001c > { static constexpr const char * name_str = "MFT0::OCU_OCSA32"; };
template<> struct address_map< 0x4002001d > { static constexpr const char * name_str = "MFT0::OCU_OCSB32"; };
template<> struct address_map< 0x40020020 > { static constexpr const char * name_str = "MFT0::OCU_OCSA54"; };
template<> struct address_map< 0x40020021 > { static constexpr const char * name_str = "MFT0::OCU_OCSB54"; };
template<> struct address_map< 0x40020024 > { static constexpr const char * name_str = "MFT0::OCU_OCSC"; };
template<> struct address_map< 0x40020028 > { static constexpr const char * name_str = "MFT0::FRT_TCCP0"; };
template<> struct address_map< 0x4002002c > { static constexpr const char * name_str = "MFT0::FRT_TCDT0"; };
template<> struct address_map< 0x40020030 > { static constexpr const char * name_str = "MFT0::FRT_TCSA0"; };
template<> struct address_map< 0x40020034 > { static constexpr const char * name_str = "MFT0::FRT_TCSB0"; };
template<> struct address_map< 0x40020038 > { static constexpr const char * name_str = "MFT0::FRT_TCCP1"; };
template<> struct address_map< 0x4002003c > { static constexpr const char * name_str = "MFT0::FRT_TCDT1"; };
template<> struct address_map< 0x40020040 > { static constexpr const char * name_str = "MFT0::FRT_TCSA1"; };
template<> struct address_map< 0x40020044 > { static constexpr const char * name_str = "MFT0::FRT_TCSB1"; };
template<> struct address_map< 0x40020048 > { static constexpr const char * name_str = "MFT0::FRT_TCCP2"; };
template<> struct address_map< 0x4002004c > { static constexpr const char * name_str = "MFT0::FRT_TCDT2"; };
template<> struct address_map< 0x40020050 > { static constexpr const char * name_str = "MFT0::FRT_TCSA2"; };
template<> struct address_map< 0x40020054 > { static constexpr const char * name_str = "MFT0::FRT_TCSB2"; };
template<> struct address_map< 0x40020058 > { static constexpr const char * name_str = "MFT0::OCU_OCFS10"; };
template<> struct address_map< 0x40020059 > { static constexpr const char * name_str = "MFT0::OCU_OCFS32"; };
template<> struct address_map< 0x4002005c > { static constexpr const char * name_str = "MFT0::OCU_OCFS54"; };
template<> struct address_map< 0x40020060 > { static constexpr const char * name_str = "MFT0::ICU_ICFS10"; };
template<> struct address_map< 0x40020061 > { static constexpr const char * name_str = "MFT0::ICU_ICFS32"; };
template<> struct address_map< 0x40020068 > { static constexpr const char * name_str = "MFT0::ICU_ICCP0"; };
template<> struct address_map< 0x4002006c > { static constexpr const char * name_str = "MFT0::ICU_ICCP1"; };
template<> struct address_map< 0x40020070 > { static constexpr const char * name_str = "MFT0::ICU_ICCP2"; };
template<> struct address_map< 0x40020074 > { static constexpr const char * name_str = "MFT0::ICU_ICCP3"; };
template<> struct address_map< 0x40020078 > { static constexpr const char * name_str = "MFT0::ICU_ICSA10"; };
template<> struct address_map< 0x40020079 > { static constexpr const char * name_str = "MFT0::ICU_ICSB10"; };
template<> struct address_map< 0x4002007c > { static constexpr const char * name_str = "MFT0::ICU_ICSA32"; };
template<> struct address_map< 0x4002007d > { static constexpr const char * name_str = "MFT0::ICU_ICSB32"; };
template<> struct address_map< 0x40020080 > { static constexpr const char * name_str = "MFT0::WFG_WFTM10"; };
template<> struct address_map< 0x40020084 > { static constexpr const char * name_str = "MFT0::WFG_WFTM32"; };
template<> struct address_map< 0x40020088 > { static constexpr const char * name_str = "MFT0::WFG_WFTM54"; };
template<> struct address_map< 0x4002008c > { static constexpr const char * name_str = "MFT0::WFG_WFSA10"; };
template<> struct address_map< 0x40020090 > { static constexpr const char * name_str = "MFT0::WFG_WFSA32"; };
template<> struct address_map< 0x40020094 > { static constexpr const char * name_str = "MFT0::WFG_WFSA54"; };
template<> struct address_map< 0x40020098 > { static constexpr const char * name_str = "MFT0::WFG_WFIR"; };
template<> struct address_map< 0x4002009c > { static constexpr const char * name_str = "MFT0::WFG_NZCL"; };
template<> struct address_map< 0x400200a0 > { static constexpr const char * name_str = "MFT0::ADCMP_ACCP0"; };
template<> struct address_map< 0x400200a4 > { static constexpr const char * name_str = "MFT0::ADCMP_ACCPDN0"; };
template<> struct address_map< 0x400200a8 > { static constexpr const char * name_str = "MFT0::ADCMP_ACCP1"; };
template<> struct address_map< 0x400200ac > { static constexpr const char * name_str = "MFT0::ADCMP_ACCPDN1"; };
template<> struct address_map< 0x400200b0 > { static constexpr const char * name_str = "MFT0::ADCMP_ACCP2"; };
template<> struct address_map< 0x400200b4 > { static constexpr const char * name_str = "MFT0::ADCMP_ACCPDN2"; };
template<> struct address_map< 0x400200b8 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSB"; };
template<> struct address_map< 0x400200bc > { static constexpr const char * name_str = "MFT0::ADCMP_ACSA"; };
template<> struct address_map< 0x400200c0 > { static constexpr const char * name_str = "MFT0::ADCMP_ATSA"; };
template<> struct address_map< 0x40024000 > { static constexpr const char * name_str = "MFT_PPG::TTCR0"; };
template<> struct address_map< 0x40024008 > { static constexpr const char * name_str = "MFT_PPG::COMP0"; };
template<> struct address_map< 0x4002400c > { static constexpr const char * name_str = "MFT_PPG::COMP2"; };
template<> struct address_map< 0x40024010 > { static constexpr const char * name_str = "MFT_PPG::COMP4"; };
template<> struct address_map< 0x40024014 > { static constexpr const char * name_str = "MFT_PPG::COMP6"; };
template<> struct address_map< 0x40024100 > { static constexpr const char * name_str = "MFT_PPG::TRG"; };
template<> struct address_map< 0x40024104 > { static constexpr const char * name_str = "MFT_PPG::REVC"; };
template<> struct address_map< 0x40024200 > { static constexpr const char * name_str = "MFT_PPG::PPGC1"; };
template<> struct address_map< 0x40024201 > { static constexpr const char * name_str = "MFT_PPG::PPGC0"; };
template<> struct address_map< 0x40024204 > { static constexpr const char * name_str = "MFT_PPG::PPGC3"; };
template<> struct address_map< 0x40024205 > { static constexpr const char * name_str = "MFT_PPG::PPGC2"; };
template<> struct address_map< 0x40024208 > { static constexpr const char * name_str = "MFT_PPG::PRLL0"; };
template<> struct address_map< 0x40024209 > { static constexpr const char * name_str = "MFT_PPG::PRLH0"; };
template<> struct address_map< 0x4002420c > { static constexpr const char * name_str = "MFT_PPG::PRLL1"; };
template<> struct address_map< 0x4002420d > { static constexpr const char * name_str = "MFT_PPG::PRLH1"; };
template<> struct address_map< 0x40024210 > { static constexpr const char * name_str = "MFT_PPG::PRLL2"; };
template<> struct address_map< 0x40024211 > { static constexpr const char * name_str = "MFT_PPG::PRLH2"; };
template<> struct address_map< 0x40024214 > { static constexpr const char * name_str = "MFT_PPG::PRLL3"; };
template<> struct address_map< 0x40024215 > { static constexpr const char * name_str = "MFT_PPG::PRLH3"; };
template<> struct address_map< 0x40024218 > { static constexpr const char * name_str = "MFT_PPG::GATEC0"; };
template<> struct address_map< 0x40024240 > { static constexpr const char * name_str = "MFT_PPG::PPGC5"; };
template<> struct address_map< 0x40024241 > { static constexpr const char * name_str = "MFT_PPG::PPGC4"; };
template<> struct address_map< 0x40024244 > { static constexpr const char * name_str = "MFT_PPG::PPGC7"; };
template<> struct address_map< 0x40024245 > { static constexpr const char * name_str = "MFT_PPG::PPGC6"; };
template<> struct address_map< 0x40024248 > { static constexpr const char * name_str = "MFT_PPG::PRLL4"; };
template<> struct address_map< 0x40024249 > { static constexpr const char * name_str = "MFT_PPG::PRLH4"; };
template<> struct address_map< 0x4002424c > { static constexpr const char * name_str = "MFT_PPG::PRLL5"; };
template<> struct address_map< 0x4002424d > { static constexpr const char * name_str = "MFT_PPG::PRLH5"; };
template<> struct address_map< 0x40024250 > { static constexpr const char * name_str = "MFT_PPG::PRLL6"; };
template<> struct address_map< 0x40024251 > { static constexpr const char * name_str = "MFT_PPG::PRLH6"; };
template<> struct address_map< 0x40024254 > { static constexpr const char * name_str = "MFT_PPG::PRLL7"; };
template<> struct address_map< 0x40024255 > { static constexpr const char * name_str = "MFT_PPG::PRLH7"; };
template<> struct address_map< 0x40024258 > { static constexpr const char * name_str = "MFT_PPG::GATEC4"; };
template<> struct address_map< 0x40024380 > { static constexpr const char * name_str = "MFT_PPG::IGBTC"; };
template<> struct address_map< 0x40025000 > { static constexpr const char * name_str = "BT0::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLL, BT0::PWM_PCSR, BT0::RT_PCSR */
template<> struct address_map< 0x40025004 > { static constexpr const char * name_str = "BT0::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLH, BT0::PWC_DTBF, BT0::PWM_PDUT */
template<> struct address_map< 0x40025008 > { static constexpr const char * name_str = "BT0::RT_TMR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMR, BT0::PWM_TMR, BT0::RT_TMR */
template<> struct address_map< 0x4002500c > { static constexpr const char * name_str = "BT0::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR, BT0::PWC_TMCR, BT0::PWM_TMCR, BT0::RT_TMCR */
template<> struct address_map< 0x40025010 > { static constexpr const char * name_str = "BT0::RT_STC"; };  /* svd2hpp: duplicate address for: BT0::PPG_STC, BT0::PWC_STC, BT0::PWM_STC, BT0::RT_STC */
template<> struct address_map< 0x40025011 > { static constexpr const char * name_str = "BT0::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR2, BT0::PWC_TMCR2, BT0::PWM_TMCR2, BT0::RT_TMCR2 */
template<> struct address_map< 0x40025040 > { static constexpr const char * name_str = "BT1::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLL, BT1::PWM_PCSR, BT1::RT_PCSR */
template<> struct address_map< 0x40025044 > { static constexpr const char * name_str = "BT1::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLH, BT1::PWC_DTBF, BT1::PWM_PDUT */
template<> struct address_map< 0x40025048 > { static constexpr const char * name_str = "BT1::RT_TMR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMR, BT1::PWM_TMR, BT1::RT_TMR */
template<> struct address_map< 0x4002504c > { static constexpr const char * name_str = "BT1::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR, BT1::PWC_TMCR, BT1::PWM_TMCR, BT1::RT_TMCR */
template<> struct address_map< 0x40025050 > { static constexpr const char * name_str = "BT1::RT_STC"; };  /* svd2hpp: duplicate address for: BT1::PPG_STC, BT1::PWC_STC, BT1::PWM_STC, BT1::RT_STC */
template<> struct address_map< 0x40025051 > { static constexpr const char * name_str = "BT1::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR2, BT1::PWC_TMCR2, BT1::PWM_TMCR2, BT1::RT_TMCR2 */
template<> struct address_map< 0x40025080 > { static constexpr const char * name_str = "BT2::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLL, BT2::PWM_PCSR, BT2::RT_PCSR */
template<> struct address_map< 0x40025084 > { static constexpr const char * name_str = "BT2::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLH, BT2::PWC_DTBF, BT2::PWM_PDUT */
template<> struct address_map< 0x40025088 > { static constexpr const char * name_str = "BT2::RT_TMR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMR, BT2::PWM_TMR, BT2::RT_TMR */
template<> struct address_map< 0x4002508c > { static constexpr const char * name_str = "BT2::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR, BT2::PWC_TMCR, BT2::PWM_TMCR, BT2::RT_TMCR */
template<> struct address_map< 0x40025090 > { static constexpr const char * name_str = "BT2::RT_STC"; };  /* svd2hpp: duplicate address for: BT2::PPG_STC, BT2::PWC_STC, BT2::PWM_STC, BT2::RT_STC */
template<> struct address_map< 0x40025091 > { static constexpr const char * name_str = "BT2::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR2, BT2::PWC_TMCR2, BT2::PWM_TMCR2, BT2::RT_TMCR2 */
template<> struct address_map< 0x400250c0 > { static constexpr const char * name_str = "BT3::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLL, BT3::PWM_PCSR, BT3::RT_PCSR */
template<> struct address_map< 0x400250c4 > { static constexpr const char * name_str = "BT3::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLH, BT3::PWC_DTBF, BT3::PWM_PDUT */
template<> struct address_map< 0x400250c8 > { static constexpr const char * name_str = "BT3::RT_TMR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMR, BT3::PWM_TMR, BT3::RT_TMR */
template<> struct address_map< 0x400250cc > { static constexpr const char * name_str = "BT3::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR, BT3::PWC_TMCR, BT3::PWM_TMCR, BT3::RT_TMCR */
template<> struct address_map< 0x400250d0 > { static constexpr const char * name_str = "BT3::RT_STC"; };  /* svd2hpp: duplicate address for: BT3::PPG_STC, BT3::PWC_STC, BT3::PWM_STC, BT3::RT_STC */
template<> struct address_map< 0x400250d1 > { static constexpr const char * name_str = "BT3::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR2, BT3::PWC_TMCR2, BT3::PWM_TMCR2, BT3::RT_TMCR2 */
template<> struct address_map< 0x40025100 > { static constexpr const char * name_str = "BTIOSEL03::BTSEL0123"; };
template<> struct address_map< 0x40025200 > { static constexpr const char * name_str = "BT4::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT4::PPG_PRLL, BT4::PWM_PCSR, BT4::RT_PCSR */
template<> struct address_map< 0x40025204 > { static constexpr const char * name_str = "BT4::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT4::PPG_PRLH, BT4::PWC_DTBF, BT4::PWM_PDUT */
template<> struct address_map< 0x40025208 > { static constexpr const char * name_str = "BT4::RT_TMR"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMR, BT4::PWM_TMR, BT4::RT_TMR */
template<> struct address_map< 0x4002520c > { static constexpr const char * name_str = "BT4::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMCR, BT4::PWC_TMCR, BT4::PWM_TMCR, BT4::RT_TMCR */
template<> struct address_map< 0x40025210 > { static constexpr const char * name_str = "BT4::RT_STC"; };  /* svd2hpp: duplicate address for: BT4::PPG_STC, BT4::PWC_STC, BT4::PWM_STC, BT4::RT_STC */
template<> struct address_map< 0x40025211 > { static constexpr const char * name_str = "BT4::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMCR2, BT4::PWC_TMCR2, BT4::PWM_TMCR2, BT4::RT_TMCR2 */
template<> struct address_map< 0x40025240 > { static constexpr const char * name_str = "BT5::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT5::PPG_PRLL, BT5::PWM_PCSR, BT5::RT_PCSR */
template<> struct address_map< 0x40025244 > { static constexpr const char * name_str = "BT5::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT5::PPG_PRLH, BT5::PWC_DTBF, BT5::PWM_PDUT */
template<> struct address_map< 0x40025248 > { static constexpr const char * name_str = "BT5::RT_TMR"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMR, BT5::PWM_TMR, BT5::RT_TMR */
template<> struct address_map< 0x4002524c > { static constexpr const char * name_str = "BT5::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMCR, BT5::PWC_TMCR, BT5::PWM_TMCR, BT5::RT_TMCR */
template<> struct address_map< 0x40025250 > { static constexpr const char * name_str = "BT5::RT_STC"; };  /* svd2hpp: duplicate address for: BT5::PPG_STC, BT5::PWC_STC, BT5::PWM_STC, BT5::RT_STC */
template<> struct address_map< 0x40025251 > { static constexpr const char * name_str = "BT5::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMCR2, BT5::PWC_TMCR2, BT5::PWM_TMCR2, BT5::RT_TMCR2 */
template<> struct address_map< 0x40025280 > { static constexpr const char * name_str = "BT6::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT6::PPG_PRLL, BT6::PWM_PCSR, BT6::RT_PCSR */
template<> struct address_map< 0x40025284 > { static constexpr const char * name_str = "BT6::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT6::PPG_PRLH, BT6::PWC_DTBF, BT6::PWM_PDUT */
template<> struct address_map< 0x40025288 > { static constexpr const char * name_str = "BT6::RT_TMR"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMR, BT6::PWM_TMR, BT6::RT_TMR */
template<> struct address_map< 0x4002528c > { static constexpr const char * name_str = "BT6::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMCR, BT6::PWC_TMCR, BT6::PWM_TMCR, BT6::RT_TMCR */
template<> struct address_map< 0x40025290 > { static constexpr const char * name_str = "BT6::RT_STC"; };  /* svd2hpp: duplicate address for: BT6::PPG_STC, BT6::PWC_STC, BT6::PWM_STC, BT6::RT_STC */
template<> struct address_map< 0x40025291 > { static constexpr const char * name_str = "BT6::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMCR2, BT6::PWC_TMCR2, BT6::PWM_TMCR2, BT6::RT_TMCR2 */
template<> struct address_map< 0x400252c0 > { static constexpr const char * name_str = "BT7::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT7::PPG_PRLL, BT7::PWM_PCSR, BT7::RT_PCSR */
template<> struct address_map< 0x400252c4 > { static constexpr const char * name_str = "BT7::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT7::PPG_PRLH, BT7::PWC_DTBF, BT7::PWM_PDUT */
template<> struct address_map< 0x400252c8 > { static constexpr const char * name_str = "BT7::RT_TMR"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMR, BT7::PWM_TMR, BT7::RT_TMR */
template<> struct address_map< 0x400252cc > { static constexpr const char * name_str = "BT7::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMCR, BT7::PWC_TMCR, BT7::PWM_TMCR, BT7::RT_TMCR */
template<> struct address_map< 0x400252d0 > { static constexpr const char * name_str = "BT7::RT_STC"; };  /* svd2hpp: duplicate address for: BT7::PPG_STC, BT7::PWC_STC, BT7::PWM_STC, BT7::RT_STC */
template<> struct address_map< 0x400252d1 > { static constexpr const char * name_str = "BT7::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMCR2, BT7::PWC_TMCR2, BT7::PWM_TMCR2, BT7::RT_TMCR2 */
template<> struct address_map< 0x40025300 > { static constexpr const char * name_str = "BTIOSEL47::BTSEL4567"; };
template<> struct address_map< 0x40025400 > { static constexpr const char * name_str = "BT8::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT8::PPG_PRLL, BT8::PWM_PCSR, BT8::RT_PCSR */
template<> struct address_map< 0x40025404 > { static constexpr const char * name_str = "BT8::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT8::PPG_PRLH, BT8::PWC_DTBF, BT8::PWM_PDUT */
template<> struct address_map< 0x40025408 > { static constexpr const char * name_str = "BT8::RT_TMR"; };  /* svd2hpp: duplicate address for: BT8::PPG_TMR, BT8::PWM_TMR, BT8::RT_TMR */
template<> struct address_map< 0x4002540c > { static constexpr const char * name_str = "BT8::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT8::PPG_TMCR, BT8::PWC_TMCR, BT8::PWM_TMCR, BT8::RT_TMCR */
template<> struct address_map< 0x40025410 > { static constexpr const char * name_str = "BT8::RT_STC"; };  /* svd2hpp: duplicate address for: BT8::PPG_STC, BT8::PWC_STC, BT8::PWM_STC, BT8::RT_STC */
template<> struct address_map< 0x40025411 > { static constexpr const char * name_str = "BT8::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT8::PPG_TMCR2, BT8::PWC_TMCR2, BT8::PWM_TMCR2, BT8::RT_TMCR2 */
template<> struct address_map< 0x40025440 > { static constexpr const char * name_str = "BT9::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT9::PPG_PRLL, BT9::PWM_PCSR, BT9::RT_PCSR */
template<> struct address_map< 0x40025444 > { static constexpr const char * name_str = "BT9::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT9::PPG_PRLH, BT9::PWC_DTBF, BT9::PWM_PDUT */
template<> struct address_map< 0x40025448 > { static constexpr const char * name_str = "BT9::RT_TMR"; };  /* svd2hpp: duplicate address for: BT9::PPG_TMR, BT9::PWM_TMR, BT9::RT_TMR */
template<> struct address_map< 0x4002544c > { static constexpr const char * name_str = "BT9::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT9::PPG_TMCR, BT9::PWC_TMCR, BT9::PWM_TMCR, BT9::RT_TMCR */
template<> struct address_map< 0x40025450 > { static constexpr const char * name_str = "BT9::RT_STC"; };  /* svd2hpp: duplicate address for: BT9::PPG_STC, BT9::PWC_STC, BT9::PWM_STC, BT9::RT_STC */
template<> struct address_map< 0x40025451 > { static constexpr const char * name_str = "BT9::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT9::PPG_TMCR2, BT9::PWC_TMCR2, BT9::PWM_TMCR2, BT9::RT_TMCR2 */
template<> struct address_map< 0x40025480 > { static constexpr const char * name_str = "BT10::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT10::PPG_PRLL, BT10::PWM_PCSR, BT10::RT_PCSR */
template<> struct address_map< 0x40025484 > { static constexpr const char * name_str = "BT10::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT10::PPG_PRLH, BT10::PWC_DTBF, BT10::PWM_PDUT */
template<> struct address_map< 0x40025488 > { static constexpr const char * name_str = "BT10::RT_TMR"; };  /* svd2hpp: duplicate address for: BT10::PPG_TMR, BT10::PWM_TMR, BT10::RT_TMR */
template<> struct address_map< 0x4002548c > { static constexpr const char * name_str = "BT10::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT10::PPG_TMCR, BT10::PWC_TMCR, BT10::PWM_TMCR, BT10::RT_TMCR */
template<> struct address_map< 0x40025490 > { static constexpr const char * name_str = "BT10::RT_STC"; };  /* svd2hpp: duplicate address for: BT10::PPG_STC, BT10::PWC_STC, BT10::PWM_STC, BT10::RT_STC */
template<> struct address_map< 0x40025491 > { static constexpr const char * name_str = "BT10::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT10::PPG_TMCR2, BT10::PWC_TMCR2, BT10::PWM_TMCR2, BT10::RT_TMCR2 */
template<> struct address_map< 0x400254c0 > { static constexpr const char * name_str = "BT11::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT11::PPG_PRLL, BT11::PWM_PCSR, BT11::RT_PCSR */
template<> struct address_map< 0x400254c4 > { static constexpr const char * name_str = "BT11::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT11::PPG_PRLH, BT11::PWC_DTBF, BT11::PWM_PDUT */
template<> struct address_map< 0x400254c8 > { static constexpr const char * name_str = "BT11::RT_TMR"; };  /* svd2hpp: duplicate address for: BT11::PPG_TMR, BT11::PWM_TMR, BT11::RT_TMR */
template<> struct address_map< 0x400254cc > { static constexpr const char * name_str = "BT11::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT11::PPG_TMCR, BT11::PWC_TMCR, BT11::PWM_TMCR, BT11::RT_TMCR */
template<> struct address_map< 0x400254d0 > { static constexpr const char * name_str = "BT11::RT_STC"; };  /* svd2hpp: duplicate address for: BT11::PPG_STC, BT11::PWC_STC, BT11::PWM_STC, BT11::RT_STC */
template<> struct address_map< 0x400254d1 > { static constexpr const char * name_str = "BT11::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT11::PPG_TMCR2, BT11::PWC_TMCR2, BT11::PWM_TMCR2, BT11::RT_TMCR2 */
template<> struct address_map< 0x40025500 > { static constexpr const char * name_str = "BTIOSEL8B::BTSEL89AB"; };
template<> struct address_map< 0x40025600 > { static constexpr const char * name_str = "BT12::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT12::PPG_PRLL, BT12::PWM_PCSR, BT12::RT_PCSR */
template<> struct address_map< 0x40025604 > { static constexpr const char * name_str = "BT12::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT12::PPG_PRLH, BT12::PWC_DTBF, BT12::PWM_PDUT */
template<> struct address_map< 0x40025608 > { static constexpr const char * name_str = "BT12::RT_TMR"; };  /* svd2hpp: duplicate address for: BT12::PPG_TMR, BT12::PWM_TMR, BT12::RT_TMR */
template<> struct address_map< 0x4002560c > { static constexpr const char * name_str = "BT12::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT12::PPG_TMCR, BT12::PWC_TMCR, BT12::PWM_TMCR, BT12::RT_TMCR */
template<> struct address_map< 0x40025610 > { static constexpr const char * name_str = "BT12::RT_STC"; };  /* svd2hpp: duplicate address for: BT12::PPG_STC, BT12::PWC_STC, BT12::PWM_STC, BT12::RT_STC */
template<> struct address_map< 0x40025611 > { static constexpr const char * name_str = "BT12::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT12::PPG_TMCR2, BT12::PWC_TMCR2, BT12::PWM_TMCR2, BT12::RT_TMCR2 */
template<> struct address_map< 0x40025640 > { static constexpr const char * name_str = "BT13::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT13::PPG_PRLL, BT13::PWM_PCSR, BT13::RT_PCSR */
template<> struct address_map< 0x40025644 > { static constexpr const char * name_str = "BT13::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT13::PPG_PRLH, BT13::PWC_DTBF, BT13::PWM_PDUT */
template<> struct address_map< 0x40025648 > { static constexpr const char * name_str = "BT13::RT_TMR"; };  /* svd2hpp: duplicate address for: BT13::PPG_TMR, BT13::PWM_TMR, BT13::RT_TMR */
template<> struct address_map< 0x4002564c > { static constexpr const char * name_str = "BT13::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT13::PPG_TMCR, BT13::PWC_TMCR, BT13::PWM_TMCR, BT13::RT_TMCR */
template<> struct address_map< 0x40025650 > { static constexpr const char * name_str = "BT13::RT_STC"; };  /* svd2hpp: duplicate address for: BT13::PPG_STC, BT13::PWC_STC, BT13::PWM_STC, BT13::RT_STC */
template<> struct address_map< 0x40025651 > { static constexpr const char * name_str = "BT13::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT13::PPG_TMCR2, BT13::PWC_TMCR2, BT13::PWM_TMCR2, BT13::RT_TMCR2 */
template<> struct address_map< 0x40025680 > { static constexpr const char * name_str = "BT14::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT14::PPG_PRLL, BT14::PWM_PCSR, BT14::RT_PCSR */
template<> struct address_map< 0x40025684 > { static constexpr const char * name_str = "BT14::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT14::PPG_PRLH, BT14::PWC_DTBF, BT14::PWM_PDUT */
template<> struct address_map< 0x40025688 > { static constexpr const char * name_str = "BT14::RT_TMR"; };  /* svd2hpp: duplicate address for: BT14::PPG_TMR, BT14::PWM_TMR, BT14::RT_TMR */
template<> struct address_map< 0x4002568c > { static constexpr const char * name_str = "BT14::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT14::PPG_TMCR, BT14::PWC_TMCR, BT14::PWM_TMCR, BT14::RT_TMCR */
template<> struct address_map< 0x40025690 > { static constexpr const char * name_str = "BT14::RT_STC"; };  /* svd2hpp: duplicate address for: BT14::PPG_STC, BT14::PWC_STC, BT14::PWM_STC, BT14::RT_STC */
template<> struct address_map< 0x40025691 > { static constexpr const char * name_str = "BT14::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT14::PPG_TMCR2, BT14::PWC_TMCR2, BT14::PWM_TMCR2, BT14::RT_TMCR2 */
template<> struct address_map< 0x400256c0 > { static constexpr const char * name_str = "BT15::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT15::PPG_PRLL, BT15::PWM_PCSR, BT15::RT_PCSR */
template<> struct address_map< 0x400256c4 > { static constexpr const char * name_str = "BT15::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT15::PPG_PRLH, BT15::PWC_DTBF, BT15::PWM_PDUT */
template<> struct address_map< 0x400256c8 > { static constexpr const char * name_str = "BT15::RT_TMR"; };  /* svd2hpp: duplicate address for: BT15::PPG_TMR, BT15::PWM_TMR, BT15::RT_TMR */
template<> struct address_map< 0x400256cc > { static constexpr const char * name_str = "BT15::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT15::PPG_TMCR, BT15::PWC_TMCR, BT15::PWM_TMCR, BT15::RT_TMCR */
template<> struct address_map< 0x400256d0 > { static constexpr const char * name_str = "BT15::RT_STC"; };  /* svd2hpp: duplicate address for: BT15::PPG_STC, BT15::PWC_STC, BT15::PWM_STC, BT15::RT_STC */
template<> struct address_map< 0x400256d1 > { static constexpr const char * name_str = "BT15::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT15::PPG_TMCR2, BT15::PWC_TMCR2, BT15::PWM_TMCR2, BT15::RT_TMCR2 */
template<> struct address_map< 0x40025700 > { static constexpr const char * name_str = "BTIOSELCF::BTSELCDEF"; };
template<> struct address_map< 0x40025ffc > { static constexpr const char * name_str = "SBSSR::BTSSSR"; };
template<> struct address_map< 0x40026000 > { static constexpr const char * name_str = "QPRC0::QPCR"; };
template<> struct address_map< 0x40026004 > { static constexpr const char * name_str = "QPRC0::QRCR"; };
template<> struct address_map< 0x40026008 > { static constexpr const char * name_str = "QPRC0::QPCCR"; };
template<> struct address_map< 0x4002600c > { static constexpr const char * name_str = "QPRC0::QPRCR"; };
template<> struct address_map< 0x40026010 > { static constexpr const char * name_str = "QPRC0::QMPR"; };
template<> struct address_map< 0x40026014 > { static constexpr const char * name_str = "QPRC0::QICRL"; };
template<> struct address_map< 0x40026015 > { static constexpr const char * name_str = "QPRC0::QICRH"; };
template<> struct address_map< 0x40026018 > { static constexpr const char * name_str = "QPRC0::QCR"; };
template<> struct address_map< 0x4002601c > { static constexpr const char * name_str = "QPRC0::QECR"; };
template<> struct address_map< 0x4002603c > { static constexpr const char * name_str = "QPRC0::QRCRR"; };
template<> struct address_map< 0x4002603e > { static constexpr const char * name_str = "QPRC0::QPCRR"; };
template<> struct address_map< 0x40026040 > { static constexpr const char * name_str = "QPRC1::QPCR"; };
template<> struct address_map< 0x40026044 > { static constexpr const char * name_str = "QPRC1::QRCR"; };
template<> struct address_map< 0x40026048 > { static constexpr const char * name_str = "QPRC1::QPCCR"; };
template<> struct address_map< 0x4002604c > { static constexpr const char * name_str = "QPRC1::QPRCR"; };
template<> struct address_map< 0x40026050 > { static constexpr const char * name_str = "QPRC1::QMPR"; };
template<> struct address_map< 0x40026054 > { static constexpr const char * name_str = "QPRC1::QICRL"; };
template<> struct address_map< 0x40026055 > { static constexpr const char * name_str = "QPRC1::QICRH"; };
template<> struct address_map< 0x40026058 > { static constexpr const char * name_str = "QPRC1::QCR"; };
template<> struct address_map< 0x4002605c > { static constexpr const char * name_str = "QPRC1::QECR"; };
template<> struct address_map< 0x4002607c > { static constexpr const char * name_str = "QPRC1::QRCRR"; };
template<> struct address_map< 0x4002607e > { static constexpr const char * name_str = "QPRC1::QPCRR"; };
template<> struct address_map< 0x40026080 > { static constexpr const char * name_str = "QPRC2::QPCR"; };
template<> struct address_map< 0x40026084 > { static constexpr const char * name_str = "QPRC2::QRCR"; };
template<> struct address_map< 0x40026088 > { static constexpr const char * name_str = "QPRC2::QPCCR"; };
template<> struct address_map< 0x4002608c > { static constexpr const char * name_str = "QPRC2::QPRCR"; };
template<> struct address_map< 0x40026090 > { static constexpr const char * name_str = "QPRC2::QMPR"; };
template<> struct address_map< 0x40026094 > { static constexpr const char * name_str = "QPRC2::QICRL"; };
template<> struct address_map< 0x40026095 > { static constexpr const char * name_str = "QPRC2::QICRH"; };
template<> struct address_map< 0x40026098 > { static constexpr const char * name_str = "QPRC2::QCR"; };
template<> struct address_map< 0x4002609c > { static constexpr const char * name_str = "QPRC2::QECR"; };
template<> struct address_map< 0x400260bc > { static constexpr const char * name_str = "QPRC2::QRCRR"; };
template<> struct address_map< 0x400260be > { static constexpr const char * name_str = "QPRC2::QPCRR"; };
template<> struct address_map< 0x40027000 > { static constexpr const char * name_str = "ADC0::ADSR"; };
template<> struct address_map< 0x40027001 > { static constexpr const char * name_str = "ADC0::ADCR"; };
template<> struct address_map< 0x40027008 > { static constexpr const char * name_str = "ADC0::SFNS"; };
template<> struct address_map< 0x40027009 > { static constexpr const char * name_str = "ADC0::SCCR"; };
template<> struct address_map< 0x4002700c > { static constexpr const char * name_str = "ADC0::SCFD"; };
template<> struct address_map< 0x40027010 > { static constexpr const char * name_str = "ADC0::SCIS2"; };
template<> struct address_map< 0x40027011 > { static constexpr const char * name_str = "ADC0::SCIS3"; };
template<> struct address_map< 0x40027014 > { static constexpr const char * name_str = "ADC0::SCIS0"; };
template<> struct address_map< 0x40027015 > { static constexpr const char * name_str = "ADC0::SCIS1"; };
template<> struct address_map< 0x40027018 > { static constexpr const char * name_str = "ADC0::PFNS"; };
template<> struct address_map< 0x40027019 > { static constexpr const char * name_str = "ADC0::PCCR"; };
template<> struct address_map< 0x4002701c > { static constexpr const char * name_str = "ADC0::PCFD"; };
template<> struct address_map< 0x40027020 > { static constexpr const char * name_str = "ADC0::PCIS"; };
template<> struct address_map< 0x40027024 > { static constexpr const char * name_str = "ADC0::CMPCR"; };
template<> struct address_map< 0x40027026 > { static constexpr const char * name_str = "ADC0::CMPD"; };
template<> struct address_map< 0x40027028 > { static constexpr const char * name_str = "ADC0::ADSS2"; };
template<> struct address_map< 0x40027029 > { static constexpr const char * name_str = "ADC0::ADSS3"; };
template<> struct address_map< 0x4002702c > { static constexpr const char * name_str = "ADC0::ADSS0"; };
template<> struct address_map< 0x4002702d > { static constexpr const char * name_str = "ADC0::ADSS1"; };
template<> struct address_map< 0x40027030 > { static constexpr const char * name_str = "ADC0::ADST1"; };
template<> struct address_map< 0x40027031 > { static constexpr const char * name_str = "ADC0::ADST0"; };
template<> struct address_map< 0x40027034 > { static constexpr const char * name_str = "ADC0::ADCT"; };
template<> struct address_map< 0x40027038 > { static constexpr const char * name_str = "ADC0::PRTSL"; };
template<> struct address_map< 0x40027039 > { static constexpr const char * name_str = "ADC0::SCTSL"; };
template<> struct address_map< 0x4002703c > { static constexpr const char * name_str = "ADC0::ADCEN"; };
template<> struct address_map< 0x40027100 > { static constexpr const char * name_str = "ADC1::ADSR"; };
template<> struct address_map< 0x40027101 > { static constexpr const char * name_str = "ADC1::ADCR"; };
template<> struct address_map< 0x40027108 > { static constexpr const char * name_str = "ADC1::SFNS"; };
template<> struct address_map< 0x40027109 > { static constexpr const char * name_str = "ADC1::SCCR"; };
template<> struct address_map< 0x4002710c > { static constexpr const char * name_str = "ADC1::SCFD"; };
template<> struct address_map< 0x40027110 > { static constexpr const char * name_str = "ADC1::SCIS2"; };
template<> struct address_map< 0x40027111 > { static constexpr const char * name_str = "ADC1::SCIS3"; };
template<> struct address_map< 0x40027114 > { static constexpr const char * name_str = "ADC1::SCIS0"; };
template<> struct address_map< 0x40027115 > { static constexpr const char * name_str = "ADC1::SCIS1"; };
template<> struct address_map< 0x40027118 > { static constexpr const char * name_str = "ADC1::PFNS"; };
template<> struct address_map< 0x40027119 > { static constexpr const char * name_str = "ADC1::PCCR"; };
template<> struct address_map< 0x4002711c > { static constexpr const char * name_str = "ADC1::PCFD"; };
template<> struct address_map< 0x40027120 > { static constexpr const char * name_str = "ADC1::PCIS"; };
template<> struct address_map< 0x40027124 > { static constexpr const char * name_str = "ADC1::CMPCR"; };
template<> struct address_map< 0x40027126 > { static constexpr const char * name_str = "ADC1::CMPD"; };
template<> struct address_map< 0x40027128 > { static constexpr const char * name_str = "ADC1::ADSS2"; };
template<> struct address_map< 0x40027129 > { static constexpr const char * name_str = "ADC1::ADSS3"; };
template<> struct address_map< 0x4002712c > { static constexpr const char * name_str = "ADC1::ADSS0"; };
template<> struct address_map< 0x4002712d > { static constexpr const char * name_str = "ADC1::ADSS1"; };
template<> struct address_map< 0x40027130 > { static constexpr const char * name_str = "ADC1::ADST1"; };
template<> struct address_map< 0x40027131 > { static constexpr const char * name_str = "ADC1::ADST0"; };
template<> struct address_map< 0x40027134 > { static constexpr const char * name_str = "ADC1::ADCT"; };
template<> struct address_map< 0x40027138 > { static constexpr const char * name_str = "ADC1::PRTSL"; };
template<> struct address_map< 0x40027139 > { static constexpr const char * name_str = "ADC1::SCTSL"; };
template<> struct address_map< 0x4002713c > { static constexpr const char * name_str = "ADC1::ADCEN"; };
template<> struct address_map< 0x4002e000 > { static constexpr const char * name_str = "CRTRIM::MCR_PSR"; };
template<> struct address_map< 0x4002e004 > { static constexpr const char * name_str = "CRTRIM::MCR_FTRM"; };
template<> struct address_map< 0x4002e00c > { static constexpr const char * name_str = "CRTRIM::MCR_RLR"; };
template<> struct address_map< 0x40030000 > { static constexpr const char * name_str = "EXTI::ENIR"; };
template<> struct address_map< 0x40030004 > { static constexpr const char * name_str = "EXTI::EIRR"; };
template<> struct address_map< 0x40030008 > { static constexpr const char * name_str = "EXTI::EICL"; };
template<> struct address_map< 0x4003000c > { static constexpr const char * name_str = "EXTI::ELVR"; };
template<> struct address_map< 0x40030010 > { static constexpr const char * name_str = "EXTI::ELVR1"; };
template<> struct address_map< 0x40030014 > { static constexpr const char * name_str = "EXTI::NMIRR"; };
template<> struct address_map< 0x40030018 > { static constexpr const char * name_str = "EXTI::NMICL"; };
template<> struct address_map< 0x40031000 > { static constexpr const char * name_str = "INTREQ::DRQSEL"; };
template<> struct address_map< 0x4003100c > { static constexpr const char * name_str = "INTREQ::IRQCMODE"; };
template<> struct address_map< 0x40031010 > { static constexpr const char * name_str = "INTREQ::EXC02MON"; };
template<> struct address_map< 0x40031014 > { static constexpr const char * name_str = "INTREQ::IRQ00MON"; };
template<> struct address_map< 0x40031018 > { static constexpr const char * name_str = "INTREQ::IRQ01MON"; };
template<> struct address_map< 0x4003101c > { static constexpr const char * name_str = "INTREQ::IRQ02MON"; };
template<> struct address_map< 0x40031020 > { static constexpr const char * name_str = "INTREQ::IRQ03MON"; };
template<> struct address_map< 0x40031024 > { static constexpr const char * name_str = "INTREQ::IRQ04MON"; };
template<> struct address_map< 0x40031028 > { static constexpr const char * name_str = "INTREQ::IRQ05MON"; };
template<> struct address_map< 0x4003102c > { static constexpr const char * name_str = "INTREQ::IRQ06MON"; };
template<> struct address_map< 0x40031030 > { static constexpr const char * name_str = "INTREQ::IRQ07MON"; };
template<> struct address_map< 0x40031034 > { static constexpr const char * name_str = "INTREQ::IRQ08MON"; };
template<> struct address_map< 0x40031038 > { static constexpr const char * name_str = "INTREQ::IRQ09MON"; };
template<> struct address_map< 0x4003103c > { static constexpr const char * name_str = "INTREQ::IRQ10MON"; };
template<> struct address_map< 0x40031040 > { static constexpr const char * name_str = "INTREQ::IRQ11MON"; };
template<> struct address_map< 0x40031044 > { static constexpr const char * name_str = "INTREQ::IRQ12MON"; };
template<> struct address_map< 0x40031048 > { static constexpr const char * name_str = "INTREQ::IRQ13MON"; };
template<> struct address_map< 0x4003104c > { static constexpr const char * name_str = "INTREQ::IRQ14MON"; };
template<> struct address_map< 0x40031050 > { static constexpr const char * name_str = "INTREQ::IRQ15MON"; };
template<> struct address_map< 0x40031054 > { static constexpr const char * name_str = "INTREQ::IRQ16MON"; };
template<> struct address_map< 0x40031058 > { static constexpr const char * name_str = "INTREQ::IRQ17MON"; };
template<> struct address_map< 0x4003105c > { static constexpr const char * name_str = "INTREQ::IRQ18MON"; };
template<> struct address_map< 0x40031060 > { static constexpr const char * name_str = "INTREQ::IRQ19MON"; };
template<> struct address_map< 0x40031064 > { static constexpr const char * name_str = "INTREQ::IRQ20MON"; };
template<> struct address_map< 0x40031068 > { static constexpr const char * name_str = "INTREQ::IRQ21MON"; };
template<> struct address_map< 0x4003106c > { static constexpr const char * name_str = "INTREQ::IRQ22MON"; };
template<> struct address_map< 0x40031070 > { static constexpr const char * name_str = "INTREQ::IRQ23MON"; };
template<> struct address_map< 0x40031074 > { static constexpr const char * name_str = "INTREQ::IRQ24MON"; };
template<> struct address_map< 0x40031078 > { static constexpr const char * name_str = "INTREQ::IRQ25MON"; };
template<> struct address_map< 0x4003107c > { static constexpr const char * name_str = "INTREQ::IRQ26MON"; };
template<> struct address_map< 0x40031080 > { static constexpr const char * name_str = "INTREQ::IRQ27MON"; };
template<> struct address_map< 0x40031084 > { static constexpr const char * name_str = "INTREQ::IRQ28MON"; };
template<> struct address_map< 0x40031088 > { static constexpr const char * name_str = "INTREQ::IRQ29MON"; };
template<> struct address_map< 0x4003108c > { static constexpr const char * name_str = "INTREQ::IRQ30MON"; };
template<> struct address_map< 0x40031090 > { static constexpr const char * name_str = "INTREQ::IRQ31MON"; };
template<> struct address_map< 0x40031094 > { static constexpr const char * name_str = "INTREQ::IRQ32MON"; };
template<> struct address_map< 0x40031098 > { static constexpr const char * name_str = "INTREQ::IRQ33MON"; };
template<> struct address_map< 0x4003109c > { static constexpr const char * name_str = "INTREQ::IRQ34MON"; };
template<> struct address_map< 0x400310a0 > { static constexpr const char * name_str = "INTREQ::IRQ35MON"; };
template<> struct address_map< 0x400310a4 > { static constexpr const char * name_str = "INTREQ::IRQ36MON"; };
template<> struct address_map< 0x400310a8 > { static constexpr const char * name_str = "INTREQ::IRQ37MON"; };
template<> struct address_map< 0x400310ac > { static constexpr const char * name_str = "INTREQ::IRQ38MON"; };
template<> struct address_map< 0x400310b0 > { static constexpr const char * name_str = "INTREQ::IRQ39MON"; };
template<> struct address_map< 0x400310b4 > { static constexpr const char * name_str = "INTREQ::IRQ40MON"; };
template<> struct address_map< 0x400310b8 > { static constexpr const char * name_str = "INTREQ::IRQ41MON"; };
template<> struct address_map< 0x400310bc > { static constexpr const char * name_str = "INTREQ::IRQ42MON"; };
template<> struct address_map< 0x400310c0 > { static constexpr const char * name_str = "INTREQ::IRQ43MON"; };
template<> struct address_map< 0x400310c4 > { static constexpr const char * name_str = "INTREQ::IRQ44MON"; };
template<> struct address_map< 0x400310c8 > { static constexpr const char * name_str = "INTREQ::IRQ45MON"; };
template<> struct address_map< 0x400310cc > { static constexpr const char * name_str = "INTREQ::IRQ46MON"; };
template<> struct address_map< 0x400310d0 > { static constexpr const char * name_str = "INTREQ::IRQ47MON"; };
template<> struct address_map< 0x40031210 > { static constexpr const char * name_str = "INTREQ::RCINTSEL0"; };
template<> struct address_map< 0x40031214 > { static constexpr const char * name_str = "INTREQ::RCINTSEL1"; };
template<> struct address_map< 0x40033000 > { static constexpr const char * name_str = "GPIO::PFR0"; };
template<> struct address_map< 0x40033004 > { static constexpr const char * name_str = "GPIO::PFR1"; };
template<> struct address_map< 0x40033008 > { static constexpr const char * name_str = "GPIO::PFR2"; };
template<> struct address_map< 0x4003300c > { static constexpr const char * name_str = "GPIO::PFR3"; };
template<> struct address_map< 0x40033010 > { static constexpr const char * name_str = "GPIO::PFR4"; };
template<> struct address_map< 0x40033014 > { static constexpr const char * name_str = "GPIO::PFR5"; };
template<> struct address_map< 0x40033018 > { static constexpr const char * name_str = "GPIO::PFR6"; };
template<> struct address_map< 0x40033020 > { static constexpr const char * name_str = "GPIO::PFR8"; };
template<> struct address_map< 0x40033038 > { static constexpr const char * name_str = "GPIO::PFRE"; };
template<> struct address_map< 0x40033100 > { static constexpr const char * name_str = "GPIO::PCR0"; };
template<> struct address_map< 0x40033104 > { static constexpr const char * name_str = "GPIO::PCR1"; };
template<> struct address_map< 0x40033108 > { static constexpr const char * name_str = "GPIO::PCR2"; };
template<> struct address_map< 0x4003310c > { static constexpr const char * name_str = "GPIO::PCR3"; };
template<> struct address_map< 0x40033110 > { static constexpr const char * name_str = "GPIO::PCR4"; };
template<> struct address_map< 0x40033114 > { static constexpr const char * name_str = "GPIO::PCR5"; };
template<> struct address_map< 0x40033118 > { static constexpr const char * name_str = "GPIO::PCR6"; };
template<> struct address_map< 0x40033138 > { static constexpr const char * name_str = "GPIO::PCRE"; };
template<> struct address_map< 0x40033200 > { static constexpr const char * name_str = "GPIO::DDR0"; };
template<> struct address_map< 0x40033204 > { static constexpr const char * name_str = "GPIO::DDR1"; };
template<> struct address_map< 0x40033208 > { static constexpr const char * name_str = "GPIO::DDR2"; };
template<> struct address_map< 0x4003320c > { static constexpr const char * name_str = "GPIO::DDR3"; };
template<> struct address_map< 0x40033210 > { static constexpr const char * name_str = "GPIO::DDR4"; };
template<> struct address_map< 0x40033214 > { static constexpr const char * name_str = "GPIO::DDR5"; };
template<> struct address_map< 0x40033218 > { static constexpr const char * name_str = "GPIO::DDR6"; };
template<> struct address_map< 0x40033220 > { static constexpr const char * name_str = "GPIO::DDR8"; };
template<> struct address_map< 0x40033238 > { static constexpr const char * name_str = "GPIO::DDRE"; };
template<> struct address_map< 0x40033300 > { static constexpr const char * name_str = "GPIO::PDIR0"; };
template<> struct address_map< 0x40033304 > { static constexpr const char * name_str = "GPIO::PDIR1"; };
template<> struct address_map< 0x40033308 > { static constexpr const char * name_str = "GPIO::PDIR2"; };
template<> struct address_map< 0x4003330c > { static constexpr const char * name_str = "GPIO::PDIR3"; };
template<> struct address_map< 0x40033310 > { static constexpr const char * name_str = "GPIO::PDIR4"; };
template<> struct address_map< 0x40033314 > { static constexpr const char * name_str = "GPIO::PDIR5"; };
template<> struct address_map< 0x40033318 > { static constexpr const char * name_str = "GPIO::PDIR6"; };
template<> struct address_map< 0x40033320 > { static constexpr const char * name_str = "GPIO::PDIR8"; };
template<> struct address_map< 0x40033338 > { static constexpr const char * name_str = "GPIO::PDIRE"; };
template<> struct address_map< 0x40033400 > { static constexpr const char * name_str = "GPIO::PDOR0"; };
template<> struct address_map< 0x40033404 > { static constexpr const char * name_str = "GPIO::PDOR1"; };
template<> struct address_map< 0x40033408 > { static constexpr const char * name_str = "GPIO::PDOR2"; };
template<> struct address_map< 0x4003340c > { static constexpr const char * name_str = "GPIO::PDOR3"; };
template<> struct address_map< 0x40033410 > { static constexpr const char * name_str = "GPIO::PDOR4"; };
template<> struct address_map< 0x40033414 > { static constexpr const char * name_str = "GPIO::PDOR5"; };
template<> struct address_map< 0x40033418 > { static constexpr const char * name_str = "GPIO::PDOR6"; };
template<> struct address_map< 0x40033420 > { static constexpr const char * name_str = "GPIO::PDOR8"; };
template<> struct address_map< 0x40033438 > { static constexpr const char * name_str = "GPIO::PDORE"; };
template<> struct address_map< 0x40033500 > { static constexpr const char * name_str = "GPIO::ADE"; };
template<> struct address_map< 0x40033580 > { static constexpr const char * name_str = "GPIO::SPSR"; };
template<> struct address_map< 0x40033600 > { static constexpr const char * name_str = "GPIO::EPFR00"; };
template<> struct address_map< 0x40033604 > { static constexpr const char * name_str = "GPIO::EPFR01"; };
template<> struct address_map< 0x40033610 > { static constexpr const char * name_str = "GPIO::EPFR04"; };
template<> struct address_map< 0x40033614 > { static constexpr const char * name_str = "GPIO::EPFR05"; };
template<> struct address_map< 0x40033618 > { static constexpr const char * name_str = "GPIO::EPFR06"; };
template<> struct address_map< 0x4003361c > { static constexpr const char * name_str = "GPIO::EPFR07"; };
template<> struct address_map< 0x40033620 > { static constexpr const char * name_str = "GPIO::EPFR08"; };
template<> struct address_map< 0x40033624 > { static constexpr const char * name_str = "GPIO::EPFR09"; };
template<> struct address_map< 0x40033628 > { static constexpr const char * name_str = "GPIO::EPFR10"; };
template<> struct address_map< 0x4003362c > { static constexpr const char * name_str = "GPIO::EPFR11"; };
template<> struct address_map< 0x40033630 > { static constexpr const char * name_str = "GPIO::EPFR12"; };
template<> struct address_map< 0x40033634 > { static constexpr const char * name_str = "GPIO::EPFR13"; };
template<> struct address_map< 0x4003363c > { static constexpr const char * name_str = "GPIO::EPFR15"; };
template<> struct address_map< 0x40033640 > { static constexpr const char * name_str = "GPIO::EPFR16"; };
template<> struct address_map< 0x40033648 > { static constexpr const char * name_str = "GPIO::EPFR18"; };
template<> struct address_map< 0x40033700 > { static constexpr const char * name_str = "GPIO::PZR0"; };
template<> struct address_map< 0x40033710 > { static constexpr const char * name_str = "GPIO::PZR4"; };
template<> struct address_map< 0x40033714 > { static constexpr const char * name_str = "GPIO::PZR5"; };
template<> struct address_map< 0x40033718 > { static constexpr const char * name_str = "GPIO::PZR6"; };
template<> struct address_map< 0x40034000 > { static constexpr const char * name_str = "HDMICEC0::TXCTRL"; };
template<> struct address_map< 0x40034004 > { static constexpr const char * name_str = "HDMICEC0::TXDATA"; };
template<> struct address_map< 0x40034008 > { static constexpr const char * name_str = "HDMICEC0::TXSTS"; };
template<> struct address_map< 0x4003400c > { static constexpr const char * name_str = "HDMICEC0::SFREE"; };
template<> struct address_map< 0x40034040 > { static constexpr const char * name_str = "HDMICEC0::RCST"; };
template<> struct address_map< 0x40034041 > { static constexpr const char * name_str = "HDMICEC0::RCCR"; };
template<> struct address_map< 0x40034044 > { static constexpr const char * name_str = "HDMICEC0::RCDAHW"; };
template<> struct address_map< 0x40034045 > { static constexpr const char * name_str = "HDMICEC0::RCSHW"; };
template<> struct address_map< 0x40034049 > { static constexpr const char * name_str = "HDMICEC0::RCDBHW"; };
template<> struct address_map< 0x4003404c > { static constexpr const char * name_str = "HDMICEC0::RCADR2"; };
template<> struct address_map< 0x4003404d > { static constexpr const char * name_str = "HDMICEC0::RCADR1"; };
template<> struct address_map< 0x40034050 > { static constexpr const char * name_str = "HDMICEC0::RCDTHL"; };
template<> struct address_map< 0x40034051 > { static constexpr const char * name_str = "HDMICEC0::RCDTHH"; };
template<> struct address_map< 0x40034054 > { static constexpr const char * name_str = "HDMICEC0::RCDTLL"; };
template<> struct address_map< 0x40034055 > { static constexpr const char * name_str = "HDMICEC0::RCDTLH"; };
template<> struct address_map< 0x40034058 > { static constexpr const char * name_str = "HDMICEC0::RCCKD"; };
template<> struct address_map< 0x4003405c > { static constexpr const char * name_str = "HDMICEC0::RCRHW"; };
template<> struct address_map< 0x4003405d > { static constexpr const char * name_str = "HDMICEC0::RCRC"; };
template<> struct address_map< 0x40034061 > { static constexpr const char * name_str = "HDMICEC0::RCLE"; };
template<> struct address_map< 0x40034064 > { static constexpr const char * name_str = "HDMICEC0::RCLESW"; };
template<> struct address_map< 0x40034065 > { static constexpr const char * name_str = "HDMICEC0::RCLELW"; };
template<> struct address_map< 0x40034100 > { static constexpr const char * name_str = "HDMICEC1::TXCTRL"; };
template<> struct address_map< 0x40034104 > { static constexpr const char * name_str = "HDMICEC1::TXDATA"; };
template<> struct address_map< 0x40034108 > { static constexpr const char * name_str = "HDMICEC1::TXSTS"; };
template<> struct address_map< 0x4003410c > { static constexpr const char * name_str = "HDMICEC1::SFREE"; };
template<> struct address_map< 0x40034140 > { static constexpr const char * name_str = "HDMICEC1::RCST"; };
template<> struct address_map< 0x40034141 > { static constexpr const char * name_str = "HDMICEC1::RCCR"; };
template<> struct address_map< 0x40034144 > { static constexpr const char * name_str = "HDMICEC1::RCDAHW"; };
template<> struct address_map< 0x40034145 > { static constexpr const char * name_str = "HDMICEC1::RCSHW"; };
template<> struct address_map< 0x40034149 > { static constexpr const char * name_str = "HDMICEC1::RCDBHW"; };
template<> struct address_map< 0x4003414c > { static constexpr const char * name_str = "HDMICEC1::RCADR2"; };
template<> struct address_map< 0x4003414d > { static constexpr const char * name_str = "HDMICEC1::RCADR1"; };
template<> struct address_map< 0x40034150 > { static constexpr const char * name_str = "HDMICEC1::RCDTHL"; };
template<> struct address_map< 0x40034151 > { static constexpr const char * name_str = "HDMICEC1::RCDTHH"; };
template<> struct address_map< 0x40034154 > { static constexpr const char * name_str = "HDMICEC1::RCDTLL"; };
template<> struct address_map< 0x40034155 > { static constexpr const char * name_str = "HDMICEC1::RCDTLH"; };
template<> struct address_map< 0x40034158 > { static constexpr const char * name_str = "HDMICEC1::RCCKD"; };
template<> struct address_map< 0x4003415c > { static constexpr const char * name_str = "HDMICEC1::RCRHW"; };
template<> struct address_map< 0x4003415d > { static constexpr const char * name_str = "HDMICEC1::RCRC"; };
template<> struct address_map< 0x40034161 > { static constexpr const char * name_str = "HDMICEC1::RCLE"; };
template<> struct address_map< 0x40034164 > { static constexpr const char * name_str = "HDMICEC1::RCLESW"; };
template<> struct address_map< 0x40034165 > { static constexpr const char * name_str = "HDMICEC1::RCLELW"; };
template<> struct address_map< 0x40035000 > { static constexpr const char * name_str = "LVD::LVD_CTL"; };
template<> struct address_map< 0x40035004 > { static constexpr const char * name_str = "LVD::LVD_STR"; };
template<> struct address_map< 0x40035008 > { static constexpr const char * name_str = "LVD::LVD_CLR"; };
template<> struct address_map< 0x4003500c > { static constexpr const char * name_str = "LVD::LVD_RLR"; };
template<> struct address_map< 0x40035010 > { static constexpr const char * name_str = "LVD::LVD_STR2"; };
template<> struct address_map< 0x40035100 > { static constexpr const char * name_str = "DS::REG_CTL"; };
template<> struct address_map< 0x40035104 > { static constexpr const char * name_str = "DS::RCK_CTL"; };
template<> struct address_map< 0x40035800 > { static constexpr const char * name_str = "DS::PMD_CTL"; };
template<> struct address_map< 0x40035804 > { static constexpr const char * name_str = "DS::WRFSR"; };
template<> struct address_map< 0x40035808 > { static constexpr const char * name_str = "DS::WIFSR"; };
template<> struct address_map< 0x4003580c > { static constexpr const char * name_str = "DS::WIER"; };
template<> struct address_map< 0x40035810 > { static constexpr const char * name_str = "DS::WILVR"; };
template<> struct address_map< 0x40035814 > { static constexpr const char * name_str = "DS::DSRAMR"; };
template<> struct address_map< 0x40035900 > { static constexpr const char * name_str = "DS::BUR01"; };
template<> struct address_map< 0x40035901 > { static constexpr const char * name_str = "DS::BUR02"; };
template<> struct address_map< 0x40035902 > { static constexpr const char * name_str = "DS::BUR03"; };
template<> struct address_map< 0x40035903 > { static constexpr const char * name_str = "DS::BUR04"; };
template<> struct address_map< 0x40035904 > { static constexpr const char * name_str = "DS::BUR05"; };
template<> struct address_map< 0x40035905 > { static constexpr const char * name_str = "DS::BUR06"; };
template<> struct address_map< 0x40035906 > { static constexpr const char * name_str = "DS::BUR07"; };
template<> struct address_map< 0x40035907 > { static constexpr const char * name_str = "DS::BUR08"; };
template<> struct address_map< 0x40035908 > { static constexpr const char * name_str = "DS::BUR09"; };
template<> struct address_map< 0x40035909 > { static constexpr const char * name_str = "DS::BUR10"; };
template<> struct address_map< 0x4003590a > { static constexpr const char * name_str = "DS::BUR11"; };
template<> struct address_map< 0x4003590b > { static constexpr const char * name_str = "DS::BUR12"; };
template<> struct address_map< 0x4003590c > { static constexpr const char * name_str = "DS::BUR13"; };
template<> struct address_map< 0x4003590d > { static constexpr const char * name_str = "DS::BUR14"; };
template<> struct address_map< 0x4003590e > { static constexpr const char * name_str = "DS::BUR15"; };
template<> struct address_map< 0x4003590f > { static constexpr const char * name_str = "DS::BUR16"; };
template<> struct address_map< 0x40038000 > { static constexpr const char * name_str = "MFS0::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SMR, MFS0::I2C_SMR, MFS0::UART_SMR */
template<> struct address_map< 0x40038001 > { static constexpr const char * name_str = "MFS0::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SCR, MFS0::I2C_IBCR, MFS0::UART_SCR */
template<> struct address_map< 0x40038004 > { static constexpr const char * name_str = "MFS0::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_ESCR, MFS0::I2C_IBSR, MFS0::UART_ESCR */
template<> struct address_map< 0x40038005 > { static constexpr const char * name_str = "MFS0::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SSR, MFS0::I2C_SSR, MFS0::UART_SSR */
template<> struct address_map< 0x40038008 > { static constexpr const char * name_str = "MFS0::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_RDR, MFS0::CSIO_TDR, MFS0::I2C_RDR, MFS0::I2C_TDR, MFS0::UART_RDR, MFS0::UART_TDR */
template<> struct address_map< 0x4003800c > { static constexpr const char * name_str = "MFS0::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_BGR, MFS0::I2C_BGR, MFS0::UART_BGR */
template<> struct address_map< 0x40038010 > { static constexpr const char * name_str = "MFS0::I2C_ISBA"; };
template<> struct address_map< 0x40038011 > { static constexpr const char * name_str = "MFS0::I2C_ISMK"; };
template<> struct address_map< 0x40038014 > { static constexpr const char * name_str = "MFS0::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FCR0, MFS0::I2C_FCR0, MFS0::UART_FCR0 */
template<> struct address_map< 0x40038015 > { static constexpr const char * name_str = "MFS0::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FCR1, MFS0::I2C_FCR1, MFS0::UART_FCR1 */
template<> struct address_map< 0x40038018 > { static constexpr const char * name_str = "MFS0::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FBYTE1, MFS0::I2C_FBYTE1, MFS0::UART_FBYTE1 */
template<> struct address_map< 0x40038019 > { static constexpr const char * name_str = "MFS0::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FBYTE2, MFS0::I2C_FBYTE2, MFS0::UART_FBYTE2 */
template<> struct address_map< 0x4003801d > { static constexpr const char * name_str = "MFS0::I2C_EIBCR"; };
template<> struct address_map< 0x40038100 > { static constexpr const char * name_str = "MFS1::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SMR, MFS1::I2C_SMR, MFS1::UART_SMR */
template<> struct address_map< 0x40038101 > { static constexpr const char * name_str = "MFS1::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SCR, MFS1::I2C_IBCR, MFS1::UART_SCR */
template<> struct address_map< 0x40038104 > { static constexpr const char * name_str = "MFS1::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_ESCR, MFS1::I2C_IBSR, MFS1::UART_ESCR */
template<> struct address_map< 0x40038105 > { static constexpr const char * name_str = "MFS1::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SSR, MFS1::I2C_SSR, MFS1::UART_SSR */
template<> struct address_map< 0x40038108 > { static constexpr const char * name_str = "MFS1::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_RDR, MFS1::CSIO_TDR, MFS1::I2C_RDR, MFS1::I2C_TDR, MFS1::UART_RDR, MFS1::UART_TDR */
template<> struct address_map< 0x4003810c > { static constexpr const char * name_str = "MFS1::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_BGR, MFS1::I2C_BGR, MFS1::UART_BGR */
template<> struct address_map< 0x40038110 > { static constexpr const char * name_str = "MFS1::I2C_ISBA"; };
template<> struct address_map< 0x40038111 > { static constexpr const char * name_str = "MFS1::I2C_ISMK"; };
template<> struct address_map< 0x40038114 > { static constexpr const char * name_str = "MFS1::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FCR0, MFS1::I2C_FCR0, MFS1::UART_FCR0 */
template<> struct address_map< 0x40038115 > { static constexpr const char * name_str = "MFS1::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FCR1, MFS1::I2C_FCR1, MFS1::UART_FCR1 */
template<> struct address_map< 0x40038118 > { static constexpr const char * name_str = "MFS1::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FBYTE1, MFS1::I2C_FBYTE1, MFS1::UART_FBYTE1 */
template<> struct address_map< 0x40038119 > { static constexpr const char * name_str = "MFS1::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FBYTE2, MFS1::I2C_FBYTE2, MFS1::UART_FBYTE2 */
template<> struct address_map< 0x4003811d > { static constexpr const char * name_str = "MFS1::I2C_EIBCR"; };
template<> struct address_map< 0x40038200 > { static constexpr const char * name_str = "MFS2::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SMR, MFS2::I2C_SMR, MFS2::UART_SMR */
template<> struct address_map< 0x40038201 > { static constexpr const char * name_str = "MFS2::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SCR, MFS2::I2C_IBCR, MFS2::UART_SCR */
template<> struct address_map< 0x40038204 > { static constexpr const char * name_str = "MFS2::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_ESCR, MFS2::I2C_IBSR, MFS2::UART_ESCR */
template<> struct address_map< 0x40038205 > { static constexpr const char * name_str = "MFS2::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SSR, MFS2::I2C_SSR, MFS2::UART_SSR */
template<> struct address_map< 0x40038208 > { static constexpr const char * name_str = "MFS2::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_RDR, MFS2::CSIO_TDR, MFS2::I2C_RDR, MFS2::I2C_TDR, MFS2::UART_RDR, MFS2::UART_TDR */
template<> struct address_map< 0x4003820c > { static constexpr const char * name_str = "MFS2::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_BGR, MFS2::I2C_BGR, MFS2::UART_BGR */
template<> struct address_map< 0x40038210 > { static constexpr const char * name_str = "MFS2::I2C_ISBA"; };
template<> struct address_map< 0x40038211 > { static constexpr const char * name_str = "MFS2::I2C_ISMK"; };
template<> struct address_map< 0x40038214 > { static constexpr const char * name_str = "MFS2::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_FCR0, MFS2::I2C_FCR0, MFS2::UART_FCR0 */
template<> struct address_map< 0x40038215 > { static constexpr const char * name_str = "MFS2::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_FCR1, MFS2::I2C_FCR1, MFS2::UART_FCR1 */
template<> struct address_map< 0x40038218 > { static constexpr const char * name_str = "MFS2::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_FBYTE1, MFS2::I2C_FBYTE1, MFS2::UART_FBYTE1 */
template<> struct address_map< 0x40038219 > { static constexpr const char * name_str = "MFS2::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_FBYTE2, MFS2::I2C_FBYTE2, MFS2::UART_FBYTE2 */
template<> struct address_map< 0x4003821d > { static constexpr const char * name_str = "MFS2::I2C_EIBCR"; };
template<> struct address_map< 0x40038300 > { static constexpr const char * name_str = "MFS3::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SMR, MFS3::I2C_SMR, MFS3::UART_SMR */
template<> struct address_map< 0x40038301 > { static constexpr const char * name_str = "MFS3::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SCR, MFS3::I2C_IBCR, MFS3::UART_SCR */
template<> struct address_map< 0x40038304 > { static constexpr const char * name_str = "MFS3::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_ESCR, MFS3::I2C_IBSR, MFS3::UART_ESCR */
template<> struct address_map< 0x40038305 > { static constexpr const char * name_str = "MFS3::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SSR, MFS3::I2C_SSR, MFS3::UART_SSR */
template<> struct address_map< 0x40038308 > { static constexpr const char * name_str = "MFS3::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_RDR, MFS3::CSIO_TDR, MFS3::I2C_RDR, MFS3::I2C_TDR, MFS3::UART_RDR, MFS3::UART_TDR */
template<> struct address_map< 0x4003830c > { static constexpr const char * name_str = "MFS3::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_BGR, MFS3::I2C_BGR, MFS3::UART_BGR */
template<> struct address_map< 0x40038310 > { static constexpr const char * name_str = "MFS3::I2C_ISBA"; };
template<> struct address_map< 0x40038311 > { static constexpr const char * name_str = "MFS3::I2C_ISMK"; };
template<> struct address_map< 0x40038314 > { static constexpr const char * name_str = "MFS3::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FCR0, MFS3::I2C_FCR0, MFS3::UART_FCR0 */
template<> struct address_map< 0x40038315 > { static constexpr const char * name_str = "MFS3::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FCR1, MFS3::I2C_FCR1, MFS3::UART_FCR1 */
template<> struct address_map< 0x40038318 > { static constexpr const char * name_str = "MFS3::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FBYTE1, MFS3::I2C_FBYTE1, MFS3::UART_FBYTE1 */
template<> struct address_map< 0x40038319 > { static constexpr const char * name_str = "MFS3::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FBYTE2, MFS3::I2C_FBYTE2, MFS3::UART_FBYTE2 */
template<> struct address_map< 0x4003831d > { static constexpr const char * name_str = "MFS3::I2C_EIBCR"; };
template<> struct address_map< 0x40038400 > { static constexpr const char * name_str = "MFS4::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SMR, MFS4::I2C_SMR, MFS4::UART_SMR */
template<> struct address_map< 0x40038401 > { static constexpr const char * name_str = "MFS4::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SCR, MFS4::I2C_IBCR, MFS4::UART_SCR */
template<> struct address_map< 0x40038404 > { static constexpr const char * name_str = "MFS4::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_ESCR, MFS4::I2C_IBSR, MFS4::UART_ESCR */
template<> struct address_map< 0x40038405 > { static constexpr const char * name_str = "MFS4::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SSR, MFS4::I2C_SSR, MFS4::UART_SSR */
template<> struct address_map< 0x40038408 > { static constexpr const char * name_str = "MFS4::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_RDR, MFS4::CSIO_TDR, MFS4::I2C_RDR, MFS4::I2C_TDR, MFS4::UART_RDR, MFS4::UART_TDR */
template<> struct address_map< 0x4003840c > { static constexpr const char * name_str = "MFS4::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_BGR, MFS4::I2C_BGR, MFS4::UART_BGR */
template<> struct address_map< 0x40038410 > { static constexpr const char * name_str = "MFS4::I2C_ISBA"; };
template<> struct address_map< 0x40038411 > { static constexpr const char * name_str = "MFS4::I2C_ISMK"; };
template<> struct address_map< 0x40038414 > { static constexpr const char * name_str = "MFS4::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FCR0, MFS4::I2C_FCR0, MFS4::UART_FCR0 */
template<> struct address_map< 0x40038415 > { static constexpr const char * name_str = "MFS4::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FCR1, MFS4::I2C_FCR1, MFS4::UART_FCR1 */
template<> struct address_map< 0x40038418 > { static constexpr const char * name_str = "MFS4::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FBYTE1, MFS4::I2C_FBYTE1, MFS4::UART_FBYTE1 */
template<> struct address_map< 0x40038419 > { static constexpr const char * name_str = "MFS4::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FBYTE2, MFS4::I2C_FBYTE2, MFS4::UART_FBYTE2 */
template<> struct address_map< 0x4003841d > { static constexpr const char * name_str = "MFS4::I2C_EIBCR"; };
template<> struct address_map< 0x40038500 > { static constexpr const char * name_str = "MFS5::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SMR, MFS5::I2C_SMR, MFS5::UART_SMR */
template<> struct address_map< 0x40038501 > { static constexpr const char * name_str = "MFS5::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SCR, MFS5::I2C_IBCR, MFS5::UART_SCR */
template<> struct address_map< 0x40038504 > { static constexpr const char * name_str = "MFS5::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_ESCR, MFS5::I2C_IBSR, MFS5::UART_ESCR */
template<> struct address_map< 0x40038505 > { static constexpr const char * name_str = "MFS5::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SSR, MFS5::I2C_SSR, MFS5::UART_SSR */
template<> struct address_map< 0x40038508 > { static constexpr const char * name_str = "MFS5::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_RDR, MFS5::CSIO_TDR, MFS5::I2C_RDR, MFS5::I2C_TDR, MFS5::UART_RDR, MFS5::UART_TDR */
template<> struct address_map< 0x4003850c > { static constexpr const char * name_str = "MFS5::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_BGR, MFS5::I2C_BGR, MFS5::UART_BGR */
template<> struct address_map< 0x40038510 > { static constexpr const char * name_str = "MFS5::I2C_ISBA"; };
template<> struct address_map< 0x40038511 > { static constexpr const char * name_str = "MFS5::I2C_ISMK"; };
template<> struct address_map< 0x40038514 > { static constexpr const char * name_str = "MFS5::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FCR0, MFS5::I2C_FCR0, MFS5::UART_FCR0 */
template<> struct address_map< 0x40038515 > { static constexpr const char * name_str = "MFS5::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FCR1, MFS5::I2C_FCR1, MFS5::UART_FCR1 */
template<> struct address_map< 0x40038518 > { static constexpr const char * name_str = "MFS5::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FBYTE1, MFS5::I2C_FBYTE1, MFS5::UART_FBYTE1 */
template<> struct address_map< 0x40038519 > { static constexpr const char * name_str = "MFS5::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FBYTE2, MFS5::I2C_FBYTE2, MFS5::UART_FBYTE2 */
template<> struct address_map< 0x4003851d > { static constexpr const char * name_str = "MFS5::I2C_EIBCR"; };
template<> struct address_map< 0x40038600 > { static constexpr const char * name_str = "MFS6::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SMR, MFS6::I2C_SMR, MFS6::UART_SMR */
template<> struct address_map< 0x40038601 > { static constexpr const char * name_str = "MFS6::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SCR, MFS6::I2C_IBCR, MFS6::UART_SCR */
template<> struct address_map< 0x40038604 > { static constexpr const char * name_str = "MFS6::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_ESCR, MFS6::I2C_IBSR, MFS6::UART_ESCR */
template<> struct address_map< 0x40038605 > { static constexpr const char * name_str = "MFS6::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SSR, MFS6::I2C_SSR, MFS6::UART_SSR */
template<> struct address_map< 0x40038608 > { static constexpr const char * name_str = "MFS6::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_RDR, MFS6::CSIO_TDR, MFS6::I2C_RDR, MFS6::I2C_TDR, MFS6::UART_RDR, MFS6::UART_TDR */
template<> struct address_map< 0x4003860c > { static constexpr const char * name_str = "MFS6::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_BGR, MFS6::I2C_BGR, MFS6::UART_BGR */
template<> struct address_map< 0x40038610 > { static constexpr const char * name_str = "MFS6::I2C_ISBA"; };
template<> struct address_map< 0x40038611 > { static constexpr const char * name_str = "MFS6::I2C_ISMK"; };
template<> struct address_map< 0x40038614 > { static constexpr const char * name_str = "MFS6::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FCR0, MFS6::I2C_FCR0, MFS6::UART_FCR0 */
template<> struct address_map< 0x40038615 > { static constexpr const char * name_str = "MFS6::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FCR1, MFS6::I2C_FCR1, MFS6::UART_FCR1 */
template<> struct address_map< 0x40038618 > { static constexpr const char * name_str = "MFS6::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FBYTE1, MFS6::I2C_FBYTE1, MFS6::UART_FBYTE1 */
template<> struct address_map< 0x40038619 > { static constexpr const char * name_str = "MFS6::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FBYTE2, MFS6::I2C_FBYTE2, MFS6::UART_FBYTE2 */
template<> struct address_map< 0x4003861d > { static constexpr const char * name_str = "MFS6::I2C_EIBCR"; };
template<> struct address_map< 0x40038700 > { static constexpr const char * name_str = "MFS7::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SMR, MFS7::I2C_SMR, MFS7::UART_SMR */
template<> struct address_map< 0x40038701 > { static constexpr const char * name_str = "MFS7::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SCR, MFS7::I2C_IBCR, MFS7::UART_SCR */
template<> struct address_map< 0x40038704 > { static constexpr const char * name_str = "MFS7::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_ESCR, MFS7::I2C_IBSR, MFS7::UART_ESCR */
template<> struct address_map< 0x40038705 > { static constexpr const char * name_str = "MFS7::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SSR, MFS7::I2C_SSR, MFS7::UART_SSR */
template<> struct address_map< 0x40038708 > { static constexpr const char * name_str = "MFS7::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_RDR, MFS7::CSIO_TDR, MFS7::I2C_RDR, MFS7::I2C_TDR, MFS7::UART_RDR, MFS7::UART_TDR */
template<> struct address_map< 0x4003870c > { static constexpr const char * name_str = "MFS7::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_BGR, MFS7::I2C_BGR, MFS7::UART_BGR */
template<> struct address_map< 0x40038710 > { static constexpr const char * name_str = "MFS7::I2C_ISBA"; };
template<> struct address_map< 0x40038711 > { static constexpr const char * name_str = "MFS7::I2C_ISMK"; };
template<> struct address_map< 0x40038714 > { static constexpr const char * name_str = "MFS7::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FCR0, MFS7::I2C_FCR0, MFS7::UART_FCR0 */
template<> struct address_map< 0x40038715 > { static constexpr const char * name_str = "MFS7::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FCR1, MFS7::I2C_FCR1, MFS7::UART_FCR1 */
template<> struct address_map< 0x40038718 > { static constexpr const char * name_str = "MFS7::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FBYTE1, MFS7::I2C_FBYTE1, MFS7::UART_FBYTE1 */
template<> struct address_map< 0x40038719 > { static constexpr const char * name_str = "MFS7::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FBYTE2, MFS7::I2C_FBYTE2, MFS7::UART_FBYTE2 */
template<> struct address_map< 0x4003871d > { static constexpr const char * name_str = "MFS7::I2C_EIBCR"; };
template<> struct address_map< 0x40038a00 > { static constexpr const char * name_str = "MFS10::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_SMR, MFS10::I2C_SMR, MFS10::UART_SMR */
template<> struct address_map< 0x40038a01 > { static constexpr const char * name_str = "MFS10::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_SCR, MFS10::I2C_IBCR, MFS10::UART_SCR */
template<> struct address_map< 0x40038a04 > { static constexpr const char * name_str = "MFS10::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_ESCR, MFS10::I2C_IBSR, MFS10::UART_ESCR */
template<> struct address_map< 0x40038a05 > { static constexpr const char * name_str = "MFS10::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_SSR, MFS10::I2C_SSR, MFS10::UART_SSR */
template<> struct address_map< 0x40038a08 > { static constexpr const char * name_str = "MFS10::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_RDR, MFS10::CSIO_TDR, MFS10::I2C_RDR, MFS10::I2C_TDR, MFS10::UART_RDR, MFS10::UART_TDR */
template<> struct address_map< 0x40038a0c > { static constexpr const char * name_str = "MFS10::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_BGR, MFS10::I2C_BGR, MFS10::UART_BGR */
template<> struct address_map< 0x40038a10 > { static constexpr const char * name_str = "MFS10::I2C_ISBA"; };
template<> struct address_map< 0x40038a11 > { static constexpr const char * name_str = "MFS10::I2C_ISMK"; };
template<> struct address_map< 0x40038a14 > { static constexpr const char * name_str = "MFS10::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_FCR0, MFS10::I2C_FCR0, MFS10::UART_FCR0 */
template<> struct address_map< 0x40038a15 > { static constexpr const char * name_str = "MFS10::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_FCR1, MFS10::I2C_FCR1, MFS10::UART_FCR1 */
template<> struct address_map< 0x40038a18 > { static constexpr const char * name_str = "MFS10::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_FBYTE1, MFS10::I2C_FBYTE1, MFS10::UART_FBYTE1 */
template<> struct address_map< 0x40038a19 > { static constexpr const char * name_str = "MFS10::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS10::CSIO_FBYTE2, MFS10::I2C_FBYTE2, MFS10::UART_FBYTE2 */
template<> struct address_map< 0x40038a1d > { static constexpr const char * name_str = "MFS10::I2C_EIBCR"; };
template<> struct address_map< 0x40038b00 > { static constexpr const char * name_str = "MFS11::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_SMR, MFS11::I2C_SMR, MFS11::UART_SMR */
template<> struct address_map< 0x40038b01 > { static constexpr const char * name_str = "MFS11::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_SCR, MFS11::I2C_IBCR, MFS11::UART_SCR */
template<> struct address_map< 0x40038b04 > { static constexpr const char * name_str = "MFS11::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_ESCR, MFS11::I2C_IBSR, MFS11::UART_ESCR */
template<> struct address_map< 0x40038b05 > { static constexpr const char * name_str = "MFS11::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_SSR, MFS11::I2C_SSR, MFS11::UART_SSR */
template<> struct address_map< 0x40038b08 > { static constexpr const char * name_str = "MFS11::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_RDR, MFS11::CSIO_TDR, MFS11::I2C_RDR, MFS11::I2C_TDR, MFS11::UART_RDR, MFS11::UART_TDR */
template<> struct address_map< 0x40038b0c > { static constexpr const char * name_str = "MFS11::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_BGR, MFS11::I2C_BGR, MFS11::UART_BGR */
template<> struct address_map< 0x40038b10 > { static constexpr const char * name_str = "MFS11::I2C_ISBA"; };
template<> struct address_map< 0x40038b11 > { static constexpr const char * name_str = "MFS11::I2C_ISMK"; };
template<> struct address_map< 0x40038b14 > { static constexpr const char * name_str = "MFS11::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_FCR0, MFS11::I2C_FCR0, MFS11::UART_FCR0 */
template<> struct address_map< 0x40038b15 > { static constexpr const char * name_str = "MFS11::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_FCR1, MFS11::I2C_FCR1, MFS11::UART_FCR1 */
template<> struct address_map< 0x40038b18 > { static constexpr const char * name_str = "MFS11::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_FBYTE1, MFS11::I2C_FBYTE1, MFS11::UART_FBYTE1 */
template<> struct address_map< 0x40038b19 > { static constexpr const char * name_str = "MFS11::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS11::CSIO_FBYTE2, MFS11::I2C_FBYTE2, MFS11::UART_FBYTE2 */
template<> struct address_map< 0x40038b1d > { static constexpr const char * name_str = "MFS11::I2C_EIBCR"; };
template<> struct address_map< 0x40039000 > { static constexpr const char * name_str = "CRC::CRCCR"; };
template<> struct address_map< 0x40039004 > { static constexpr const char * name_str = "CRC::CRCINIT"; };
template<> struct address_map< 0x40039008 > { static constexpr const char * name_str = "CRC::CRCIN"; };
template<> struct address_map< 0x4003900c > { static constexpr const char * name_str = "CRC::CRCR"; };
template<> struct address_map< 0x4003a000 > { static constexpr const char * name_str = "WC::WCRD"; };
template<> struct address_map< 0x4003a001 > { static constexpr const char * name_str = "WC::WCRL"; };
template<> struct address_map< 0x4003a002 > { static constexpr const char * name_str = "WC::WCCR"; };
template<> struct address_map< 0x4003a010 > { static constexpr const char * name_str = "WC::CLK_SEL"; };
template<> struct address_map< 0x4003a014 > { static constexpr const char * name_str = "WC::CLK_EN"; };
template<> struct address_map< 0x4003b000 > { static constexpr const char * name_str = "RTC::WTCR1"; };
template<> struct address_map< 0x4003b004 > { static constexpr const char * name_str = "RTC::WTCR2"; };
template<> struct address_map< 0x4003b008 > { static constexpr const char * name_str = "RTC::WTBR"; };
template<> struct address_map< 0x4003b00c > { static constexpr const char * name_str = "RTC::WTSR"; };
template<> struct address_map< 0x4003b00d > { static constexpr const char * name_str = "RTC::WTMIR"; };
template<> struct address_map< 0x4003b00e > { static constexpr const char * name_str = "RTC::WTHR"; };
template<> struct address_map< 0x4003b00f > { static constexpr const char * name_str = "RTC::WTDR"; };
template<> struct address_map< 0x4003b010 > { static constexpr const char * name_str = "RTC::WTDW"; };
template<> struct address_map< 0x4003b011 > { static constexpr const char * name_str = "RTC::WTMOR"; };
template<> struct address_map< 0x4003b012 > { static constexpr const char * name_str = "RTC::WTYR"; };
template<> struct address_map< 0x4003b015 > { static constexpr const char * name_str = "RTC::ALMIR"; };
template<> struct address_map< 0x4003b016 > { static constexpr const char * name_str = "RTC::ALHR"; };
template<> struct address_map< 0x4003b017 > { static constexpr const char * name_str = "RTC::ALDR"; };
template<> struct address_map< 0x4003b019 > { static constexpr const char * name_str = "RTC::ALMOR"; };
template<> struct address_map< 0x4003b01a > { static constexpr const char * name_str = "RTC::ALYR"; };
template<> struct address_map< 0x4003b01c > { static constexpr const char * name_str = "RTC::WTTR"; };
template<> struct address_map< 0x4003b020 > { static constexpr const char * name_str = "RTC::WTCLKS"; };
template<> struct address_map< 0x4003b021 > { static constexpr const char * name_str = "RTC::WTCLKM"; };
template<> struct address_map< 0x4003b024 > { static constexpr const char * name_str = "RTC::WTCAL"; };
template<> struct address_map< 0x4003b026 > { static constexpr const char * name_str = "RTC::WTCALEN"; };
template<> struct address_map< 0x4003b028 > { static constexpr const char * name_str = "RTC::WTDIV"; };
template<> struct address_map< 0x4003b029 > { static constexpr const char * name_str = "RTC::WTDIVEN"; };
template<> struct address_map< 0x4003b02c > { static constexpr const char * name_str = "RTC::WTCALPRD"; };
template<> struct address_map< 0x4003b030 > { static constexpr const char * name_str = "RTC::WTCOSEL"; };
template<> struct address_map< 0x4003f000 > { static constexpr const char * name_str = "EXBUS::MODE0"; };
template<> struct address_map< 0x4003f004 > { static constexpr const char * name_str = "EXBUS::MODE1"; };
template<> struct address_map< 0x4003f018 > { static constexpr const char * name_str = "EXBUS::MODE6"; };
template<> struct address_map< 0x4003f01c > { static constexpr const char * name_str = "EXBUS::MODE7"; };
template<> struct address_map< 0x4003f020 > { static constexpr const char * name_str = "EXBUS::TIM0"; };
template<> struct address_map< 0x4003f024 > { static constexpr const char * name_str = "EXBUS::TIM1"; };
template<> struct address_map< 0x4003f038 > { static constexpr const char * name_str = "EXBUS::TIM6"; };
template<> struct address_map< 0x4003f03c > { static constexpr const char * name_str = "EXBUS::TIM7"; };
template<> struct address_map< 0x4003f040 > { static constexpr const char * name_str = "EXBUS::AREA0"; };
template<> struct address_map< 0x4003f044 > { static constexpr const char * name_str = "EXBUS::AREA1"; };
template<> struct address_map< 0x4003f058 > { static constexpr const char * name_str = "EXBUS::AREA6"; };
template<> struct address_map< 0x4003f05c > { static constexpr const char * name_str = "EXBUS::AREA7"; };
template<> struct address_map< 0x4003f060 > { static constexpr const char * name_str = "EXBUS::ATIM0"; };
template<> struct address_map< 0x4003f064 > { static constexpr const char * name_str = "EXBUS::ATIM1"; };
template<> struct address_map< 0x4003f078 > { static constexpr const char * name_str = "EXBUS::ATIM6"; };
template<> struct address_map< 0x4003f07c > { static constexpr const char * name_str = "EXBUS::ATIM7"; };
template<> struct address_map< 0x4003f300 > { static constexpr const char * name_str = "EXBUS::DCLKR"; };
template<> struct address_map< 0x40060000 > { static constexpr const char * name_str = "DMAC::DMACR"; };
template<> struct address_map< 0x40060010 > { static constexpr const char * name_str = "DMAC::DMACA0"; };
template<> struct address_map< 0x40060014 > { static constexpr const char * name_str = "DMAC::DMACB0"; };
template<> struct address_map< 0x40060018 > { static constexpr const char * name_str = "DMAC::DMACSA0"; };
template<> struct address_map< 0x4006001c > { static constexpr const char * name_str = "DMAC::DMACDA0"; };
template<> struct address_map< 0x40060020 > { static constexpr const char * name_str = "DMAC::DMACA1"; };
template<> struct address_map< 0x40060024 > { static constexpr const char * name_str = "DMAC::DMACB1"; };
template<> struct address_map< 0x40060028 > { static constexpr const char * name_str = "DMAC::DMACSA1"; };
template<> struct address_map< 0x4006002c > { static constexpr const char * name_str = "DMAC::DMACDA1"; };
template<> struct address_map< 0x40060030 > { static constexpr const char * name_str = "DMAC::DMACA2"; };
template<> struct address_map< 0x40060034 > { static constexpr const char * name_str = "DMAC::DMACB2"; };
template<> struct address_map< 0x40060038 > { static constexpr const char * name_str = "DMAC::DMACSA2"; };
template<> struct address_map< 0x4006003c > { static constexpr const char * name_str = "DMAC::DMACDA2"; };
template<> struct address_map< 0x40060040 > { static constexpr const char * name_str = "DMAC::DMACA3"; };
template<> struct address_map< 0x40060044 > { static constexpr const char * name_str = "DMAC::DMACB3"; };
template<> struct address_map< 0x40060048 > { static constexpr const char * name_str = "DMAC::DMACSA3"; };
template<> struct address_map< 0x4006004c > { static constexpr const char * name_str = "DMAC::DMACDA3"; };
template<> struct address_map< 0x40060050 > { static constexpr const char * name_str = "DMAC::DMACA4"; };
template<> struct address_map< 0x40060054 > { static constexpr const char * name_str = "DMAC::DMACB4"; };
template<> struct address_map< 0x40060058 > { static constexpr const char * name_str = "DMAC::DMACSA4"; };
template<> struct address_map< 0x4006005c > { static constexpr const char * name_str = "DMAC::DMACDA4"; };
template<> struct address_map< 0x40060060 > { static constexpr const char * name_str = "DMAC::DMACA5"; };
template<> struct address_map< 0x40060064 > { static constexpr const char * name_str = "DMAC::DMACB5"; };
template<> struct address_map< 0x40060068 > { static constexpr const char * name_str = "DMAC::DMACSA5"; };
template<> struct address_map< 0x4006006c > { static constexpr const char * name_str = "DMAC::DMACDA5"; };
template<> struct address_map< 0x40060070 > { static constexpr const char * name_str = "DMAC::DMACA6"; };
template<> struct address_map< 0x40060074 > { static constexpr const char * name_str = "DMAC::DMACB6"; };
template<> struct address_map< 0x40060078 > { static constexpr const char * name_str = "DMAC::DMACSA6"; };
template<> struct address_map< 0x4006007c > { static constexpr const char * name_str = "DMAC::DMACDA6"; };
template<> struct address_map< 0x40060080 > { static constexpr const char * name_str = "DMAC::DMACA7"; };
template<> struct address_map< 0x40060084 > { static constexpr const char * name_str = "DMAC::DMACB7"; };
template<> struct address_map< 0x40060088 > { static constexpr const char * name_str = "DMAC::DMACSA7"; };
template<> struct address_map< 0x4006008c > { static constexpr const char * name_str = "DMAC::DMACDA7"; };

} // namespace mptl

#endif // ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
