/*
 * OpenMPTL - C++ Microprocessor Template Library
 *
 * This program is a derivative representation of a CMSIS System View
 * Description (SVD) file, and is subject to the corresponding license
 * (see "License.txt" in the parent directory).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

////////////////////////////////////////////////////////////////////////
//
//  Import from CMSIS-SVD: "Spansion/MB9AFB4xN.svd"
//
//  name: MB9AFB4xN
//  version: 1.7
//  description: MB9AFB4xN
//  --------------------------------------------------------------------
//
//  C++ Header file, containing architecture specific register
//  declarations for use in OpenMPTL. It has been converted directly
//  from a CMSIS-SVD file.
//
//  https://digint.ch/openmptl
//  https://github.com/posborne/cmsis-svd
//

#ifndef ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
#define ARCH_REG_ADDRESS_MAP_HPP_INCLUDED

#warning "using untested register declarations"

#include <register_type.hpp>

namespace mptl {

template<reg_addr_t addr>
struct address_map {
  static constexpr const char * name_str = nullptr;
};

template<> struct address_map< 0x40000004 > { static constexpr const char * name_str = "FLASH_IF::FRWTR"; };
template<> struct address_map< 0x40000008 > { static constexpr const char * name_str = "FLASH_IF::FSTR"; };
template<> struct address_map< 0x40000020 > { static constexpr const char * name_str = "FLASH_IF::FICR"; };
template<> struct address_map< 0x40000024 > { static constexpr const char * name_str = "FLASH_IF::FISR"; };
template<> struct address_map< 0x40000028 > { static constexpr const char * name_str = "FLASH_IF::FICLR"; };
template<> struct address_map< 0x40000100 > { static constexpr const char * name_str = "FLASH_IF::CRTRMM"; };
template<> struct address_map< 0x40010000 > { static constexpr const char * name_str = "CRG::SCM_CTL"; };
template<> struct address_map< 0x40010004 > { static constexpr const char * name_str = "CRG::SCM_STR"; };
template<> struct address_map< 0x40010008 > { static constexpr const char * name_str = "CRG::STB_CTL"; };
template<> struct address_map< 0x4001000c > { static constexpr const char * name_str = "CRG::RST_STR"; };
template<> struct address_map< 0x40010010 > { static constexpr const char * name_str = "CRG::BSC_PSR"; };
template<> struct address_map< 0x40010014 > { static constexpr const char * name_str = "CRG::APBC0_PSR"; };
template<> struct address_map< 0x40010018 > { static constexpr const char * name_str = "CRG::APBC1_PSR"; };
template<> struct address_map< 0x4001001c > { static constexpr const char * name_str = "CRG::APBC2_PSR"; };
template<> struct address_map< 0x40010020 > { static constexpr const char * name_str = "CRG::SWC_PSR"; };
template<> struct address_map< 0x40010028 > { static constexpr const char * name_str = "CRG::TTC_PSR"; };
template<> struct address_map< 0x40010030 > { static constexpr const char * name_str = "CRG::CSW_TMR"; };
template<> struct address_map< 0x40010034 > { static constexpr const char * name_str = "CRG::PSW_TMR"; };
template<> struct address_map< 0x40010038 > { static constexpr const char * name_str = "CRG::PLL_CTL1"; };
template<> struct address_map< 0x4001003c > { static constexpr const char * name_str = "CRG::PLL_CTL2"; };
template<> struct address_map< 0x40010040 > { static constexpr const char * name_str = "CRG::CSV_CTL"; };
template<> struct address_map< 0x40010044 > { static constexpr const char * name_str = "CRG::CSV_STR"; };
template<> struct address_map< 0x40010048 > { static constexpr const char * name_str = "CRG::FCSWH_CTL"; };
template<> struct address_map< 0x4001004c > { static constexpr const char * name_str = "CRG::FCSWL_CTL"; };
template<> struct address_map< 0x40010050 > { static constexpr const char * name_str = "CRG::FCSWD_CTL"; };
template<> struct address_map< 0x40010054 > { static constexpr const char * name_str = "CRG::DBWDT_CTL"; };
template<> struct address_map< 0x40010060 > { static constexpr const char * name_str = "CRG::INT_ENR"; };
template<> struct address_map< 0x40010064 > { static constexpr const char * name_str = "CRG::INT_STR"; };
template<> struct address_map< 0x40010068 > { static constexpr const char * name_str = "CRG::INT_CLR"; };
template<> struct address_map< 0x40011000 > { static constexpr const char * name_str = "HWWDT::WDG_LDR"; };
template<> struct address_map< 0x40011004 > { static constexpr const char * name_str = "HWWDT::WDG_VLR"; };
template<> struct address_map< 0x40011008 > { static constexpr const char * name_str = "HWWDT::WDG_CTL"; };
template<> struct address_map< 0x4001100c > { static constexpr const char * name_str = "HWWDT::WDG_ICL"; };
template<> struct address_map< 0x40011010 > { static constexpr const char * name_str = "HWWDT::WDG_RIS"; };
template<> struct address_map< 0x40011c00 > { static constexpr const char * name_str = "HWWDT::WDG_LCK"; };
template<> struct address_map< 0x40012000 > { static constexpr const char * name_str = "SWWDT::WDOGLOAD"; };
template<> struct address_map< 0x40012004 > { static constexpr const char * name_str = "SWWDT::WDOGVALUE"; };
template<> struct address_map< 0x40012008 > { static constexpr const char * name_str = "SWWDT::WDOGCONTROL"; };
template<> struct address_map< 0x4001200c > { static constexpr const char * name_str = "SWWDT::WDOGINTCLR"; };
template<> struct address_map< 0x40012010 > { static constexpr const char * name_str = "SWWDT::WDOGRIS"; };
template<> struct address_map< 0x40012c00 > { static constexpr const char * name_str = "SWWDT::WDOGLOCK"; };
template<> struct address_map< 0x40015000 > { static constexpr const char * name_str = "DTIM::TIMER1LOAD"; };
template<> struct address_map< 0x40015004 > { static constexpr const char * name_str = "DTIM::TIMER1VALUE"; };
template<> struct address_map< 0x40015008 > { static constexpr const char * name_str = "DTIM::TIMER1CONTROL"; };
template<> struct address_map< 0x4001500c > { static constexpr const char * name_str = "DTIM::TIMER1INTCLR"; };
template<> struct address_map< 0x40015010 > { static constexpr const char * name_str = "DTIM::TIMER1RIS"; };
template<> struct address_map< 0x40015014 > { static constexpr const char * name_str = "DTIM::TIMER1MIS"; };
template<> struct address_map< 0x40015018 > { static constexpr const char * name_str = "DTIM::TIMER1BGLOAD"; };
template<> struct address_map< 0x40015020 > { static constexpr const char * name_str = "DTIM::TIMER2LOAD"; };
template<> struct address_map< 0x40015024 > { static constexpr const char * name_str = "DTIM::TIMER2VALUE"; };
template<> struct address_map< 0x40015028 > { static constexpr const char * name_str = "DTIM::TIMER2CONTROL"; };
template<> struct address_map< 0x4001502c > { static constexpr const char * name_str = "DTIM::TIMER2INTCLR"; };
template<> struct address_map< 0x40015030 > { static constexpr const char * name_str = "DTIM::TIMER2RIS"; };
template<> struct address_map< 0x40015034 > { static constexpr const char * name_str = "DTIM::TIMER2MIS"; };
template<> struct address_map< 0x40015038 > { static constexpr const char * name_str = "DTIM::TIMER2BGLOAD"; };
template<> struct address_map< 0x40025000 > { static constexpr const char * name_str = "BT0::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLL, BT0::PWM_PCSR, BT0::RT_PCSR */
template<> struct address_map< 0x40025004 > { static constexpr const char * name_str = "BT0::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLH, BT0::PWC_DTBF, BT0::PWM_PDUT */
template<> struct address_map< 0x40025008 > { static constexpr const char * name_str = "BT0::RT_TMR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMR, BT0::PWM_TMR, BT0::RT_TMR */
template<> struct address_map< 0x4002500c > { static constexpr const char * name_str = "BT0::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR, BT0::PWC_TMCR, BT0::PWM_TMCR, BT0::RT_TMCR */
template<> struct address_map< 0x40025010 > { static constexpr const char * name_str = "BT0::RT_STC"; };  /* svd2hpp: duplicate address for: BT0::PPG_STC, BT0::PWC_STC, BT0::PWM_STC, BT0::RT_STC */
template<> struct address_map< 0x40025011 > { static constexpr const char * name_str = "BT0::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR2, BT0::PWC_TMCR2, BT0::PWM_TMCR2, BT0::RT_TMCR2 */
template<> struct address_map< 0x40025040 > { static constexpr const char * name_str = "BT1::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLL, BT1::PWM_PCSR, BT1::RT_PCSR */
template<> struct address_map< 0x40025044 > { static constexpr const char * name_str = "BT1::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLH, BT1::PWC_DTBF, BT1::PWM_PDUT */
template<> struct address_map< 0x40025048 > { static constexpr const char * name_str = "BT1::RT_TMR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMR, BT1::PWM_TMR, BT1::RT_TMR */
template<> struct address_map< 0x4002504c > { static constexpr const char * name_str = "BT1::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR, BT1::PWC_TMCR, BT1::PWM_TMCR, BT1::RT_TMCR */
template<> struct address_map< 0x40025050 > { static constexpr const char * name_str = "BT1::RT_STC"; };  /* svd2hpp: duplicate address for: BT1::PPG_STC, BT1::PWC_STC, BT1::PWM_STC, BT1::RT_STC */
template<> struct address_map< 0x40025051 > { static constexpr const char * name_str = "BT1::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR2, BT1::PWC_TMCR2, BT1::PWM_TMCR2, BT1::RT_TMCR2 */
template<> struct address_map< 0x40025080 > { static constexpr const char * name_str = "BT2::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLL, BT2::PWM_PCSR, BT2::RT_PCSR */
template<> struct address_map< 0x40025084 > { static constexpr const char * name_str = "BT2::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLH, BT2::PWC_DTBF, BT2::PWM_PDUT */
template<> struct address_map< 0x40025088 > { static constexpr const char * name_str = "BT2::RT_TMR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMR, BT2::PWM_TMR, BT2::RT_TMR */
template<> struct address_map< 0x4002508c > { static constexpr const char * name_str = "BT2::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR, BT2::PWC_TMCR, BT2::PWM_TMCR, BT2::RT_TMCR */
template<> struct address_map< 0x40025090 > { static constexpr const char * name_str = "BT2::RT_STC"; };  /* svd2hpp: duplicate address for: BT2::PPG_STC, BT2::PWC_STC, BT2::PWM_STC, BT2::RT_STC */
template<> struct address_map< 0x40025091 > { static constexpr const char * name_str = "BT2::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR2, BT2::PWC_TMCR2, BT2::PWM_TMCR2, BT2::RT_TMCR2 */
template<> struct address_map< 0x400250c0 > { static constexpr const char * name_str = "BT3::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLL, BT3::PWM_PCSR, BT3::RT_PCSR */
template<> struct address_map< 0x400250c4 > { static constexpr const char * name_str = "BT3::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLH, BT3::PWC_DTBF, BT3::PWM_PDUT */
template<> struct address_map< 0x400250c8 > { static constexpr const char * name_str = "BT3::RT_TMR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMR, BT3::PWM_TMR, BT3::RT_TMR */
template<> struct address_map< 0x400250cc > { static constexpr const char * name_str = "BT3::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR, BT3::PWC_TMCR, BT3::PWM_TMCR, BT3::RT_TMCR */
template<> struct address_map< 0x400250d0 > { static constexpr const char * name_str = "BT3::RT_STC"; };  /* svd2hpp: duplicate address for: BT3::PPG_STC, BT3::PWC_STC, BT3::PWM_STC, BT3::RT_STC */
template<> struct address_map< 0x400250d1 > { static constexpr const char * name_str = "BT3::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR2, BT3::PWC_TMCR2, BT3::PWM_TMCR2, BT3::RT_TMCR2 */
template<> struct address_map< 0x40025100 > { static constexpr const char * name_str = "BTIOSEL03::BTSEL0123"; };
template<> struct address_map< 0x40025200 > { static constexpr const char * name_str = "BT4::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT4::PPG_PRLL, BT4::PWM_PCSR, BT4::RT_PCSR */
template<> struct address_map< 0x40025204 > { static constexpr const char * name_str = "BT4::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT4::PPG_PRLH, BT4::PWC_DTBF, BT4::PWM_PDUT */
template<> struct address_map< 0x40025208 > { static constexpr const char * name_str = "BT4::RT_TMR"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMR, BT4::PWM_TMR, BT4::RT_TMR */
template<> struct address_map< 0x4002520c > { static constexpr const char * name_str = "BT4::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMCR, BT4::PWC_TMCR, BT4::PWM_TMCR, BT4::RT_TMCR */
template<> struct address_map< 0x40025210 > { static constexpr const char * name_str = "BT4::RT_STC"; };  /* svd2hpp: duplicate address for: BT4::PPG_STC, BT4::PWC_STC, BT4::PWM_STC, BT4::RT_STC */
template<> struct address_map< 0x40025211 > { static constexpr const char * name_str = "BT4::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT4::PPG_TMCR2, BT4::PWC_TMCR2, BT4::PWM_TMCR2, BT4::RT_TMCR2 */
template<> struct address_map< 0x40025240 > { static constexpr const char * name_str = "BT5::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT5::PPG_PRLL, BT5::PWM_PCSR, BT5::RT_PCSR */
template<> struct address_map< 0x40025244 > { static constexpr const char * name_str = "BT5::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT5::PPG_PRLH, BT5::PWC_DTBF, BT5::PWM_PDUT */
template<> struct address_map< 0x40025248 > { static constexpr const char * name_str = "BT5::RT_TMR"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMR, BT5::PWM_TMR, BT5::RT_TMR */
template<> struct address_map< 0x4002524c > { static constexpr const char * name_str = "BT5::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMCR, BT5::PWC_TMCR, BT5::PWM_TMCR, BT5::RT_TMCR */
template<> struct address_map< 0x40025250 > { static constexpr const char * name_str = "BT5::RT_STC"; };  /* svd2hpp: duplicate address for: BT5::PPG_STC, BT5::PWC_STC, BT5::PWM_STC, BT5::RT_STC */
template<> struct address_map< 0x40025251 > { static constexpr const char * name_str = "BT5::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT5::PPG_TMCR2, BT5::PWC_TMCR2, BT5::PWM_TMCR2, BT5::RT_TMCR2 */
template<> struct address_map< 0x40025280 > { static constexpr const char * name_str = "BT6::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT6::PPG_PRLL, BT6::PWM_PCSR, BT6::RT_PCSR */
template<> struct address_map< 0x40025284 > { static constexpr const char * name_str = "BT6::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT6::PPG_PRLH, BT6::PWC_DTBF, BT6::PWM_PDUT */
template<> struct address_map< 0x40025288 > { static constexpr const char * name_str = "BT6::RT_TMR"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMR, BT6::PWM_TMR, BT6::RT_TMR */
template<> struct address_map< 0x4002528c > { static constexpr const char * name_str = "BT6::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMCR, BT6::PWC_TMCR, BT6::PWM_TMCR, BT6::RT_TMCR */
template<> struct address_map< 0x40025290 > { static constexpr const char * name_str = "BT6::RT_STC"; };  /* svd2hpp: duplicate address for: BT6::PPG_STC, BT6::PWC_STC, BT6::PWM_STC, BT6::RT_STC */
template<> struct address_map< 0x40025291 > { static constexpr const char * name_str = "BT6::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT6::PPG_TMCR2, BT6::PWC_TMCR2, BT6::PWM_TMCR2, BT6::RT_TMCR2 */
template<> struct address_map< 0x400252c0 > { static constexpr const char * name_str = "BT7::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT7::PPG_PRLL, BT7::PWM_PCSR, BT7::RT_PCSR */
template<> struct address_map< 0x400252c4 > { static constexpr const char * name_str = "BT7::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT7::PPG_PRLH, BT7::PWC_DTBF, BT7::PWM_PDUT */
template<> struct address_map< 0x400252c8 > { static constexpr const char * name_str = "BT7::RT_TMR"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMR, BT7::PWM_TMR, BT7::RT_TMR */
template<> struct address_map< 0x400252cc > { static constexpr const char * name_str = "BT7::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMCR, BT7::PWC_TMCR, BT7::PWM_TMCR, BT7::RT_TMCR */
template<> struct address_map< 0x400252d0 > { static constexpr const char * name_str = "BT7::RT_STC"; };  /* svd2hpp: duplicate address for: BT7::PPG_STC, BT7::PWC_STC, BT7::PWM_STC, BT7::RT_STC */
template<> struct address_map< 0x400252d1 > { static constexpr const char * name_str = "BT7::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT7::PPG_TMCR2, BT7::PWC_TMCR2, BT7::PWM_TMCR2, BT7::RT_TMCR2 */
template<> struct address_map< 0x40025300 > { static constexpr const char * name_str = "BTIOSEL47::BTSEL4567"; };
template<> struct address_map< 0x40025ffc > { static constexpr const char * name_str = "SBSSR::BTSSSR"; };
template<> struct address_map< 0x40027000 > { static constexpr const char * name_str = "ADC0::ADSR"; };
template<> struct address_map< 0x40027001 > { static constexpr const char * name_str = "ADC0::ADCR"; };
template<> struct address_map< 0x40027008 > { static constexpr const char * name_str = "ADC0::SFNS"; };
template<> struct address_map< 0x40027009 > { static constexpr const char * name_str = "ADC0::SCCR"; };
template<> struct address_map< 0x4002700c > { static constexpr const char * name_str = "ADC0::SCFD"; };
template<> struct address_map< 0x40027010 > { static constexpr const char * name_str = "ADC0::SCIS2"; };
template<> struct address_map< 0x40027011 > { static constexpr const char * name_str = "ADC0::SCIS3"; };
template<> struct address_map< 0x40027014 > { static constexpr const char * name_str = "ADC0::SCIS0"; };
template<> struct address_map< 0x40027015 > { static constexpr const char * name_str = "ADC0::SCIS1"; };
template<> struct address_map< 0x40027018 > { static constexpr const char * name_str = "ADC0::PFNS"; };
template<> struct address_map< 0x40027019 > { static constexpr const char * name_str = "ADC0::PCCR"; };
template<> struct address_map< 0x4002701c > { static constexpr const char * name_str = "ADC0::PCFD"; };
template<> struct address_map< 0x40027020 > { static constexpr const char * name_str = "ADC0::PCIS"; };
template<> struct address_map< 0x40027024 > { static constexpr const char * name_str = "ADC0::CMPCR"; };
template<> struct address_map< 0x40027026 > { static constexpr const char * name_str = "ADC0::CMPD"; };
template<> struct address_map< 0x40027028 > { static constexpr const char * name_str = "ADC0::ADSS2"; };
template<> struct address_map< 0x40027029 > { static constexpr const char * name_str = "ADC0::ADSS3"; };
template<> struct address_map< 0x4002702c > { static constexpr const char * name_str = "ADC0::ADSS0"; };
template<> struct address_map< 0x4002702d > { static constexpr const char * name_str = "ADC0::ADSS1"; };
template<> struct address_map< 0x40027030 > { static constexpr const char * name_str = "ADC0::ADST1"; };
template<> struct address_map< 0x40027031 > { static constexpr const char * name_str = "ADC0::ADST0"; };
template<> struct address_map< 0x40027034 > { static constexpr const char * name_str = "ADC0::ADCT"; };
template<> struct address_map< 0x40027038 > { static constexpr const char * name_str = "ADC0::PRTSL"; };
template<> struct address_map< 0x40027039 > { static constexpr const char * name_str = "ADC0::SCTSL"; };
template<> struct address_map< 0x4002703c > { static constexpr const char * name_str = "ADC0::ADCEN"; };
template<> struct address_map< 0x40027100 > { static constexpr const char * name_str = "ADC1::ADSR"; };
template<> struct address_map< 0x40027101 > { static constexpr const char * name_str = "ADC1::ADCR"; };
template<> struct address_map< 0x40027108 > { static constexpr const char * name_str = "ADC1::SFNS"; };
template<> struct address_map< 0x40027109 > { static constexpr const char * name_str = "ADC1::SCCR"; };
template<> struct address_map< 0x4002710c > { static constexpr const char * name_str = "ADC1::SCFD"; };
template<> struct address_map< 0x40027110 > { static constexpr const char * name_str = "ADC1::SCIS2"; };
template<> struct address_map< 0x40027111 > { static constexpr const char * name_str = "ADC1::SCIS3"; };
template<> struct address_map< 0x40027114 > { static constexpr const char * name_str = "ADC1::SCIS0"; };
template<> struct address_map< 0x40027115 > { static constexpr const char * name_str = "ADC1::SCIS1"; };
template<> struct address_map< 0x40027118 > { static constexpr const char * name_str = "ADC1::PFNS"; };
template<> struct address_map< 0x40027119 > { static constexpr const char * name_str = "ADC1::PCCR"; };
template<> struct address_map< 0x4002711c > { static constexpr const char * name_str = "ADC1::PCFD"; };
template<> struct address_map< 0x40027120 > { static constexpr const char * name_str = "ADC1::PCIS"; };
template<> struct address_map< 0x40027124 > { static constexpr const char * name_str = "ADC1::CMPCR"; };
template<> struct address_map< 0x40027126 > { static constexpr const char * name_str = "ADC1::CMPD"; };
template<> struct address_map< 0x40027128 > { static constexpr const char * name_str = "ADC1::ADSS2"; };
template<> struct address_map< 0x40027129 > { static constexpr const char * name_str = "ADC1::ADSS3"; };
template<> struct address_map< 0x4002712c > { static constexpr const char * name_str = "ADC1::ADSS0"; };
template<> struct address_map< 0x4002712d > { static constexpr const char * name_str = "ADC1::ADSS1"; };
template<> struct address_map< 0x40027130 > { static constexpr const char * name_str = "ADC1::ADST1"; };
template<> struct address_map< 0x40027131 > { static constexpr const char * name_str = "ADC1::ADST0"; };
template<> struct address_map< 0x40027134 > { static constexpr const char * name_str = "ADC1::ADCT"; };
template<> struct address_map< 0x40027138 > { static constexpr const char * name_str = "ADC1::PRTSL"; };
template<> struct address_map< 0x40027139 > { static constexpr const char * name_str = "ADC1::SCTSL"; };
template<> struct address_map< 0x4002713c > { static constexpr const char * name_str = "ADC1::ADCEN"; };
template<> struct address_map< 0x4002e000 > { static constexpr const char * name_str = "CRTRIM::MCR_PSR"; };
template<> struct address_map< 0x4002e004 > { static constexpr const char * name_str = "CRTRIM::MCR_FTRM"; };
template<> struct address_map< 0x4002e00c > { static constexpr const char * name_str = "CRTRIM::MCR_RLR"; };
template<> struct address_map< 0x40030000 > { static constexpr const char * name_str = "EXTI::ENIR"; };
template<> struct address_map< 0x40030004 > { static constexpr const char * name_str = "EXTI::EIRR"; };
template<> struct address_map< 0x40030008 > { static constexpr const char * name_str = "EXTI::EICL"; };
template<> struct address_map< 0x4003000c > { static constexpr const char * name_str = "EXTI::ELVR"; };
template<> struct address_map< 0x40030014 > { static constexpr const char * name_str = "EXTI::NMIRR"; };
template<> struct address_map< 0x40030018 > { static constexpr const char * name_str = "EXTI::NMICL"; };
template<> struct address_map< 0x40031000 > { static constexpr const char * name_str = "INTREQ::DRQSEL"; };
template<> struct address_map< 0x4003100b > { static constexpr const char * name_str = "INTREQ::ODDPKS"; };
template<> struct address_map< 0x4003100c > { static constexpr const char * name_str = "INTREQ::IRQCMODE"; };
template<> struct address_map< 0x40031010 > { static constexpr const char * name_str = "INTREQ::EXC02MON"; };
template<> struct address_map< 0x40031014 > { static constexpr const char * name_str = "INTREQ::IRQ00MON"; };
template<> struct address_map< 0x40031018 > { static constexpr const char * name_str = "INTREQ::IRQ01MON"; };
template<> struct address_map< 0x4003101c > { static constexpr const char * name_str = "INTREQ::IRQ02MON"; };
template<> struct address_map< 0x40031024 > { static constexpr const char * name_str = "INTREQ::IRQ04MON"; };
template<> struct address_map< 0x40031028 > { static constexpr const char * name_str = "INTREQ::IRQ05MON"; };
template<> struct address_map< 0x4003102c > { static constexpr const char * name_str = "INTREQ::IRQ06MON"; };
template<> struct address_map< 0x40031030 > { static constexpr const char * name_str = "INTREQ::IRQ07MON"; };
template<> struct address_map< 0x40031034 > { static constexpr const char * name_str = "INTREQ::IRQ08MON"; };
template<> struct address_map< 0x40031038 > { static constexpr const char * name_str = "INTREQ::IRQ09MON"; };
template<> struct address_map< 0x4003103c > { static constexpr const char * name_str = "INTREQ::IRQ10MON"; };
template<> struct address_map< 0x40031040 > { static constexpr const char * name_str = "INTREQ::IRQ11MON"; };
template<> struct address_map< 0x40031044 > { static constexpr const char * name_str = "INTREQ::IRQ12MON"; };
template<> struct address_map< 0x40031048 > { static constexpr const char * name_str = "INTREQ::IRQ13MON"; };
template<> struct address_map< 0x4003104c > { static constexpr const char * name_str = "INTREQ::IRQ14MON"; };
template<> struct address_map< 0x40031050 > { static constexpr const char * name_str = "INTREQ::IRQ15MON"; };
template<> struct address_map< 0x40031054 > { static constexpr const char * name_str = "INTREQ::IRQ16MON"; };
template<> struct address_map< 0x40031058 > { static constexpr const char * name_str = "INTREQ::IRQ17MON"; };
template<> struct address_map< 0x4003105c > { static constexpr const char * name_str = "INTREQ::IRQ18MON"; };
template<> struct address_map< 0x40031060 > { static constexpr const char * name_str = "INTREQ::IRQ19MON"; };
template<> struct address_map< 0x40031064 > { static constexpr const char * name_str = "INTREQ::IRQ20MON"; };
template<> struct address_map< 0x40031068 > { static constexpr const char * name_str = "INTREQ::IRQ21MON"; };
template<> struct address_map< 0x4003106c > { static constexpr const char * name_str = "INTREQ::IRQ22MON"; };
template<> struct address_map< 0x40031074 > { static constexpr const char * name_str = "INTREQ::IRQ24MON"; };
template<> struct address_map< 0x40031078 > { static constexpr const char * name_str = "INTREQ::IRQ25MON"; };
template<> struct address_map< 0x4003107c > { static constexpr const char * name_str = "INTREQ::IRQ26MON"; };
template<> struct address_map< 0x40031080 > { static constexpr const char * name_str = "INTREQ::IRQ27MON"; };
template<> struct address_map< 0x40031090 > { static constexpr const char * name_str = "INTREQ::IRQ31MON"; };
template<> struct address_map< 0x4003109c > { static constexpr const char * name_str = "INTREQ::IRQ34MON"; };
template<> struct address_map< 0x400310a0 > { static constexpr const char * name_str = "INTREQ::IRQ35MON"; };
template<> struct address_map< 0x400310a4 > { static constexpr const char * name_str = "INTREQ::IRQ36MON"; };
template<> struct address_map< 0x400310a8 > { static constexpr const char * name_str = "INTREQ::IRQ37MON"; };
template<> struct address_map< 0x400310ac > { static constexpr const char * name_str = "INTREQ::IRQ38MON"; };
template<> struct address_map< 0x400310b0 > { static constexpr const char * name_str = "INTREQ::IRQ39MON"; };
template<> struct address_map< 0x400310b4 > { static constexpr const char * name_str = "INTREQ::IRQ40MON"; };
template<> struct address_map< 0x400310b8 > { static constexpr const char * name_str = "INTREQ::IRQ41MON"; };
template<> struct address_map< 0x400310bc > { static constexpr const char * name_str = "INTREQ::IRQ42MON"; };
template<> struct address_map< 0x400310c0 > { static constexpr const char * name_str = "INTREQ::IRQ43MON"; };
template<> struct address_map< 0x400310c4 > { static constexpr const char * name_str = "INTREQ::IRQ44MON"; };
template<> struct address_map< 0x400310c8 > { static constexpr const char * name_str = "INTREQ::IRQ45MON"; };
template<> struct address_map< 0x400310d0 > { static constexpr const char * name_str = "INTREQ::IRQ47MON"; };
template<> struct address_map< 0x40031210 > { static constexpr const char * name_str = "INTREQ::RCINTSEL0"; };
template<> struct address_map< 0x40031214 > { static constexpr const char * name_str = "INTREQ::RCINTSEL1"; };
template<> struct address_map< 0x40032000 > { static constexpr const char * name_str = "LCDC::LCDCC1"; };
template<> struct address_map< 0x40032001 > { static constexpr const char * name_str = "LCDC::LCDCC2"; };
template<> struct address_map< 0x40032002 > { static constexpr const char * name_str = "LCDC::LCDCC3"; };
template<> struct address_map< 0x40032004 > { static constexpr const char * name_str = "LCDC::LCDC_PSR"; };
template<> struct address_map< 0x40032008 > { static constexpr const char * name_str = "LCDC::LCDC_COMEN"; };
template<> struct address_map< 0x4003200c > { static constexpr const char * name_str = "LCDC::LCDC_SEGEN1"; };
template<> struct address_map< 0x40032010 > { static constexpr const char * name_str = "LCDC::LCDC_SEGEN2"; };
template<> struct address_map< 0x40032014 > { static constexpr const char * name_str = "LCDC::LCDC_BLINK"; };
template<> struct address_map< 0x4003201c > { static constexpr const char * name_str = "LCDC::LCDRAM00"; };
template<> struct address_map< 0x4003201d > { static constexpr const char * name_str = "LCDC::LCDRAM01"; };
template<> struct address_map< 0x4003201e > { static constexpr const char * name_str = "LCDC::LCDRAM02"; };
template<> struct address_map< 0x4003201f > { static constexpr const char * name_str = "LCDC::LCDRAM03"; };
template<> struct address_map< 0x40032020 > { static constexpr const char * name_str = "LCDC::LCDRAM04"; };
template<> struct address_map< 0x40032021 > { static constexpr const char * name_str = "LCDC::LCDRAM05"; };
template<> struct address_map< 0x40032022 > { static constexpr const char * name_str = "LCDC::LCDRAM06"; };
template<> struct address_map< 0x40032023 > { static constexpr const char * name_str = "LCDC::LCDRAM07"; };
template<> struct address_map< 0x40032024 > { static constexpr const char * name_str = "LCDC::LCDRAM08"; };
template<> struct address_map< 0x40032025 > { static constexpr const char * name_str = "LCDC::LCDRAM09"; };
template<> struct address_map< 0x40032026 > { static constexpr const char * name_str = "LCDC::LCDRAM10"; };
template<> struct address_map< 0x40032027 > { static constexpr const char * name_str = "LCDC::LCDRAM11"; };
template<> struct address_map< 0x40032028 > { static constexpr const char * name_str = "LCDC::LCDRAM12"; };
template<> struct address_map< 0x40032029 > { static constexpr const char * name_str = "LCDC::LCDRAM13"; };
template<> struct address_map< 0x4003202a > { static constexpr const char * name_str = "LCDC::LCDRAM14"; };
template<> struct address_map< 0x4003202b > { static constexpr const char * name_str = "LCDC::LCDRAM15"; };
template<> struct address_map< 0x4003202c > { static constexpr const char * name_str = "LCDC::LCDRAM16"; };
template<> struct address_map< 0x4003202d > { static constexpr const char * name_str = "LCDC::LCDRAM17"; };
template<> struct address_map< 0x4003202e > { static constexpr const char * name_str = "LCDC::LCDRAM18"; };
template<> struct address_map< 0x4003202f > { static constexpr const char * name_str = "LCDC::LCDRAM19"; };
template<> struct address_map< 0x40032030 > { static constexpr const char * name_str = "LCDC::LCDRAM20"; };
template<> struct address_map< 0x40032031 > { static constexpr const char * name_str = "LCDC::LCDRAM21"; };
template<> struct address_map< 0x40032032 > { static constexpr const char * name_str = "LCDC::LCDRAM22"; };
template<> struct address_map< 0x40032033 > { static constexpr const char * name_str = "LCDC::LCDRAM23"; };
template<> struct address_map< 0x40032034 > { static constexpr const char * name_str = "LCDC::LCDRAM24"; };
template<> struct address_map< 0x40032035 > { static constexpr const char * name_str = "LCDC::LCDRAM25"; };
template<> struct address_map< 0x40032036 > { static constexpr const char * name_str = "LCDC::LCDRAM26"; };
template<> struct address_map< 0x40032037 > { static constexpr const char * name_str = "LCDC::LCDRAM27"; };
template<> struct address_map< 0x40032038 > { static constexpr const char * name_str = "LCDC::LCDRAM28"; };
template<> struct address_map< 0x40032039 > { static constexpr const char * name_str = "LCDC::LCDRAM29"; };
template<> struct address_map< 0x4003203a > { static constexpr const char * name_str = "LCDC::LCDRAM30"; };
template<> struct address_map< 0x4003203b > { static constexpr const char * name_str = "LCDC::LCDRAM31"; };
template<> struct address_map< 0x4003203c > { static constexpr const char * name_str = "LCDC::LCDRAM32"; };
template<> struct address_map< 0x4003203d > { static constexpr const char * name_str = "LCDC::LCDRAM33"; };
template<> struct address_map< 0x4003203e > { static constexpr const char * name_str = "LCDC::LCDRAM34"; };
template<> struct address_map< 0x4003203f > { static constexpr const char * name_str = "LCDC::LCDRAM35"; };
template<> struct address_map< 0x40032040 > { static constexpr const char * name_str = "LCDC::LCDRAM36"; };
template<> struct address_map< 0x40032041 > { static constexpr const char * name_str = "LCDC::LCDRAM37"; };
template<> struct address_map< 0x40032042 > { static constexpr const char * name_str = "LCDC::LCDRAM38"; };
template<> struct address_map< 0x40032043 > { static constexpr const char * name_str = "LCDC::LCDRAM39"; };
template<> struct address_map< 0x40033000 > { static constexpr const char * name_str = "GPIO::PFR0"; };
template<> struct address_map< 0x40033004 > { static constexpr const char * name_str = "GPIO::PFR1"; };
template<> struct address_map< 0x40033008 > { static constexpr const char * name_str = "GPIO::PFR2"; };
template<> struct address_map< 0x4003300c > { static constexpr const char * name_str = "GPIO::PFR3"; };
template<> struct address_map< 0x40033010 > { static constexpr const char * name_str = "GPIO::PFR4"; };
template<> struct address_map< 0x40033014 > { static constexpr const char * name_str = "GPIO::PFR5"; };
template<> struct address_map< 0x40033018 > { static constexpr const char * name_str = "GPIO::PFR6"; };
template<> struct address_map< 0x40033020 > { static constexpr const char * name_str = "GPIO::PFR8"; };
template<> struct address_map< 0x40033038 > { static constexpr const char * name_str = "GPIO::PFRE"; };
template<> struct address_map< 0x40033100 > { static constexpr const char * name_str = "GPIO::PCR0"; };
template<> struct address_map< 0x40033104 > { static constexpr const char * name_str = "GPIO::PCR1"; };
template<> struct address_map< 0x40033108 > { static constexpr const char * name_str = "GPIO::PCR2"; };
template<> struct address_map< 0x4003310c > { static constexpr const char * name_str = "GPIO::PCR3"; };
template<> struct address_map< 0x40033110 > { static constexpr const char * name_str = "GPIO::PCR4"; };
template<> struct address_map< 0x40033114 > { static constexpr const char * name_str = "GPIO::PCR5"; };
template<> struct address_map< 0x40033118 > { static constexpr const char * name_str = "GPIO::PCR6"; };
template<> struct address_map< 0x40033138 > { static constexpr const char * name_str = "GPIO::PCRE"; };
template<> struct address_map< 0x40033200 > { static constexpr const char * name_str = "GPIO::DDR0"; };
template<> struct address_map< 0x40033204 > { static constexpr const char * name_str = "GPIO::DDR1"; };
template<> struct address_map< 0x40033208 > { static constexpr const char * name_str = "GPIO::DDR2"; };
template<> struct address_map< 0x4003320c > { static constexpr const char * name_str = "GPIO::DDR3"; };
template<> struct address_map< 0x40033210 > { static constexpr const char * name_str = "GPIO::DDR4"; };
template<> struct address_map< 0x40033214 > { static constexpr const char * name_str = "GPIO::DDR5"; };
template<> struct address_map< 0x40033218 > { static constexpr const char * name_str = "GPIO::DDR6"; };
template<> struct address_map< 0x40033220 > { static constexpr const char * name_str = "GPIO::DDR8"; };
template<> struct address_map< 0x40033238 > { static constexpr const char * name_str = "GPIO::DDRE"; };
template<> struct address_map< 0x40033300 > { static constexpr const char * name_str = "GPIO::PDIR0"; };
template<> struct address_map< 0x40033304 > { static constexpr const char * name_str = "GPIO::PDIR1"; };
template<> struct address_map< 0x40033308 > { static constexpr const char * name_str = "GPIO::PDIR2"; };
template<> struct address_map< 0x4003330c > { static constexpr const char * name_str = "GPIO::PDIR3"; };
template<> struct address_map< 0x40033310 > { static constexpr const char * name_str = "GPIO::PDIR4"; };
template<> struct address_map< 0x40033314 > { static constexpr const char * name_str = "GPIO::PDIR5"; };
template<> struct address_map< 0x40033318 > { static constexpr const char * name_str = "GPIO::PDIR6"; };
template<> struct address_map< 0x40033320 > { static constexpr const char * name_str = "GPIO::PDIR8"; };
template<> struct address_map< 0x40033338 > { static constexpr const char * name_str = "GPIO::PDIRE"; };
template<> struct address_map< 0x40033400 > { static constexpr const char * name_str = "GPIO::PDOR0"; };
template<> struct address_map< 0x40033404 > { static constexpr const char * name_str = "GPIO::PDOR1"; };
template<> struct address_map< 0x40033408 > { static constexpr const char * name_str = "GPIO::PDOR2"; };
template<> struct address_map< 0x4003340c > { static constexpr const char * name_str = "GPIO::PDOR3"; };
template<> struct address_map< 0x40033410 > { static constexpr const char * name_str = "GPIO::PDOR4"; };
template<> struct address_map< 0x40033414 > { static constexpr const char * name_str = "GPIO::PDOR5"; };
template<> struct address_map< 0x40033418 > { static constexpr const char * name_str = "GPIO::PDOR6"; };
template<> struct address_map< 0x40033420 > { static constexpr const char * name_str = "GPIO::PDOR8"; };
template<> struct address_map< 0x40033438 > { static constexpr const char * name_str = "GPIO::PDORE"; };
template<> struct address_map< 0x40033500 > { static constexpr const char * name_str = "GPIO::ADE"; };
template<> struct address_map< 0x40033580 > { static constexpr const char * name_str = "GPIO::SPSR"; };
template<> struct address_map< 0x40033600 > { static constexpr const char * name_str = "GPIO::EPFR00"; };
template<> struct address_map< 0x40033610 > { static constexpr const char * name_str = "GPIO::EPFR04"; };
template<> struct address_map< 0x40033614 > { static constexpr const char * name_str = "GPIO::EPFR05"; };
template<> struct address_map< 0x40033618 > { static constexpr const char * name_str = "GPIO::EPFR06"; };
template<> struct address_map< 0x4003361c > { static constexpr const char * name_str = "GPIO::EPFR07"; };
template<> struct address_map< 0x40033620 > { static constexpr const char * name_str = "GPIO::EPFR08"; };
template<> struct address_map< 0x40033624 > { static constexpr const char * name_str = "GPIO::EPFR09"; };
template<> struct address_map< 0x40033628 > { static constexpr const char * name_str = "GPIO::EPFR10"; };
template<> struct address_map< 0x4003362c > { static constexpr const char * name_str = "GPIO::EPFR11"; };
template<> struct address_map< 0x40033638 > { static constexpr const char * name_str = "GPIO::EPFR14"; };
template<> struct address_map< 0x40033700 > { static constexpr const char * name_str = "GPIO::PZR0"; };
template<> struct address_map< 0x40033710 > { static constexpr const char * name_str = "GPIO::PZR4"; };
template<> struct address_map< 0x40033718 > { static constexpr const char * name_str = "GPIO::PZR6"; };
template<> struct address_map< 0x40034000 > { static constexpr const char * name_str = "HDMICEC0::TXCTRL"; };
template<> struct address_map< 0x40034004 > { static constexpr const char * name_str = "HDMICEC0::TXDATA"; };
template<> struct address_map< 0x40034008 > { static constexpr const char * name_str = "HDMICEC0::TXSTS"; };
template<> struct address_map< 0x4003400c > { static constexpr const char * name_str = "HDMICEC0::SFREE"; };
template<> struct address_map< 0x40034040 > { static constexpr const char * name_str = "HDMICEC0::RCST"; };
template<> struct address_map< 0x40034041 > { static constexpr const char * name_str = "HDMICEC0::RCCR"; };
template<> struct address_map< 0x40034044 > { static constexpr const char * name_str = "HDMICEC0::RCDAHW"; };
template<> struct address_map< 0x40034045 > { static constexpr const char * name_str = "HDMICEC0::RCSHW"; };
template<> struct address_map< 0x40034049 > { static constexpr const char * name_str = "HDMICEC0::RCDBHW"; };
template<> struct address_map< 0x4003404c > { static constexpr const char * name_str = "HDMICEC0::RCADR2"; };
template<> struct address_map< 0x4003404d > { static constexpr const char * name_str = "HDMICEC0::RCADR1"; };
template<> struct address_map< 0x40034050 > { static constexpr const char * name_str = "HDMICEC0::RCDTHL"; };
template<> struct address_map< 0x40034051 > { static constexpr const char * name_str = "HDMICEC0::RCDTHH"; };
template<> struct address_map< 0x40034054 > { static constexpr const char * name_str = "HDMICEC0::RCDTLL"; };
template<> struct address_map< 0x40034055 > { static constexpr const char * name_str = "HDMICEC0::RCDTLH"; };
template<> struct address_map< 0x40034058 > { static constexpr const char * name_str = "HDMICEC0::RCCKD"; };
template<> struct address_map< 0x4003405c > { static constexpr const char * name_str = "HDMICEC0::RCRHW"; };
template<> struct address_map< 0x4003405d > { static constexpr const char * name_str = "HDMICEC0::RCRC"; };
template<> struct address_map< 0x40034061 > { static constexpr const char * name_str = "HDMICEC0::RCLE"; };
template<> struct address_map< 0x40034064 > { static constexpr const char * name_str = "HDMICEC0::RCLESW"; };
template<> struct address_map< 0x40034065 > { static constexpr const char * name_str = "HDMICEC0::RCLELW"; };
template<> struct address_map< 0x40034100 > { static constexpr const char * name_str = "HDMICEC1::TXCTRL"; };
template<> struct address_map< 0x40034104 > { static constexpr const char * name_str = "HDMICEC1::TXDATA"; };
template<> struct address_map< 0x40034108 > { static constexpr const char * name_str = "HDMICEC1::TXSTS"; };
template<> struct address_map< 0x4003410c > { static constexpr const char * name_str = "HDMICEC1::SFREE"; };
template<> struct address_map< 0x40034140 > { static constexpr const char * name_str = "HDMICEC1::RCST"; };
template<> struct address_map< 0x40034141 > { static constexpr const char * name_str = "HDMICEC1::RCCR"; };
template<> struct address_map< 0x40034144 > { static constexpr const char * name_str = "HDMICEC1::RCDAHW"; };
template<> struct address_map< 0x40034145 > { static constexpr const char * name_str = "HDMICEC1::RCSHW"; };
template<> struct address_map< 0x40034149 > { static constexpr const char * name_str = "HDMICEC1::RCDBHW"; };
template<> struct address_map< 0x4003414c > { static constexpr const char * name_str = "HDMICEC1::RCADR2"; };
template<> struct address_map< 0x4003414d > { static constexpr const char * name_str = "HDMICEC1::RCADR1"; };
template<> struct address_map< 0x40034150 > { static constexpr const char * name_str = "HDMICEC1::RCDTHL"; };
template<> struct address_map< 0x40034151 > { static constexpr const char * name_str = "HDMICEC1::RCDTHH"; };
template<> struct address_map< 0x40034154 > { static constexpr const char * name_str = "HDMICEC1::RCDTLL"; };
template<> struct address_map< 0x40034155 > { static constexpr const char * name_str = "HDMICEC1::RCDTLH"; };
template<> struct address_map< 0x40034158 > { static constexpr const char * name_str = "HDMICEC1::RCCKD"; };
template<> struct address_map< 0x4003415c > { static constexpr const char * name_str = "HDMICEC1::RCRHW"; };
template<> struct address_map< 0x4003415d > { static constexpr const char * name_str = "HDMICEC1::RCRC"; };
template<> struct address_map< 0x40034161 > { static constexpr const char * name_str = "HDMICEC1::RCLE"; };
template<> struct address_map< 0x40034164 > { static constexpr const char * name_str = "HDMICEC1::RCLESW"; };
template<> struct address_map< 0x40034165 > { static constexpr const char * name_str = "HDMICEC1::RCLELW"; };
template<> struct address_map< 0x40035000 > { static constexpr const char * name_str = "LVD::LVD_CTL"; };
template<> struct address_map< 0x40035004 > { static constexpr const char * name_str = "LVD::LVD_STR"; };
template<> struct address_map< 0x40035008 > { static constexpr const char * name_str = "LVD::LVD_CLR"; };
template<> struct address_map< 0x4003500c > { static constexpr const char * name_str = "LVD::LVD_RLR"; };
template<> struct address_map< 0x40035010 > { static constexpr const char * name_str = "LVD::LVD_STR2"; };
template<> struct address_map< 0x40035100 > { static constexpr const char * name_str = "DS::REG_CTL"; };
template<> struct address_map< 0x40035104 > { static constexpr const char * name_str = "DS::RCK_CTL"; };
template<> struct address_map< 0x40035800 > { static constexpr const char * name_str = "DS::PMD_CTL"; };
template<> struct address_map< 0x40035804 > { static constexpr const char * name_str = "DS::WRFSR"; };
template<> struct address_map< 0x40035808 > { static constexpr const char * name_str = "DS::WIFSR"; };
template<> struct address_map< 0x4003580c > { static constexpr const char * name_str = "DS::WIER"; };
template<> struct address_map< 0x40035810 > { static constexpr const char * name_str = "DS::WILVR"; };
template<> struct address_map< 0x40035814 > { static constexpr const char * name_str = "DS::DSRAMR"; };
template<> struct address_map< 0x40035900 > { static constexpr const char * name_str = "DS::BUR01"; };
template<> struct address_map< 0x40035901 > { static constexpr const char * name_str = "DS::BUR02"; };
template<> struct address_map< 0x40035902 > { static constexpr const char * name_str = "DS::BUR03"; };
template<> struct address_map< 0x40035903 > { static constexpr const char * name_str = "DS::BUR04"; };
template<> struct address_map< 0x40035904 > { static constexpr const char * name_str = "DS::BUR05"; };
template<> struct address_map< 0x40035905 > { static constexpr const char * name_str = "DS::BUR06"; };
template<> struct address_map< 0x40035906 > { static constexpr const char * name_str = "DS::BUR07"; };
template<> struct address_map< 0x40035907 > { static constexpr const char * name_str = "DS::BUR08"; };
template<> struct address_map< 0x40035908 > { static constexpr const char * name_str = "DS::BUR09"; };
template<> struct address_map< 0x40035909 > { static constexpr const char * name_str = "DS::BUR10"; };
template<> struct address_map< 0x4003590a > { static constexpr const char * name_str = "DS::BUR11"; };
template<> struct address_map< 0x4003590b > { static constexpr const char * name_str = "DS::BUR12"; };
template<> struct address_map< 0x4003590c > { static constexpr const char * name_str = "DS::BUR13"; };
template<> struct address_map< 0x4003590d > { static constexpr const char * name_str = "DS::BUR14"; };
template<> struct address_map< 0x4003590e > { static constexpr const char * name_str = "DS::BUR15"; };
template<> struct address_map< 0x4003590f > { static constexpr const char * name_str = "DS::BUR16"; };
template<> struct address_map< 0x40036000 > { static constexpr const char * name_str = "USBCLK::UCCR"; };
template<> struct address_map< 0x40036004 > { static constexpr const char * name_str = "USBCLK::UPCR1"; };
template<> struct address_map< 0x40036008 > { static constexpr const char * name_str = "USBCLK::UPCR2"; };
template<> struct address_map< 0x4003600c > { static constexpr const char * name_str = "USBCLK::UPCR3"; };
template<> struct address_map< 0x40036010 > { static constexpr const char * name_str = "USBCLK::UPCR4"; };
template<> struct address_map< 0x40036014 > { static constexpr const char * name_str = "USBCLK::UP_STR"; };
template<> struct address_map< 0x40036018 > { static constexpr const char * name_str = "USBCLK::UPINT_ENR"; };
template<> struct address_map< 0x4003601c > { static constexpr const char * name_str = "USBCLK::UPINT_CLR"; };
template<> struct address_map< 0x40036020 > { static constexpr const char * name_str = "USBCLK::UPINT_STR"; };
template<> struct address_map< 0x40036024 > { static constexpr const char * name_str = "USBCLK::UPCR5"; };
template<> struct address_map< 0x40036030 > { static constexpr const char * name_str = "USBCLK::USBEN"; };
template<> struct address_map< 0x40038000 > { static constexpr const char * name_str = "MFS0::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SMR, MFS0::I2C_SMR, MFS0::UART_SMR */
template<> struct address_map< 0x40038001 > { static constexpr const char * name_str = "MFS0::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SCR, MFS0::I2C_IBCR, MFS0::UART_SCR */
template<> struct address_map< 0x40038004 > { static constexpr const char * name_str = "MFS0::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_ESCR, MFS0::I2C_IBSR, MFS0::UART_ESCR */
template<> struct address_map< 0x40038005 > { static constexpr const char * name_str = "MFS0::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SSR, MFS0::I2C_SSR, MFS0::UART_SSR */
template<> struct address_map< 0x40038008 > { static constexpr const char * name_str = "MFS0::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_RDR, MFS0::CSIO_TDR, MFS0::I2C_RDR, MFS0::I2C_TDR, MFS0::UART_RDR, MFS0::UART_TDR */
template<> struct address_map< 0x4003800c > { static constexpr const char * name_str = "MFS0::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_BGR, MFS0::I2C_BGR, MFS0::UART_BGR */
template<> struct address_map< 0x40038010 > { static constexpr const char * name_str = "MFS0::I2C_ISBA"; };
template<> struct address_map< 0x40038011 > { static constexpr const char * name_str = "MFS0::I2C_ISMK"; };
template<> struct address_map< 0x4003801d > { static constexpr const char * name_str = "MFS0::I2C_EIBCR"; };
template<> struct address_map< 0x40038100 > { static constexpr const char * name_str = "MFS1::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SMR, MFS1::I2C_SMR, MFS1::UART_SMR */
template<> struct address_map< 0x40038101 > { static constexpr const char * name_str = "MFS1::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SCR, MFS1::I2C_IBCR, MFS1::UART_SCR */
template<> struct address_map< 0x40038104 > { static constexpr const char * name_str = "MFS1::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_ESCR, MFS1::I2C_IBSR, MFS1::UART_ESCR */
template<> struct address_map< 0x40038105 > { static constexpr const char * name_str = "MFS1::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SSR, MFS1::I2C_SSR, MFS1::UART_SSR */
template<> struct address_map< 0x40038108 > { static constexpr const char * name_str = "MFS1::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_RDR, MFS1::CSIO_TDR, MFS1::I2C_RDR, MFS1::I2C_TDR, MFS1::UART_RDR, MFS1::UART_TDR */
template<> struct address_map< 0x4003810c > { static constexpr const char * name_str = "MFS1::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_BGR, MFS1::I2C_BGR, MFS1::UART_BGR */
template<> struct address_map< 0x40038110 > { static constexpr const char * name_str = "MFS1::I2C_ISBA"; };
template<> struct address_map< 0x40038111 > { static constexpr const char * name_str = "MFS1::I2C_ISMK"; };
template<> struct address_map< 0x4003811d > { static constexpr const char * name_str = "MFS1::I2C_EIBCR"; };
template<> struct address_map< 0x40038200 > { static constexpr const char * name_str = "MFS2::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SMR, MFS2::I2C_SMR, MFS2::UART_SMR */
template<> struct address_map< 0x40038201 > { static constexpr const char * name_str = "MFS2::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SCR, MFS2::I2C_IBCR, MFS2::UART_SCR */
template<> struct address_map< 0x40038204 > { static constexpr const char * name_str = "MFS2::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_ESCR, MFS2::I2C_IBSR, MFS2::UART_ESCR */
template<> struct address_map< 0x40038205 > { static constexpr const char * name_str = "MFS2::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_SSR, MFS2::I2C_SSR, MFS2::UART_SSR */
template<> struct address_map< 0x40038208 > { static constexpr const char * name_str = "MFS2::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_RDR, MFS2::CSIO_TDR, MFS2::I2C_RDR, MFS2::I2C_TDR, MFS2::UART_RDR, MFS2::UART_TDR */
template<> struct address_map< 0x4003820c > { static constexpr const char * name_str = "MFS2::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS2::CSIO_BGR, MFS2::I2C_BGR, MFS2::UART_BGR */
template<> struct address_map< 0x40038210 > { static constexpr const char * name_str = "MFS2::I2C_ISBA"; };
template<> struct address_map< 0x40038211 > { static constexpr const char * name_str = "MFS2::I2C_ISMK"; };
template<> struct address_map< 0x4003821d > { static constexpr const char * name_str = "MFS2::I2C_EIBCR"; };
template<> struct address_map< 0x40038300 > { static constexpr const char * name_str = "MFS3::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SMR, MFS3::I2C_SMR, MFS3::UART_SMR */
template<> struct address_map< 0x40038301 > { static constexpr const char * name_str = "MFS3::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SCR, MFS3::I2C_IBCR, MFS3::UART_SCR */
template<> struct address_map< 0x40038304 > { static constexpr const char * name_str = "MFS3::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_ESCR, MFS3::I2C_IBSR, MFS3::UART_ESCR */
template<> struct address_map< 0x40038305 > { static constexpr const char * name_str = "MFS3::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SSR, MFS3::I2C_SSR, MFS3::UART_SSR */
template<> struct address_map< 0x40038308 > { static constexpr const char * name_str = "MFS3::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_RDR, MFS3::CSIO_TDR, MFS3::I2C_RDR, MFS3::I2C_TDR, MFS3::UART_RDR, MFS3::UART_TDR */
template<> struct address_map< 0x4003830c > { static constexpr const char * name_str = "MFS3::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_BGR, MFS3::I2C_BGR, MFS3::UART_BGR */
template<> struct address_map< 0x40038310 > { static constexpr const char * name_str = "MFS3::I2C_ISBA"; };
template<> struct address_map< 0x40038311 > { static constexpr const char * name_str = "MFS3::I2C_ISMK"; };
template<> struct address_map< 0x4003831d > { static constexpr const char * name_str = "MFS3::I2C_EIBCR"; };
template<> struct address_map< 0x40038400 > { static constexpr const char * name_str = "MFS4::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SMR, MFS4::I2C_SMR, MFS4::UART_SMR */
template<> struct address_map< 0x40038401 > { static constexpr const char * name_str = "MFS4::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SCR, MFS4::I2C_IBCR, MFS4::UART_SCR */
template<> struct address_map< 0x40038404 > { static constexpr const char * name_str = "MFS4::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_ESCR, MFS4::I2C_IBSR, MFS4::UART_ESCR */
template<> struct address_map< 0x40038405 > { static constexpr const char * name_str = "MFS4::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_SSR, MFS4::I2C_SSR, MFS4::UART_SSR */
template<> struct address_map< 0x40038408 > { static constexpr const char * name_str = "MFS4::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_RDR, MFS4::CSIO_TDR, MFS4::I2C_RDR, MFS4::I2C_TDR, MFS4::UART_RDR, MFS4::UART_TDR */
template<> struct address_map< 0x4003840c > { static constexpr const char * name_str = "MFS4::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_BGR, MFS4::I2C_BGR, MFS4::UART_BGR */
template<> struct address_map< 0x40038410 > { static constexpr const char * name_str = "MFS4::I2C_ISBA"; };
template<> struct address_map< 0x40038411 > { static constexpr const char * name_str = "MFS4::I2C_ISMK"; };
template<> struct address_map< 0x40038414 > { static constexpr const char * name_str = "MFS4::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FCR0, MFS4::I2C_FCR0, MFS4::UART_FCR0 */
template<> struct address_map< 0x40038415 > { static constexpr const char * name_str = "MFS4::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FCR1, MFS4::I2C_FCR1, MFS4::UART_FCR1 */
template<> struct address_map< 0x40038418 > { static constexpr const char * name_str = "MFS4::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FBYTE1, MFS4::I2C_FBYTE1, MFS4::UART_FBYTE1 */
template<> struct address_map< 0x40038419 > { static constexpr const char * name_str = "MFS4::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS4::CSIO_FBYTE2, MFS4::I2C_FBYTE2, MFS4::UART_FBYTE2 */
template<> struct address_map< 0x4003841d > { static constexpr const char * name_str = "MFS4::I2C_EIBCR"; };
template<> struct address_map< 0x40038500 > { static constexpr const char * name_str = "MFS5::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SMR, MFS5::I2C_SMR, MFS5::UART_SMR */
template<> struct address_map< 0x40038501 > { static constexpr const char * name_str = "MFS5::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SCR, MFS5::I2C_IBCR, MFS5::UART_SCR */
template<> struct address_map< 0x40038504 > { static constexpr const char * name_str = "MFS5::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_ESCR, MFS5::I2C_IBSR, MFS5::UART_ESCR */
template<> struct address_map< 0x40038505 > { static constexpr const char * name_str = "MFS5::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_SSR, MFS5::I2C_SSR, MFS5::UART_SSR */
template<> struct address_map< 0x40038508 > { static constexpr const char * name_str = "MFS5::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_RDR, MFS5::CSIO_TDR, MFS5::I2C_RDR, MFS5::I2C_TDR, MFS5::UART_RDR, MFS5::UART_TDR */
template<> struct address_map< 0x4003850c > { static constexpr const char * name_str = "MFS5::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_BGR, MFS5::I2C_BGR, MFS5::UART_BGR */
template<> struct address_map< 0x40038510 > { static constexpr const char * name_str = "MFS5::I2C_ISBA"; };
template<> struct address_map< 0x40038511 > { static constexpr const char * name_str = "MFS5::I2C_ISMK"; };
template<> struct address_map< 0x40038514 > { static constexpr const char * name_str = "MFS5::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FCR0, MFS5::I2C_FCR0, MFS5::UART_FCR0 */
template<> struct address_map< 0x40038515 > { static constexpr const char * name_str = "MFS5::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FCR1, MFS5::I2C_FCR1, MFS5::UART_FCR1 */
template<> struct address_map< 0x40038518 > { static constexpr const char * name_str = "MFS5::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FBYTE1, MFS5::I2C_FBYTE1, MFS5::UART_FBYTE1 */
template<> struct address_map< 0x40038519 > { static constexpr const char * name_str = "MFS5::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS5::CSIO_FBYTE2, MFS5::I2C_FBYTE2, MFS5::UART_FBYTE2 */
template<> struct address_map< 0x4003851d > { static constexpr const char * name_str = "MFS5::I2C_EIBCR"; };
template<> struct address_map< 0x40038600 > { static constexpr const char * name_str = "MFS6::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SMR, MFS6::I2C_SMR, MFS6::UART_SMR */
template<> struct address_map< 0x40038601 > { static constexpr const char * name_str = "MFS6::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SCR, MFS6::I2C_IBCR, MFS6::UART_SCR */
template<> struct address_map< 0x40038604 > { static constexpr const char * name_str = "MFS6::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_ESCR, MFS6::I2C_IBSR, MFS6::UART_ESCR */
template<> struct address_map< 0x40038605 > { static constexpr const char * name_str = "MFS6::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_SSR, MFS6::I2C_SSR, MFS6::UART_SSR */
template<> struct address_map< 0x40038608 > { static constexpr const char * name_str = "MFS6::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_RDR, MFS6::CSIO_TDR, MFS6::I2C_RDR, MFS6::I2C_TDR, MFS6::UART_RDR, MFS6::UART_TDR */
template<> struct address_map< 0x4003860c > { static constexpr const char * name_str = "MFS6::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_BGR, MFS6::I2C_BGR, MFS6::UART_BGR */
template<> struct address_map< 0x40038610 > { static constexpr const char * name_str = "MFS6::I2C_ISBA"; };
template<> struct address_map< 0x40038611 > { static constexpr const char * name_str = "MFS6::I2C_ISMK"; };
template<> struct address_map< 0x40038614 > { static constexpr const char * name_str = "MFS6::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FCR0, MFS6::I2C_FCR0, MFS6::UART_FCR0 */
template<> struct address_map< 0x40038615 > { static constexpr const char * name_str = "MFS6::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FCR1, MFS6::I2C_FCR1, MFS6::UART_FCR1 */
template<> struct address_map< 0x40038618 > { static constexpr const char * name_str = "MFS6::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FBYTE1, MFS6::I2C_FBYTE1, MFS6::UART_FBYTE1 */
template<> struct address_map< 0x40038619 > { static constexpr const char * name_str = "MFS6::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS6::CSIO_FBYTE2, MFS6::I2C_FBYTE2, MFS6::UART_FBYTE2 */
template<> struct address_map< 0x4003861d > { static constexpr const char * name_str = "MFS6::I2C_EIBCR"; };
template<> struct address_map< 0x40038700 > { static constexpr const char * name_str = "MFS7::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SMR, MFS7::I2C_SMR, MFS7::UART_SMR */
template<> struct address_map< 0x40038701 > { static constexpr const char * name_str = "MFS7::I2C_IBCR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SCR, MFS7::I2C_IBCR, MFS7::UART_SCR */
template<> struct address_map< 0x40038704 > { static constexpr const char * name_str = "MFS7::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_ESCR, MFS7::I2C_IBSR, MFS7::UART_ESCR */
template<> struct address_map< 0x40038705 > { static constexpr const char * name_str = "MFS7::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_SSR, MFS7::I2C_SSR, MFS7::UART_SSR */
template<> struct address_map< 0x40038708 > { static constexpr const char * name_str = "MFS7::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_RDR, MFS7::CSIO_TDR, MFS7::I2C_RDR, MFS7::I2C_TDR, MFS7::UART_RDR, MFS7::UART_TDR */
template<> struct address_map< 0x4003870c > { static constexpr const char * name_str = "MFS7::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_BGR, MFS7::I2C_BGR, MFS7::UART_BGR */
template<> struct address_map< 0x40038710 > { static constexpr const char * name_str = "MFS7::I2C_ISBA"; };
template<> struct address_map< 0x40038711 > { static constexpr const char * name_str = "MFS7::I2C_ISMK"; };
template<> struct address_map< 0x40038714 > { static constexpr const char * name_str = "MFS7::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FCR0, MFS7::I2C_FCR0, MFS7::UART_FCR0 */
template<> struct address_map< 0x40038715 > { static constexpr const char * name_str = "MFS7::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FCR1, MFS7::I2C_FCR1, MFS7::UART_FCR1 */
template<> struct address_map< 0x40038718 > { static constexpr const char * name_str = "MFS7::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FBYTE1, MFS7::I2C_FBYTE1, MFS7::UART_FBYTE1 */
template<> struct address_map< 0x40038719 > { static constexpr const char * name_str = "MFS7::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS7::CSIO_FBYTE2, MFS7::I2C_FBYTE2, MFS7::UART_FBYTE2 */
template<> struct address_map< 0x4003871d > { static constexpr const char * name_str = "MFS7::I2C_EIBCR"; };
template<> struct address_map< 0x40039000 > { static constexpr const char * name_str = "CRC::CRCCR"; };
template<> struct address_map< 0x40039004 > { static constexpr const char * name_str = "CRC::CRCINIT"; };
template<> struct address_map< 0x40039008 > { static constexpr const char * name_str = "CRC::CRCIN"; };
template<> struct address_map< 0x4003900c > { static constexpr const char * name_str = "CRC::CRCR"; };
template<> struct address_map< 0x4003a000 > { static constexpr const char * name_str = "WC::WCRD"; };
template<> struct address_map< 0x4003a001 > { static constexpr const char * name_str = "WC::WCRL"; };
template<> struct address_map< 0x4003a002 > { static constexpr const char * name_str = "WC::WCCR"; };
template<> struct address_map< 0x4003a010 > { static constexpr const char * name_str = "WC::CLK_SEL"; };
template<> struct address_map< 0x4003a014 > { static constexpr const char * name_str = "WC::CLK_EN"; };
template<> struct address_map< 0x4003b000 > { static constexpr const char * name_str = "RTC::WTCR1"; };
template<> struct address_map< 0x4003b004 > { static constexpr const char * name_str = "RTC::WTCR2"; };
template<> struct address_map< 0x4003b008 > { static constexpr const char * name_str = "RTC::WTBR"; };
template<> struct address_map< 0x4003b00c > { static constexpr const char * name_str = "RTC::WTSR"; };
template<> struct address_map< 0x4003b00d > { static constexpr const char * name_str = "RTC::WTMIR"; };
template<> struct address_map< 0x4003b00e > { static constexpr const char * name_str = "RTC::WTHR"; };
template<> struct address_map< 0x4003b00f > { static constexpr const char * name_str = "RTC::WTDR"; };
template<> struct address_map< 0x4003b010 > { static constexpr const char * name_str = "RTC::WTDW"; };
template<> struct address_map< 0x4003b011 > { static constexpr const char * name_str = "RTC::WTMOR"; };
template<> struct address_map< 0x4003b012 > { static constexpr const char * name_str = "RTC::WTYR"; };
template<> struct address_map< 0x4003b015 > { static constexpr const char * name_str = "RTC::ALMIR"; };
template<> struct address_map< 0x4003b016 > { static constexpr const char * name_str = "RTC::ALHR"; };
template<> struct address_map< 0x4003b017 > { static constexpr const char * name_str = "RTC::ALDR"; };
template<> struct address_map< 0x4003b019 > { static constexpr const char * name_str = "RTC::ALMOR"; };
template<> struct address_map< 0x4003b01a > { static constexpr const char * name_str = "RTC::ALYR"; };
template<> struct address_map< 0x4003b01c > { static constexpr const char * name_str = "RTC::WTTR"; };
template<> struct address_map< 0x4003b020 > { static constexpr const char * name_str = "RTC::WTCLKS"; };
template<> struct address_map< 0x4003b021 > { static constexpr const char * name_str = "RTC::WTCLKM"; };
template<> struct address_map< 0x4003b024 > { static constexpr const char * name_str = "RTC::WTCAL"; };
template<> struct address_map< 0x4003b026 > { static constexpr const char * name_str = "RTC::WTCALEN"; };
template<> struct address_map< 0x4003b028 > { static constexpr const char * name_str = "RTC::WTDIV"; };
template<> struct address_map< 0x4003b029 > { static constexpr const char * name_str = "RTC::WTDIVEN"; };
template<> struct address_map< 0x4003b02c > { static constexpr const char * name_str = "RTC::WTCALPRD"; };
template<> struct address_map< 0x4003b030 > { static constexpr const char * name_str = "RTC::WTCOSEL"; };
template<> struct address_map< 0x4003f000 > { static constexpr const char * name_str = "EXBUS::MODE0"; };
template<> struct address_map< 0x4003f004 > { static constexpr const char * name_str = "EXBUS::MODE1"; };
template<> struct address_map< 0x4003f008 > { static constexpr const char * name_str = "EXBUS::MODE2"; };
template<> struct address_map< 0x4003f00c > { static constexpr const char * name_str = "EXBUS::MODE3"; };
template<> struct address_map< 0x4003f010 > { static constexpr const char * name_str = "EXBUS::MODE4"; };
template<> struct address_map< 0x4003f014 > { static constexpr const char * name_str = "EXBUS::MODE5"; };
template<> struct address_map< 0x4003f018 > { static constexpr const char * name_str = "EXBUS::MODE6"; };
template<> struct address_map< 0x4003f01c > { static constexpr const char * name_str = "EXBUS::MODE7"; };
template<> struct address_map< 0x4003f020 > { static constexpr const char * name_str = "EXBUS::TIM0"; };
template<> struct address_map< 0x4003f024 > { static constexpr const char * name_str = "EXBUS::TIM1"; };
template<> struct address_map< 0x4003f028 > { static constexpr const char * name_str = "EXBUS::TIM2"; };
template<> struct address_map< 0x4003f02c > { static constexpr const char * name_str = "EXBUS::TIM3"; };
template<> struct address_map< 0x4003f030 > { static constexpr const char * name_str = "EXBUS::TIM4"; };
template<> struct address_map< 0x4003f034 > { static constexpr const char * name_str = "EXBUS::TIM5"; };
template<> struct address_map< 0x4003f038 > { static constexpr const char * name_str = "EXBUS::TIM6"; };
template<> struct address_map< 0x4003f03c > { static constexpr const char * name_str = "EXBUS::TIM7"; };
template<> struct address_map< 0x4003f040 > { static constexpr const char * name_str = "EXBUS::AREA0"; };
template<> struct address_map< 0x4003f044 > { static constexpr const char * name_str = "EXBUS::AREA1"; };
template<> struct address_map< 0x4003f048 > { static constexpr const char * name_str = "EXBUS::AREA2"; };
template<> struct address_map< 0x4003f04c > { static constexpr const char * name_str = "EXBUS::AREA3"; };
template<> struct address_map< 0x4003f050 > { static constexpr const char * name_str = "EXBUS::AREA4"; };
template<> struct address_map< 0x4003f054 > { static constexpr const char * name_str = "EXBUS::AREA5"; };
template<> struct address_map< 0x4003f058 > { static constexpr const char * name_str = "EXBUS::AREA6"; };
template<> struct address_map< 0x4003f05c > { static constexpr const char * name_str = "EXBUS::AREA7"; };
template<> struct address_map< 0x4003f060 > { static constexpr const char * name_str = "EXBUS::ATIM0"; };
template<> struct address_map< 0x4003f064 > { static constexpr const char * name_str = "EXBUS::ATIM1"; };
template<> struct address_map< 0x4003f068 > { static constexpr const char * name_str = "EXBUS::ATIM2"; };
template<> struct address_map< 0x4003f06c > { static constexpr const char * name_str = "EXBUS::ATIM3"; };
template<> struct address_map< 0x4003f070 > { static constexpr const char * name_str = "EXBUS::ATIM4"; };
template<> struct address_map< 0x4003f074 > { static constexpr const char * name_str = "EXBUS::ATIM5"; };
template<> struct address_map< 0x4003f078 > { static constexpr const char * name_str = "EXBUS::ATIM6"; };
template<> struct address_map< 0x4003f07c > { static constexpr const char * name_str = "EXBUS::ATIM7"; };
template<> struct address_map< 0x4003f300 > { static constexpr const char * name_str = "EXBUS::DCLKR"; };
template<> struct address_map< 0x40042100 > { static constexpr const char * name_str = "USB0::HCNT"; };
template<> struct address_map< 0x40042104 > { static constexpr const char * name_str = "USB0::HIRQ"; };
template<> struct address_map< 0x40042105 > { static constexpr const char * name_str = "USB0::HERR"; };
template<> struct address_map< 0x40042108 > { static constexpr const char * name_str = "USB0::HSTATE"; };
template<> struct address_map< 0x40042109 > { static constexpr const char * name_str = "USB0::HFCOMP"; };
template<> struct address_map< 0x4004210c > { static constexpr const char * name_str = "USB0::HRTIMER"; };
template<> struct address_map< 0x40042110 > { static constexpr const char * name_str = "USB0::HRTIMER2"; };
template<> struct address_map< 0x40042111 > { static constexpr const char * name_str = "USB0::HADR"; };
template<> struct address_map< 0x40042114 > { static constexpr const char * name_str = "USB0::HEOF"; };
template<> struct address_map< 0x40042118 > { static constexpr const char * name_str = "USB0::HFRAME"; };
template<> struct address_map< 0x4004211c > { static constexpr const char * name_str = "USB0::HTOKEN"; };
template<> struct address_map< 0x40042120 > { static constexpr const char * name_str = "USB0::UDCC"; };
template<> struct address_map< 0x40042124 > { static constexpr const char * name_str = "USB0::EP0C"; };
template<> struct address_map< 0x40042128 > { static constexpr const char * name_str = "USB0::EP1C"; };
template<> struct address_map< 0x4004212c > { static constexpr const char * name_str = "USB0::EP2C"; };
template<> struct address_map< 0x40042130 > { static constexpr const char * name_str = "USB0::EP3C"; };
template<> struct address_map< 0x40042134 > { static constexpr const char * name_str = "USB0::EP4C"; };
template<> struct address_map< 0x40042138 > { static constexpr const char * name_str = "USB0::EP5C"; };
template<> struct address_map< 0x4004213c > { static constexpr const char * name_str = "USB0::TMSP"; };
template<> struct address_map< 0x40042140 > { static constexpr const char * name_str = "USB0::UDCS"; };
template<> struct address_map< 0x40042141 > { static constexpr const char * name_str = "USB0::UDCIE"; };
template<> struct address_map< 0x40042144 > { static constexpr const char * name_str = "USB0::EP0IS"; };
template<> struct address_map< 0x40042148 > { static constexpr const char * name_str = "USB0::EP0OS"; };
template<> struct address_map< 0x4004214c > { static constexpr const char * name_str = "USB0::EP1S"; };
template<> struct address_map< 0x40042150 > { static constexpr const char * name_str = "USB0::EP2S"; };
template<> struct address_map< 0x40042154 > { static constexpr const char * name_str = "USB0::EP3S"; };
template<> struct address_map< 0x40042158 > { static constexpr const char * name_str = "USB0::EP4S"; };
template<> struct address_map< 0x4004215c > { static constexpr const char * name_str = "USB0::EP5S"; };
template<> struct address_map< 0x40042160 > { static constexpr const char * name_str = "USB0::EP0DT"; };
template<> struct address_map< 0x40042164 > { static constexpr const char * name_str = "USB0::EP1DT"; };
template<> struct address_map< 0x40042168 > { static constexpr const char * name_str = "USB0::EP2DT"; };
template<> struct address_map< 0x4004216c > { static constexpr const char * name_str = "USB0::EP3DT"; };
template<> struct address_map< 0x40042170 > { static constexpr const char * name_str = "USB0::EP4DT"; };
template<> struct address_map< 0x40042174 > { static constexpr const char * name_str = "USB0::EP5DT"; };
template<> struct address_map< 0x40060000 > { static constexpr const char * name_str = "DMAC::DMACR"; };
template<> struct address_map< 0x40060010 > { static constexpr const char * name_str = "DMAC::DMACA0"; };
template<> struct address_map< 0x40060014 > { static constexpr const char * name_str = "DMAC::DMACB0"; };
template<> struct address_map< 0x40060018 > { static constexpr const char * name_str = "DMAC::DMACSA0"; };
template<> struct address_map< 0x4006001c > { static constexpr const char * name_str = "DMAC::DMACDA0"; };
template<> struct address_map< 0x40060020 > { static constexpr const char * name_str = "DMAC::DMACA1"; };
template<> struct address_map< 0x40060024 > { static constexpr const char * name_str = "DMAC::DMACB1"; };
template<> struct address_map< 0x40060028 > { static constexpr const char * name_str = "DMAC::DMACSA1"; };
template<> struct address_map< 0x4006002c > { static constexpr const char * name_str = "DMAC::DMACDA1"; };
template<> struct address_map< 0x40060030 > { static constexpr const char * name_str = "DMAC::DMACA2"; };
template<> struct address_map< 0x40060034 > { static constexpr const char * name_str = "DMAC::DMACB2"; };
template<> struct address_map< 0x40060038 > { static constexpr const char * name_str = "DMAC::DMACSA2"; };
template<> struct address_map< 0x4006003c > { static constexpr const char * name_str = "DMAC::DMACDA2"; };
template<> struct address_map< 0x40060040 > { static constexpr const char * name_str = "DMAC::DMACA3"; };
template<> struct address_map< 0x40060044 > { static constexpr const char * name_str = "DMAC::DMACB3"; };
template<> struct address_map< 0x40060048 > { static constexpr const char * name_str = "DMAC::DMACSA3"; };
template<> struct address_map< 0x4006004c > { static constexpr const char * name_str = "DMAC::DMACDA3"; };
template<> struct address_map< 0x40060050 > { static constexpr const char * name_str = "DMAC::DMACA4"; };
template<> struct address_map< 0x40060054 > { static constexpr const char * name_str = "DMAC::DMACB4"; };
template<> struct address_map< 0x40060058 > { static constexpr const char * name_str = "DMAC::DMACSA4"; };
template<> struct address_map< 0x4006005c > { static constexpr const char * name_str = "DMAC::DMACDA4"; };
template<> struct address_map< 0x40060060 > { static constexpr const char * name_str = "DMAC::DMACA5"; };
template<> struct address_map< 0x40060064 > { static constexpr const char * name_str = "DMAC::DMACB5"; };
template<> struct address_map< 0x40060068 > { static constexpr const char * name_str = "DMAC::DMACSA5"; };
template<> struct address_map< 0x4006006c > { static constexpr const char * name_str = "DMAC::DMACDA5"; };
template<> struct address_map< 0x40060070 > { static constexpr const char * name_str = "DMAC::DMACA6"; };
template<> struct address_map< 0x40060074 > { static constexpr const char * name_str = "DMAC::DMACB6"; };
template<> struct address_map< 0x40060078 > { static constexpr const char * name_str = "DMAC::DMACSA6"; };
template<> struct address_map< 0x4006007c > { static constexpr const char * name_str = "DMAC::DMACDA6"; };
template<> struct address_map< 0x40060080 > { static constexpr const char * name_str = "DMAC::DMACA7"; };
template<> struct address_map< 0x40060084 > { static constexpr const char * name_str = "DMAC::DMACB7"; };
template<> struct address_map< 0x40060088 > { static constexpr const char * name_str = "DMAC::DMACSA7"; };
template<> struct address_map< 0x4006008c > { static constexpr const char * name_str = "DMAC::DMACDA7"; };

} // namespace mptl

#endif // ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
