/*
 * OpenMPTL - C++ Microprocessor Template Library
 *
 * This program is a derivative representation of a CMSIS System View
 * Description (SVD) file, and is subject to the corresponding license
 * (see "License.html" in the parent directory).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

////////////////////////////////////////////////////////////////////////
//
//  Import from CMSIS-SVD: "Atmel/ATSAM3U4E.svd"
//
//  vendor: Atmel
//  name: ATSAM3U4E
//  series: SAM3U
//  version: 20130131
//  description: Atmel ATSAM3U4E device: Cortex-M3 Microcontroller with 256KB Flash, HS USB, 144 Pins (refer to http://www.atmel.com/devices/SAM3U4E.aspx for more)
//  --------------------------------------------------------------------
//
//  C++ Header file, containing architecture specific register
//  declarations for use in OpenMPTL. It has been converted directly
//  from a CMSIS-SVD file.
//
//  https://digint.ch/openmptl
//  https://github.com/posborne/cmsis-svd
//

#ifndef ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
#define ARCH_REG_ADDRESS_MAP_HPP_INCLUDED

#warning "using untested register declarations"

#include <register_type.hpp>

namespace mptl {

template<reg_addr_t addr>
struct address_map {
  static constexpr const char * name_str = nullptr;
};

template<> struct address_map< 0x40000000 > { static constexpr const char * name_str = "HSMCI::CR"; };
template<> struct address_map< 0x40000004 > { static constexpr const char * name_str = "HSMCI::MR"; };
template<> struct address_map< 0x40000008 > { static constexpr const char * name_str = "HSMCI::DTOR"; };
template<> struct address_map< 0x4000000c > { static constexpr const char * name_str = "HSMCI::SDCR"; };
template<> struct address_map< 0x40000010 > { static constexpr const char * name_str = "HSMCI::ARGR"; };
template<> struct address_map< 0x40000014 > { static constexpr const char * name_str = "HSMCI::CMDR"; };
template<> struct address_map< 0x40000018 > { static constexpr const char * name_str = "HSMCI::BLKR"; };
template<> struct address_map< 0x4000001c > { static constexpr const char * name_str = "HSMCI::CSTOR"; };
template<> struct address_map< 0x40000020 > { static constexpr const char * name_str = "HSMCI::RSPR[%s]"; };
template<> struct address_map< 0x40000030 > { static constexpr const char * name_str = "HSMCI::RDR"; };
template<> struct address_map< 0x40000034 > { static constexpr const char * name_str = "HSMCI::TDR"; };
template<> struct address_map< 0x40000040 > { static constexpr const char * name_str = "HSMCI::SR"; };
template<> struct address_map< 0x40000044 > { static constexpr const char * name_str = "HSMCI::IER"; };
template<> struct address_map< 0x40000048 > { static constexpr const char * name_str = "HSMCI::IDR"; };
template<> struct address_map< 0x4000004c > { static constexpr const char * name_str = "HSMCI::IMR"; };
template<> struct address_map< 0x40000050 > { static constexpr const char * name_str = "HSMCI::DMA"; };
template<> struct address_map< 0x40000054 > { static constexpr const char * name_str = "HSMCI::CFG"; };
template<> struct address_map< 0x400000e4 > { static constexpr const char * name_str = "HSMCI::WPMR"; };
template<> struct address_map< 0x400000e8 > { static constexpr const char * name_str = "HSMCI::WPSR"; };
template<> struct address_map< 0x40000200 > { static constexpr const char * name_str = "HSMCI::FIFO[%s]"; };
template<> struct address_map< 0x40004000 > { static constexpr const char * name_str = "SSC::CR"; };
template<> struct address_map< 0x40004004 > { static constexpr const char * name_str = "SSC::CMR"; };
template<> struct address_map< 0x40004010 > { static constexpr const char * name_str = "SSC::RCMR"; };
template<> struct address_map< 0x40004014 > { static constexpr const char * name_str = "SSC::RFMR"; };
template<> struct address_map< 0x40004018 > { static constexpr const char * name_str = "SSC::TCMR"; };
template<> struct address_map< 0x4000401c > { static constexpr const char * name_str = "SSC::TFMR"; };
template<> struct address_map< 0x40004020 > { static constexpr const char * name_str = "SSC::RHR"; };
template<> struct address_map< 0x40004024 > { static constexpr const char * name_str = "SSC::THR"; };
template<> struct address_map< 0x40004030 > { static constexpr const char * name_str = "SSC::RSHR"; };
template<> struct address_map< 0x40004034 > { static constexpr const char * name_str = "SSC::TSHR"; };
template<> struct address_map< 0x40004038 > { static constexpr const char * name_str = "SSC::RC0R"; };
template<> struct address_map< 0x4000403c > { static constexpr const char * name_str = "SSC::RC1R"; };
template<> struct address_map< 0x40004040 > { static constexpr const char * name_str = "SSC::SR"; };
template<> struct address_map< 0x40004044 > { static constexpr const char * name_str = "SSC::IER"; };
template<> struct address_map< 0x40004048 > { static constexpr const char * name_str = "SSC::IDR"; };
template<> struct address_map< 0x4000404c > { static constexpr const char * name_str = "SSC::IMR"; };
template<> struct address_map< 0x400040e4 > { static constexpr const char * name_str = "SSC::WPMR"; };
template<> struct address_map< 0x400040e8 > { static constexpr const char * name_str = "SSC::WPSR"; };
template<> struct address_map< 0x40008000 > { static constexpr const char * name_str = "SPI::CR"; };
template<> struct address_map< 0x40008004 > { static constexpr const char * name_str = "SPI::MR"; };
template<> struct address_map< 0x40008008 > { static constexpr const char * name_str = "SPI::RDR"; };
template<> struct address_map< 0x4000800c > { static constexpr const char * name_str = "SPI::TDR"; };
template<> struct address_map< 0x40008010 > { static constexpr const char * name_str = "SPI::SR"; };
template<> struct address_map< 0x40008014 > { static constexpr const char * name_str = "SPI::IER"; };
template<> struct address_map< 0x40008018 > { static constexpr const char * name_str = "SPI::IDR"; };
template<> struct address_map< 0x4000801c > { static constexpr const char * name_str = "SPI::IMR"; };
template<> struct address_map< 0x40008030 > { static constexpr const char * name_str = "SPI::CSR[%s]"; };
template<> struct address_map< 0x400080e4 > { static constexpr const char * name_str = "SPI::WPMR"; };
template<> struct address_map< 0x400080e8 > { static constexpr const char * name_str = "SPI::WPSR"; };
template<> struct address_map< 0x40080000 > { static constexpr const char * name_str = "TC0::CCR0"; };
template<> struct address_map< 0x40080004 > { static constexpr const char * name_str = "TC0::CMR0"; };  /* svd2hpp: duplicate address for: TC0::CMR0, TC0::CMR0_WAVE_EQ_1 */
template<> struct address_map< 0x40080010 > { static constexpr const char * name_str = "TC0::CV0"; };
template<> struct address_map< 0x40080014 > { static constexpr const char * name_str = "TC0::RA0"; };
template<> struct address_map< 0x40080018 > { static constexpr const char * name_str = "TC0::RB0"; };
template<> struct address_map< 0x4008001c > { static constexpr const char * name_str = "TC0::RC0"; };
template<> struct address_map< 0x40080020 > { static constexpr const char * name_str = "TC0::SR0"; };
template<> struct address_map< 0x40080024 > { static constexpr const char * name_str = "TC0::IER0"; };
template<> struct address_map< 0x40080028 > { static constexpr const char * name_str = "TC0::IDR0"; };
template<> struct address_map< 0x4008002c > { static constexpr const char * name_str = "TC0::IMR0"; };
template<> struct address_map< 0x40080040 > { static constexpr const char * name_str = "TC0::CCR1"; };
template<> struct address_map< 0x40080044 > { static constexpr const char * name_str = "TC0::CMR1"; };  /* svd2hpp: duplicate address for: TC0::CMR1, TC0::CMR1_WAVE_EQ_1 */
template<> struct address_map< 0x40080050 > { static constexpr const char * name_str = "TC0::CV1"; };
template<> struct address_map< 0x40080054 > { static constexpr const char * name_str = "TC0::RA1"; };
template<> struct address_map< 0x40080058 > { static constexpr const char * name_str = "TC0::RB1"; };
template<> struct address_map< 0x4008005c > { static constexpr const char * name_str = "TC0::RC1"; };
template<> struct address_map< 0x40080060 > { static constexpr const char * name_str = "TC0::SR1"; };
template<> struct address_map< 0x40080064 > { static constexpr const char * name_str = "TC0::IER1"; };
template<> struct address_map< 0x40080068 > { static constexpr const char * name_str = "TC0::IDR1"; };
template<> struct address_map< 0x4008006c > { static constexpr const char * name_str = "TC0::IMR1"; };
template<> struct address_map< 0x40080080 > { static constexpr const char * name_str = "TC0::CCR2"; };
template<> struct address_map< 0x40080084 > { static constexpr const char * name_str = "TC0::CMR2"; };  /* svd2hpp: duplicate address for: TC0::CMR2, TC0::CMR2_WAVE_EQ_1 */
template<> struct address_map< 0x40080090 > { static constexpr const char * name_str = "TC0::CV2"; };
template<> struct address_map< 0x40080094 > { static constexpr const char * name_str = "TC0::RA2"; };
template<> struct address_map< 0x40080098 > { static constexpr const char * name_str = "TC0::RB2"; };
template<> struct address_map< 0x4008009c > { static constexpr const char * name_str = "TC0::RC2"; };
template<> struct address_map< 0x400800a0 > { static constexpr const char * name_str = "TC0::SR2"; };
template<> struct address_map< 0x400800a4 > { static constexpr const char * name_str = "TC0::IER2"; };
template<> struct address_map< 0x400800a8 > { static constexpr const char * name_str = "TC0::IDR2"; };
template<> struct address_map< 0x400800ac > { static constexpr const char * name_str = "TC0::IMR2"; };
template<> struct address_map< 0x400800c0 > { static constexpr const char * name_str = "TC0::BCR"; };
template<> struct address_map< 0x400800c4 > { static constexpr const char * name_str = "TC0::BMR"; };
template<> struct address_map< 0x400800c8 > { static constexpr const char * name_str = "TC0::QIER"; };
template<> struct address_map< 0x400800cc > { static constexpr const char * name_str = "TC0::QIDR"; };
template<> struct address_map< 0x400800d0 > { static constexpr const char * name_str = "TC0::QIMR"; };
template<> struct address_map< 0x400800d4 > { static constexpr const char * name_str = "TC0::QISR"; };
template<> struct address_map< 0x40084000 > { static constexpr const char * name_str = "TWI0::CR"; };
template<> struct address_map< 0x40084004 > { static constexpr const char * name_str = "TWI0::MMR"; };
template<> struct address_map< 0x40084008 > { static constexpr const char * name_str = "TWI0::SMR"; };
template<> struct address_map< 0x4008400c > { static constexpr const char * name_str = "TWI0::IADR"; };
template<> struct address_map< 0x40084010 > { static constexpr const char * name_str = "TWI0::CWGR"; };
template<> struct address_map< 0x40084020 > { static constexpr const char * name_str = "TWI0::SR"; };
template<> struct address_map< 0x40084024 > { static constexpr const char * name_str = "TWI0::IER"; };
template<> struct address_map< 0x40084028 > { static constexpr const char * name_str = "TWI0::IDR"; };
template<> struct address_map< 0x4008402c > { static constexpr const char * name_str = "TWI0::IMR"; };
template<> struct address_map< 0x40084030 > { static constexpr const char * name_str = "TWI0::RHR"; };
template<> struct address_map< 0x40084034 > { static constexpr const char * name_str = "TWI0::THR"; };
template<> struct address_map< 0x40084100 > { static constexpr const char * name_str = "TWI0::RPR"; };
template<> struct address_map< 0x40084104 > { static constexpr const char * name_str = "TWI0::RCR"; };
template<> struct address_map< 0x40084108 > { static constexpr const char * name_str = "TWI0::TPR"; };
template<> struct address_map< 0x4008410c > { static constexpr const char * name_str = "TWI0::TCR"; };
template<> struct address_map< 0x40084110 > { static constexpr const char * name_str = "TWI0::RNPR"; };
template<> struct address_map< 0x40084114 > { static constexpr const char * name_str = "TWI0::RNCR"; };
template<> struct address_map< 0x40084118 > { static constexpr const char * name_str = "TWI0::TNPR"; };
template<> struct address_map< 0x4008411c > { static constexpr const char * name_str = "TWI0::TNCR"; };
template<> struct address_map< 0x40084120 > { static constexpr const char * name_str = "TWI0::PTCR"; };
template<> struct address_map< 0x40084124 > { static constexpr const char * name_str = "TWI0::PTSR"; };
template<> struct address_map< 0x40088000 > { static constexpr const char * name_str = "TWI1::CR"; };
template<> struct address_map< 0x40088004 > { static constexpr const char * name_str = "TWI1::MMR"; };
template<> struct address_map< 0x40088008 > { static constexpr const char * name_str = "TWI1::SMR"; };
template<> struct address_map< 0x4008800c > { static constexpr const char * name_str = "TWI1::IADR"; };
template<> struct address_map< 0x40088010 > { static constexpr const char * name_str = "TWI1::CWGR"; };
template<> struct address_map< 0x40088020 > { static constexpr const char * name_str = "TWI1::SR"; };
template<> struct address_map< 0x40088024 > { static constexpr const char * name_str = "TWI1::IER"; };
template<> struct address_map< 0x40088028 > { static constexpr const char * name_str = "TWI1::IDR"; };
template<> struct address_map< 0x4008802c > { static constexpr const char * name_str = "TWI1::IMR"; };
template<> struct address_map< 0x40088030 > { static constexpr const char * name_str = "TWI1::RHR"; };
template<> struct address_map< 0x40088034 > { static constexpr const char * name_str = "TWI1::THR"; };
template<> struct address_map< 0x40088100 > { static constexpr const char * name_str = "TWI1::RPR"; };
template<> struct address_map< 0x40088104 > { static constexpr const char * name_str = "TWI1::RCR"; };
template<> struct address_map< 0x40088108 > { static constexpr const char * name_str = "TWI1::TPR"; };
template<> struct address_map< 0x4008810c > { static constexpr const char * name_str = "TWI1::TCR"; };
template<> struct address_map< 0x40088110 > { static constexpr const char * name_str = "TWI1::RNPR"; };
template<> struct address_map< 0x40088114 > { static constexpr const char * name_str = "TWI1::RNCR"; };
template<> struct address_map< 0x40088118 > { static constexpr const char * name_str = "TWI1::TNPR"; };
template<> struct address_map< 0x4008811c > { static constexpr const char * name_str = "TWI1::TNCR"; };
template<> struct address_map< 0x40088120 > { static constexpr const char * name_str = "TWI1::PTCR"; };
template<> struct address_map< 0x40088124 > { static constexpr const char * name_str = "TWI1::PTSR"; };
template<> struct address_map< 0x4008c000 > { static constexpr const char * name_str = "PWM::CLK"; };
template<> struct address_map< 0x4008c004 > { static constexpr const char * name_str = "PWM::ENA"; };
template<> struct address_map< 0x4008c008 > { static constexpr const char * name_str = "PWM::DIS"; };
template<> struct address_map< 0x4008c00c > { static constexpr const char * name_str = "PWM::SR"; };
template<> struct address_map< 0x4008c010 > { static constexpr const char * name_str = "PWM::IER1"; };
template<> struct address_map< 0x4008c014 > { static constexpr const char * name_str = "PWM::IDR1"; };
template<> struct address_map< 0x4008c018 > { static constexpr const char * name_str = "PWM::IMR1"; };
template<> struct address_map< 0x4008c01c > { static constexpr const char * name_str = "PWM::ISR1"; };
template<> struct address_map< 0x4008c020 > { static constexpr const char * name_str = "PWM::SCM"; };
template<> struct address_map< 0x4008c028 > { static constexpr const char * name_str = "PWM::SCUC"; };
template<> struct address_map< 0x4008c02c > { static constexpr const char * name_str = "PWM::SCUP"; };
template<> struct address_map< 0x4008c030 > { static constexpr const char * name_str = "PWM::SCUPUPD"; };
template<> struct address_map< 0x4008c034 > { static constexpr const char * name_str = "PWM::IER2"; };
template<> struct address_map< 0x4008c038 > { static constexpr const char * name_str = "PWM::IDR2"; };
template<> struct address_map< 0x4008c03c > { static constexpr const char * name_str = "PWM::IMR2"; };
template<> struct address_map< 0x4008c040 > { static constexpr const char * name_str = "PWM::ISR2"; };
template<> struct address_map< 0x4008c044 > { static constexpr const char * name_str = "PWM::OOV"; };
template<> struct address_map< 0x4008c048 > { static constexpr const char * name_str = "PWM::OS"; };
template<> struct address_map< 0x4008c04c > { static constexpr const char * name_str = "PWM::OSS"; };
template<> struct address_map< 0x4008c050 > { static constexpr const char * name_str = "PWM::OSC"; };
template<> struct address_map< 0x4008c054 > { static constexpr const char * name_str = "PWM::OSSUPD"; };
template<> struct address_map< 0x4008c058 > { static constexpr const char * name_str = "PWM::OSCUPD"; };
template<> struct address_map< 0x4008c05c > { static constexpr const char * name_str = "PWM::FMR"; };
template<> struct address_map< 0x4008c060 > { static constexpr const char * name_str = "PWM::FSR"; };
template<> struct address_map< 0x4008c064 > { static constexpr const char * name_str = "PWM::FCR"; };
template<> struct address_map< 0x4008c068 > { static constexpr const char * name_str = "PWM::FPV"; };
template<> struct address_map< 0x4008c06c > { static constexpr const char * name_str = "PWM::FPE"; };
template<> struct address_map< 0x4008c07c > { static constexpr const char * name_str = "PWM::ELMR[%s]"; };
template<> struct address_map< 0x4008c0b0 > { static constexpr const char * name_str = "PWM::SMMR"; };
template<> struct address_map< 0x4008c0e4 > { static constexpr const char * name_str = "PWM::WPCR"; };
template<> struct address_map< 0x4008c0e8 > { static constexpr const char * name_str = "PWM::WPSR"; };
template<> struct address_map< 0x4008c108 > { static constexpr const char * name_str = "PWM::TPR"; };
template<> struct address_map< 0x4008c10c > { static constexpr const char * name_str = "PWM::TCR"; };
template<> struct address_map< 0x4008c118 > { static constexpr const char * name_str = "PWM::TNPR"; };
template<> struct address_map< 0x4008c11c > { static constexpr const char * name_str = "PWM::TNCR"; };
template<> struct address_map< 0x4008c120 > { static constexpr const char * name_str = "PWM::PTCR"; };
template<> struct address_map< 0x4008c124 > { static constexpr const char * name_str = "PWM::PTSR"; };
template<> struct address_map< 0x4008c130 > { static constexpr const char * name_str = "PWM::CMPV0"; };
template<> struct address_map< 0x4008c134 > { static constexpr const char * name_str = "PWM::CMPVUPD0"; };
template<> struct address_map< 0x4008c138 > { static constexpr const char * name_str = "PWM::CMPM0"; };
template<> struct address_map< 0x4008c13c > { static constexpr const char * name_str = "PWM::CMPMUPD0"; };
template<> struct address_map< 0x4008c140 > { static constexpr const char * name_str = "PWM::CMPV1"; };
template<> struct address_map< 0x4008c144 > { static constexpr const char * name_str = "PWM::CMPVUPD1"; };
template<> struct address_map< 0x4008c148 > { static constexpr const char * name_str = "PWM::CMPM1"; };
template<> struct address_map< 0x4008c14c > { static constexpr const char * name_str = "PWM::CMPMUPD1"; };
template<> struct address_map< 0x4008c150 > { static constexpr const char * name_str = "PWM::CMPV2"; };
template<> struct address_map< 0x4008c154 > { static constexpr const char * name_str = "PWM::CMPVUPD2"; };
template<> struct address_map< 0x4008c158 > { static constexpr const char * name_str = "PWM::CMPM2"; };
template<> struct address_map< 0x4008c15c > { static constexpr const char * name_str = "PWM::CMPMUPD2"; };
template<> struct address_map< 0x4008c160 > { static constexpr const char * name_str = "PWM::CMPV3"; };
template<> struct address_map< 0x4008c164 > { static constexpr const char * name_str = "PWM::CMPVUPD3"; };
template<> struct address_map< 0x4008c168 > { static constexpr const char * name_str = "PWM::CMPM3"; };
template<> struct address_map< 0x4008c16c > { static constexpr const char * name_str = "PWM::CMPMUPD3"; };
template<> struct address_map< 0x4008c170 > { static constexpr const char * name_str = "PWM::CMPV4"; };
template<> struct address_map< 0x4008c174 > { static constexpr const char * name_str = "PWM::CMPVUPD4"; };
template<> struct address_map< 0x4008c178 > { static constexpr const char * name_str = "PWM::CMPM4"; };
template<> struct address_map< 0x4008c17c > { static constexpr const char * name_str = "PWM::CMPMUPD4"; };
template<> struct address_map< 0x4008c180 > { static constexpr const char * name_str = "PWM::CMPV5"; };
template<> struct address_map< 0x4008c184 > { static constexpr const char * name_str = "PWM::CMPVUPD5"; };
template<> struct address_map< 0x4008c188 > { static constexpr const char * name_str = "PWM::CMPM5"; };
template<> struct address_map< 0x4008c18c > { static constexpr const char * name_str = "PWM::CMPMUPD5"; };
template<> struct address_map< 0x4008c190 > { static constexpr const char * name_str = "PWM::CMPV6"; };
template<> struct address_map< 0x4008c194 > { static constexpr const char * name_str = "PWM::CMPVUPD6"; };
template<> struct address_map< 0x4008c198 > { static constexpr const char * name_str = "PWM::CMPM6"; };
template<> struct address_map< 0x4008c19c > { static constexpr const char * name_str = "PWM::CMPMUPD6"; };
template<> struct address_map< 0x4008c1a0 > { static constexpr const char * name_str = "PWM::CMPV7"; };
template<> struct address_map< 0x4008c1a4 > { static constexpr const char * name_str = "PWM::CMPVUPD7"; };
template<> struct address_map< 0x4008c1a8 > { static constexpr const char * name_str = "PWM::CMPM7"; };
template<> struct address_map< 0x4008c1ac > { static constexpr const char * name_str = "PWM::CMPMUPD7"; };
template<> struct address_map< 0x4008c200 > { static constexpr const char * name_str = "PWM::CMR0"; };
template<> struct address_map< 0x4008c204 > { static constexpr const char * name_str = "PWM::CDTY0"; };
template<> struct address_map< 0x4008c208 > { static constexpr const char * name_str = "PWM::CDTYUPD0"; };
template<> struct address_map< 0x4008c20c > { static constexpr const char * name_str = "PWM::CPRD0"; };
template<> struct address_map< 0x4008c210 > { static constexpr const char * name_str = "PWM::CPRDUPD0"; };
template<> struct address_map< 0x4008c214 > { static constexpr const char * name_str = "PWM::CCNT0"; };
template<> struct address_map< 0x4008c218 > { static constexpr const char * name_str = "PWM::DT0"; };
template<> struct address_map< 0x4008c21c > { static constexpr const char * name_str = "PWM::DTUPD0"; };
template<> struct address_map< 0x4008c220 > { static constexpr const char * name_str = "PWM::CMR1"; };
template<> struct address_map< 0x4008c224 > { static constexpr const char * name_str = "PWM::CDTY1"; };
template<> struct address_map< 0x4008c228 > { static constexpr const char * name_str = "PWM::CDTYUPD1"; };
template<> struct address_map< 0x4008c22c > { static constexpr const char * name_str = "PWM::CPRD1"; };
template<> struct address_map< 0x4008c230 > { static constexpr const char * name_str = "PWM::CPRDUPD1"; };
template<> struct address_map< 0x4008c234 > { static constexpr const char * name_str = "PWM::CCNT1"; };
template<> struct address_map< 0x4008c238 > { static constexpr const char * name_str = "PWM::DT1"; };
template<> struct address_map< 0x4008c23c > { static constexpr const char * name_str = "PWM::DTUPD1"; };
template<> struct address_map< 0x4008c240 > { static constexpr const char * name_str = "PWM::CMR2"; };
template<> struct address_map< 0x4008c244 > { static constexpr const char * name_str = "PWM::CDTY2"; };
template<> struct address_map< 0x4008c248 > { static constexpr const char * name_str = "PWM::CDTYUPD2"; };
template<> struct address_map< 0x4008c24c > { static constexpr const char * name_str = "PWM::CPRD2"; };
template<> struct address_map< 0x4008c250 > { static constexpr const char * name_str = "PWM::CPRDUPD2"; };
template<> struct address_map< 0x4008c254 > { static constexpr const char * name_str = "PWM::CCNT2"; };
template<> struct address_map< 0x4008c258 > { static constexpr const char * name_str = "PWM::DT2"; };
template<> struct address_map< 0x4008c25c > { static constexpr const char * name_str = "PWM::DTUPD2"; };
template<> struct address_map< 0x4008c260 > { static constexpr const char * name_str = "PWM::CMR3"; };
template<> struct address_map< 0x4008c264 > { static constexpr const char * name_str = "PWM::CDTY3"; };
template<> struct address_map< 0x4008c268 > { static constexpr const char * name_str = "PWM::CDTYUPD3"; };
template<> struct address_map< 0x4008c26c > { static constexpr const char * name_str = "PWM::CPRD3"; };
template<> struct address_map< 0x4008c270 > { static constexpr const char * name_str = "PWM::CPRDUPD3"; };
template<> struct address_map< 0x4008c274 > { static constexpr const char * name_str = "PWM::CCNT3"; };
template<> struct address_map< 0x4008c278 > { static constexpr const char * name_str = "PWM::DT3"; };
template<> struct address_map< 0x4008c27c > { static constexpr const char * name_str = "PWM::DTUPD3"; };
template<> struct address_map< 0x40090000 > { static constexpr const char * name_str = "USART0::CR"; };  /* svd2hpp: duplicate address for: USART0::CR, USART0::CR_SPI_MODE */
template<> struct address_map< 0x40090004 > { static constexpr const char * name_str = "USART0::MR"; };  /* svd2hpp: duplicate address for: USART0::MR, USART0::MR_SPI_MODE */
template<> struct address_map< 0x40090008 > { static constexpr const char * name_str = "USART0::IER"; };  /* svd2hpp: duplicate address for: USART0::IER, USART0::IER_SPI_MODE */
template<> struct address_map< 0x4009000c > { static constexpr const char * name_str = "USART0::IDR"; };  /* svd2hpp: duplicate address for: USART0::IDR, USART0::IDR_SPI_MODE */
template<> struct address_map< 0x40090010 > { static constexpr const char * name_str = "USART0::IMR"; };  /* svd2hpp: duplicate address for: USART0::IMR, USART0::IMR_SPI_MODE */
template<> struct address_map< 0x40090014 > { static constexpr const char * name_str = "USART0::CSR"; };  /* svd2hpp: duplicate address for: USART0::CSR, USART0::CSR_SPI_MODE */
template<> struct address_map< 0x40090018 > { static constexpr const char * name_str = "USART0::RHR"; };
template<> struct address_map< 0x4009001c > { static constexpr const char * name_str = "USART0::THR"; };
template<> struct address_map< 0x40090020 > { static constexpr const char * name_str = "USART0::BRGR"; };
template<> struct address_map< 0x40090024 > { static constexpr const char * name_str = "USART0::RTOR"; };
template<> struct address_map< 0x40090028 > { static constexpr const char * name_str = "USART0::TTGR"; };
template<> struct address_map< 0x40090040 > { static constexpr const char * name_str = "USART0::FIDI"; };
template<> struct address_map< 0x40090044 > { static constexpr const char * name_str = "USART0::NER"; };
template<> struct address_map< 0x4009004c > { static constexpr const char * name_str = "USART0::IF"; };
template<> struct address_map< 0x40090050 > { static constexpr const char * name_str = "USART0::MAN"; };
template<> struct address_map< 0x400900e4 > { static constexpr const char * name_str = "USART0::WPMR"; };
template<> struct address_map< 0x400900e8 > { static constexpr const char * name_str = "USART0::WPSR"; };
template<> struct address_map< 0x40090100 > { static constexpr const char * name_str = "USART0::RPR"; };
template<> struct address_map< 0x40090104 > { static constexpr const char * name_str = "USART0::RCR"; };
template<> struct address_map< 0x40090108 > { static constexpr const char * name_str = "USART0::TPR"; };
template<> struct address_map< 0x4009010c > { static constexpr const char * name_str = "USART0::TCR"; };
template<> struct address_map< 0x40090110 > { static constexpr const char * name_str = "USART0::RNPR"; };
template<> struct address_map< 0x40090114 > { static constexpr const char * name_str = "USART0::RNCR"; };
template<> struct address_map< 0x40090118 > { static constexpr const char * name_str = "USART0::TNPR"; };
template<> struct address_map< 0x4009011c > { static constexpr const char * name_str = "USART0::TNCR"; };
template<> struct address_map< 0x40090120 > { static constexpr const char * name_str = "USART0::PTCR"; };
template<> struct address_map< 0x40090124 > { static constexpr const char * name_str = "USART0::PTSR"; };
template<> struct address_map< 0x40094000 > { static constexpr const char * name_str = "USART1::CR"; };  /* svd2hpp: duplicate address for: USART1::CR, USART1::CR_SPI_MODE */
template<> struct address_map< 0x40094004 > { static constexpr const char * name_str = "USART1::MR"; };  /* svd2hpp: duplicate address for: USART1::MR, USART1::MR_SPI_MODE */
template<> struct address_map< 0x40094008 > { static constexpr const char * name_str = "USART1::IER"; };  /* svd2hpp: duplicate address for: USART1::IER, USART1::IER_SPI_MODE */
template<> struct address_map< 0x4009400c > { static constexpr const char * name_str = "USART1::IDR"; };  /* svd2hpp: duplicate address for: USART1::IDR, USART1::IDR_SPI_MODE */
template<> struct address_map< 0x40094010 > { static constexpr const char * name_str = "USART1::IMR"; };  /* svd2hpp: duplicate address for: USART1::IMR, USART1::IMR_SPI_MODE */
template<> struct address_map< 0x40094014 > { static constexpr const char * name_str = "USART1::CSR"; };  /* svd2hpp: duplicate address for: USART1::CSR, USART1::CSR_SPI_MODE */
template<> struct address_map< 0x40094018 > { static constexpr const char * name_str = "USART1::RHR"; };
template<> struct address_map< 0x4009401c > { static constexpr const char * name_str = "USART1::THR"; };
template<> struct address_map< 0x40094020 > { static constexpr const char * name_str = "USART1::BRGR"; };
template<> struct address_map< 0x40094024 > { static constexpr const char * name_str = "USART1::RTOR"; };
template<> struct address_map< 0x40094028 > { static constexpr const char * name_str = "USART1::TTGR"; };
template<> struct address_map< 0x40094040 > { static constexpr const char * name_str = "USART1::FIDI"; };
template<> struct address_map< 0x40094044 > { static constexpr const char * name_str = "USART1::NER"; };
template<> struct address_map< 0x4009404c > { static constexpr const char * name_str = "USART1::IF"; };
template<> struct address_map< 0x40094050 > { static constexpr const char * name_str = "USART1::MAN"; };
template<> struct address_map< 0x400940e4 > { static constexpr const char * name_str = "USART1::WPMR"; };
template<> struct address_map< 0x400940e8 > { static constexpr const char * name_str = "USART1::WPSR"; };
template<> struct address_map< 0x40094100 > { static constexpr const char * name_str = "USART1::RPR"; };
template<> struct address_map< 0x40094104 > { static constexpr const char * name_str = "USART1::RCR"; };
template<> struct address_map< 0x40094108 > { static constexpr const char * name_str = "USART1::TPR"; };
template<> struct address_map< 0x4009410c > { static constexpr const char * name_str = "USART1::TCR"; };
template<> struct address_map< 0x40094110 > { static constexpr const char * name_str = "USART1::RNPR"; };
template<> struct address_map< 0x40094114 > { static constexpr const char * name_str = "USART1::RNCR"; };
template<> struct address_map< 0x40094118 > { static constexpr const char * name_str = "USART1::TNPR"; };
template<> struct address_map< 0x4009411c > { static constexpr const char * name_str = "USART1::TNCR"; };
template<> struct address_map< 0x40094120 > { static constexpr const char * name_str = "USART1::PTCR"; };
template<> struct address_map< 0x40094124 > { static constexpr const char * name_str = "USART1::PTSR"; };
template<> struct address_map< 0x40098000 > { static constexpr const char * name_str = "USART2::CR"; };  /* svd2hpp: duplicate address for: USART2::CR, USART2::CR_SPI_MODE */
template<> struct address_map< 0x40098004 > { static constexpr const char * name_str = "USART2::MR"; };  /* svd2hpp: duplicate address for: USART2::MR, USART2::MR_SPI_MODE */
template<> struct address_map< 0x40098008 > { static constexpr const char * name_str = "USART2::IER"; };  /* svd2hpp: duplicate address for: USART2::IER, USART2::IER_SPI_MODE */
template<> struct address_map< 0x4009800c > { static constexpr const char * name_str = "USART2::IDR"; };  /* svd2hpp: duplicate address for: USART2::IDR, USART2::IDR_SPI_MODE */
template<> struct address_map< 0x40098010 > { static constexpr const char * name_str = "USART2::IMR"; };  /* svd2hpp: duplicate address for: USART2::IMR, USART2::IMR_SPI_MODE */
template<> struct address_map< 0x40098014 > { static constexpr const char * name_str = "USART2::CSR"; };  /* svd2hpp: duplicate address for: USART2::CSR, USART2::CSR_SPI_MODE */
template<> struct address_map< 0x40098018 > { static constexpr const char * name_str = "USART2::RHR"; };
template<> struct address_map< 0x4009801c > { static constexpr const char * name_str = "USART2::THR"; };
template<> struct address_map< 0x40098020 > { static constexpr const char * name_str = "USART2::BRGR"; };
template<> struct address_map< 0x40098024 > { static constexpr const char * name_str = "USART2::RTOR"; };
template<> struct address_map< 0x40098028 > { static constexpr const char * name_str = "USART2::TTGR"; };
template<> struct address_map< 0x40098040 > { static constexpr const char * name_str = "USART2::FIDI"; };
template<> struct address_map< 0x40098044 > { static constexpr const char * name_str = "USART2::NER"; };
template<> struct address_map< 0x4009804c > { static constexpr const char * name_str = "USART2::IF"; };
template<> struct address_map< 0x40098050 > { static constexpr const char * name_str = "USART2::MAN"; };
template<> struct address_map< 0x400980e4 > { static constexpr const char * name_str = "USART2::WPMR"; };
template<> struct address_map< 0x400980e8 > { static constexpr const char * name_str = "USART2::WPSR"; };
template<> struct address_map< 0x40098100 > { static constexpr const char * name_str = "USART2::RPR"; };
template<> struct address_map< 0x40098104 > { static constexpr const char * name_str = "USART2::RCR"; };
template<> struct address_map< 0x40098108 > { static constexpr const char * name_str = "USART2::TPR"; };
template<> struct address_map< 0x4009810c > { static constexpr const char * name_str = "USART2::TCR"; };
template<> struct address_map< 0x40098110 > { static constexpr const char * name_str = "USART2::RNPR"; };
template<> struct address_map< 0x40098114 > { static constexpr const char * name_str = "USART2::RNCR"; };
template<> struct address_map< 0x40098118 > { static constexpr const char * name_str = "USART2::TNPR"; };
template<> struct address_map< 0x4009811c > { static constexpr const char * name_str = "USART2::TNCR"; };
template<> struct address_map< 0x40098120 > { static constexpr const char * name_str = "USART2::PTCR"; };
template<> struct address_map< 0x40098124 > { static constexpr const char * name_str = "USART2::PTSR"; };
template<> struct address_map< 0x4009c000 > { static constexpr const char * name_str = "USART3::CR"; };  /* svd2hpp: duplicate address for: USART3::CR, USART3::CR_SPI_MODE */
template<> struct address_map< 0x4009c004 > { static constexpr const char * name_str = "USART3::MR"; };  /* svd2hpp: duplicate address for: USART3::MR, USART3::MR_SPI_MODE */
template<> struct address_map< 0x4009c008 > { static constexpr const char * name_str = "USART3::IER"; };  /* svd2hpp: duplicate address for: USART3::IER, USART3::IER_SPI_MODE */
template<> struct address_map< 0x4009c00c > { static constexpr const char * name_str = "USART3::IDR"; };  /* svd2hpp: duplicate address for: USART3::IDR, USART3::IDR_SPI_MODE */
template<> struct address_map< 0x4009c010 > { static constexpr const char * name_str = "USART3::IMR"; };  /* svd2hpp: duplicate address for: USART3::IMR, USART3::IMR_SPI_MODE */
template<> struct address_map< 0x4009c014 > { static constexpr const char * name_str = "USART3::CSR"; };  /* svd2hpp: duplicate address for: USART3::CSR, USART3::CSR_SPI_MODE */
template<> struct address_map< 0x4009c018 > { static constexpr const char * name_str = "USART3::RHR"; };
template<> struct address_map< 0x4009c01c > { static constexpr const char * name_str = "USART3::THR"; };
template<> struct address_map< 0x4009c020 > { static constexpr const char * name_str = "USART3::BRGR"; };
template<> struct address_map< 0x4009c024 > { static constexpr const char * name_str = "USART3::RTOR"; };
template<> struct address_map< 0x4009c028 > { static constexpr const char * name_str = "USART3::TTGR"; };
template<> struct address_map< 0x4009c040 > { static constexpr const char * name_str = "USART3::FIDI"; };
template<> struct address_map< 0x4009c044 > { static constexpr const char * name_str = "USART3::NER"; };
template<> struct address_map< 0x4009c04c > { static constexpr const char * name_str = "USART3::IF"; };
template<> struct address_map< 0x4009c050 > { static constexpr const char * name_str = "USART3::MAN"; };
template<> struct address_map< 0x4009c0e4 > { static constexpr const char * name_str = "USART3::WPMR"; };
template<> struct address_map< 0x4009c0e8 > { static constexpr const char * name_str = "USART3::WPSR"; };
template<> struct address_map< 0x4009c100 > { static constexpr const char * name_str = "USART3::RPR"; };
template<> struct address_map< 0x4009c104 > { static constexpr const char * name_str = "USART3::RCR"; };
template<> struct address_map< 0x4009c108 > { static constexpr const char * name_str = "USART3::TPR"; };
template<> struct address_map< 0x4009c10c > { static constexpr const char * name_str = "USART3::TCR"; };
template<> struct address_map< 0x4009c110 > { static constexpr const char * name_str = "USART3::RNPR"; };
template<> struct address_map< 0x4009c114 > { static constexpr const char * name_str = "USART3::RNCR"; };
template<> struct address_map< 0x4009c118 > { static constexpr const char * name_str = "USART3::TNPR"; };
template<> struct address_map< 0x4009c11c > { static constexpr const char * name_str = "USART3::TNCR"; };
template<> struct address_map< 0x4009c120 > { static constexpr const char * name_str = "USART3::PTCR"; };
template<> struct address_map< 0x4009c124 > { static constexpr const char * name_str = "USART3::PTSR"; };
template<> struct address_map< 0x400a4000 > { static constexpr const char * name_str = "UDPHS::CTRL"; };
template<> struct address_map< 0x400a4004 > { static constexpr const char * name_str = "UDPHS::FNUM"; };
template<> struct address_map< 0x400a4010 > { static constexpr const char * name_str = "UDPHS::IEN"; };
template<> struct address_map< 0x400a4014 > { static constexpr const char * name_str = "UDPHS::INTSTA"; };
template<> struct address_map< 0x400a4018 > { static constexpr const char * name_str = "UDPHS::CLRINT"; };
template<> struct address_map< 0x400a401c > { static constexpr const char * name_str = "UDPHS::EPTRST"; };
template<> struct address_map< 0x400a40e0 > { static constexpr const char * name_str = "UDPHS::TST"; };
template<> struct address_map< 0x400a4100 > { static constexpr const char * name_str = "UDPHS::EPTCFG0"; };
template<> struct address_map< 0x400a4104 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB0, UDPHS::EPTCTLENB0_ISOENDPT */
template<> struct address_map< 0x400a4108 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS0, UDPHS::EPTCTLDIS0_ISOENDPT */
template<> struct address_map< 0x400a410c > { static constexpr const char * name_str = "UDPHS::EPTCTL0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL0, UDPHS::EPTCTL0_ISOENDPT */
template<> struct address_map< 0x400a4114 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA0, UDPHS::EPTSETSTA0_ISOENDPT */
template<> struct address_map< 0x400a4118 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA0, UDPHS::EPTCLRSTA0_ISOENDPT */
template<> struct address_map< 0x400a411c > { static constexpr const char * name_str = "UDPHS::EPTSTA0"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA0, UDPHS::EPTSTA0_ISOENDPT */
template<> struct address_map< 0x400a4120 > { static constexpr const char * name_str = "UDPHS::EPTCFG1"; };
template<> struct address_map< 0x400a4124 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB1, UDPHS::EPTCTLENB1_ISOENDPT */
template<> struct address_map< 0x400a4128 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS1, UDPHS::EPTCTLDIS1_ISOENDPT */
template<> struct address_map< 0x400a412c > { static constexpr const char * name_str = "UDPHS::EPTCTL1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL1, UDPHS::EPTCTL1_ISOENDPT */
template<> struct address_map< 0x400a4134 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA1, UDPHS::EPTSETSTA1_ISOENDPT */
template<> struct address_map< 0x400a4138 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA1, UDPHS::EPTCLRSTA1_ISOENDPT */
template<> struct address_map< 0x400a413c > { static constexpr const char * name_str = "UDPHS::EPTSTA1"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA1, UDPHS::EPTSTA1_ISOENDPT */
template<> struct address_map< 0x400a4140 > { static constexpr const char * name_str = "UDPHS::EPTCFG2"; };
template<> struct address_map< 0x400a4144 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB2, UDPHS::EPTCTLENB2_ISOENDPT */
template<> struct address_map< 0x400a4148 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS2, UDPHS::EPTCTLDIS2_ISOENDPT */
template<> struct address_map< 0x400a414c > { static constexpr const char * name_str = "UDPHS::EPTCTL2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL2, UDPHS::EPTCTL2_ISOENDPT */
template<> struct address_map< 0x400a4154 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA2, UDPHS::EPTSETSTA2_ISOENDPT */
template<> struct address_map< 0x400a4158 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA2, UDPHS::EPTCLRSTA2_ISOENDPT */
template<> struct address_map< 0x400a415c > { static constexpr const char * name_str = "UDPHS::EPTSTA2"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA2, UDPHS::EPTSTA2_ISOENDPT */
template<> struct address_map< 0x400a4160 > { static constexpr const char * name_str = "UDPHS::EPTCFG3"; };
template<> struct address_map< 0x400a4164 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB3, UDPHS::EPTCTLENB3_ISOENDPT */
template<> struct address_map< 0x400a4168 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS3, UDPHS::EPTCTLDIS3_ISOENDPT */
template<> struct address_map< 0x400a416c > { static constexpr const char * name_str = "UDPHS::EPTCTL3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL3, UDPHS::EPTCTL3_ISOENDPT */
template<> struct address_map< 0x400a4174 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA3, UDPHS::EPTSETSTA3_ISOENDPT */
template<> struct address_map< 0x400a4178 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA3, UDPHS::EPTCLRSTA3_ISOENDPT */
template<> struct address_map< 0x400a417c > { static constexpr const char * name_str = "UDPHS::EPTSTA3"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA3, UDPHS::EPTSTA3_ISOENDPT */
template<> struct address_map< 0x400a4180 > { static constexpr const char * name_str = "UDPHS::EPTCFG4"; };
template<> struct address_map< 0x400a4184 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB4, UDPHS::EPTCTLENB4_ISOENDPT */
template<> struct address_map< 0x400a4188 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS4, UDPHS::EPTCTLDIS4_ISOENDPT */
template<> struct address_map< 0x400a418c > { static constexpr const char * name_str = "UDPHS::EPTCTL4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL4, UDPHS::EPTCTL4_ISOENDPT */
template<> struct address_map< 0x400a4194 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA4, UDPHS::EPTSETSTA4_ISOENDPT */
template<> struct address_map< 0x400a4198 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA4, UDPHS::EPTCLRSTA4_ISOENDPT */
template<> struct address_map< 0x400a419c > { static constexpr const char * name_str = "UDPHS::EPTSTA4"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA4, UDPHS::EPTSTA4_ISOENDPT */
template<> struct address_map< 0x400a41a0 > { static constexpr const char * name_str = "UDPHS::EPTCFG5"; };
template<> struct address_map< 0x400a41a4 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB5, UDPHS::EPTCTLENB5_ISOENDPT */
template<> struct address_map< 0x400a41a8 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS5, UDPHS::EPTCTLDIS5_ISOENDPT */
template<> struct address_map< 0x400a41ac > { static constexpr const char * name_str = "UDPHS::EPTCTL5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL5, UDPHS::EPTCTL5_ISOENDPT */
template<> struct address_map< 0x400a41b4 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA5, UDPHS::EPTSETSTA5_ISOENDPT */
template<> struct address_map< 0x400a41b8 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA5, UDPHS::EPTCLRSTA5_ISOENDPT */
template<> struct address_map< 0x400a41bc > { static constexpr const char * name_str = "UDPHS::EPTSTA5"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA5, UDPHS::EPTSTA5_ISOENDPT */
template<> struct address_map< 0x400a41c0 > { static constexpr const char * name_str = "UDPHS::EPTCFG6"; };
template<> struct address_map< 0x400a41c4 > { static constexpr const char * name_str = "UDPHS::EPTCTLENB6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLENB6, UDPHS::EPTCTLENB6_ISOENDPT */
template<> struct address_map< 0x400a41c8 > { static constexpr const char * name_str = "UDPHS::EPTCTLDIS6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTLDIS6, UDPHS::EPTCTLDIS6_ISOENDPT */
template<> struct address_map< 0x400a41cc > { static constexpr const char * name_str = "UDPHS::EPTCTL6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCTL6, UDPHS::EPTCTL6_ISOENDPT */
template<> struct address_map< 0x400a41d4 > { static constexpr const char * name_str = "UDPHS::EPTSETSTA6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSETSTA6, UDPHS::EPTSETSTA6_ISOENDPT */
template<> struct address_map< 0x400a41d8 > { static constexpr const char * name_str = "UDPHS::EPTCLRSTA6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTCLRSTA6, UDPHS::EPTCLRSTA6_ISOENDPT */
template<> struct address_map< 0x400a41dc > { static constexpr const char * name_str = "UDPHS::EPTSTA6"; };  /* svd2hpp: duplicate address for: UDPHS::EPTSTA6, UDPHS::EPTSTA6_ISOENDPT */
template<> struct address_map< 0x400a4300 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC0"; };
template<> struct address_map< 0x400a4304 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS0"; };
template<> struct address_map< 0x400a4308 > { static constexpr const char * name_str = "UDPHS::DMACONTROL0"; };
template<> struct address_map< 0x400a430c > { static constexpr const char * name_str = "UDPHS::DMASTATUS0"; };
template<> struct address_map< 0x400a4310 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC1"; };
template<> struct address_map< 0x400a4314 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS1"; };
template<> struct address_map< 0x400a4318 > { static constexpr const char * name_str = "UDPHS::DMACONTROL1"; };
template<> struct address_map< 0x400a431c > { static constexpr const char * name_str = "UDPHS::DMASTATUS1"; };
template<> struct address_map< 0x400a4320 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC2"; };
template<> struct address_map< 0x400a4324 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS2"; };
template<> struct address_map< 0x400a4328 > { static constexpr const char * name_str = "UDPHS::DMACONTROL2"; };
template<> struct address_map< 0x400a432c > { static constexpr const char * name_str = "UDPHS::DMASTATUS2"; };
template<> struct address_map< 0x400a4330 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC3"; };
template<> struct address_map< 0x400a4334 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS3"; };
template<> struct address_map< 0x400a4338 > { static constexpr const char * name_str = "UDPHS::DMACONTROL3"; };
template<> struct address_map< 0x400a433c > { static constexpr const char * name_str = "UDPHS::DMASTATUS3"; };
template<> struct address_map< 0x400a4340 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC4"; };
template<> struct address_map< 0x400a4344 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS4"; };
template<> struct address_map< 0x400a4348 > { static constexpr const char * name_str = "UDPHS::DMACONTROL4"; };
template<> struct address_map< 0x400a434c > { static constexpr const char * name_str = "UDPHS::DMASTATUS4"; };
template<> struct address_map< 0x400a4350 > { static constexpr const char * name_str = "UDPHS::DMANXTDSC5"; };
template<> struct address_map< 0x400a4354 > { static constexpr const char * name_str = "UDPHS::DMAADDRESS5"; };
template<> struct address_map< 0x400a4358 > { static constexpr const char * name_str = "UDPHS::DMACONTROL5"; };
template<> struct address_map< 0x400a435c > { static constexpr const char * name_str = "UDPHS::DMASTATUS5"; };
template<> struct address_map< 0x400a8000 > { static constexpr const char * name_str = "ADC12B::CR"; };
template<> struct address_map< 0x400a8004 > { static constexpr const char * name_str = "ADC12B::MR"; };
template<> struct address_map< 0x400a8010 > { static constexpr const char * name_str = "ADC12B::CHER"; };
template<> struct address_map< 0x400a8014 > { static constexpr const char * name_str = "ADC12B::CHDR"; };
template<> struct address_map< 0x400a8018 > { static constexpr const char * name_str = "ADC12B::CHSR"; };
template<> struct address_map< 0x400a801c > { static constexpr const char * name_str = "ADC12B::SR"; };
template<> struct address_map< 0x400a8020 > { static constexpr const char * name_str = "ADC12B::LCDR"; };
template<> struct address_map< 0x400a8024 > { static constexpr const char * name_str = "ADC12B::IER"; };
template<> struct address_map< 0x400a8028 > { static constexpr const char * name_str = "ADC12B::IDR"; };
template<> struct address_map< 0x400a802c > { static constexpr const char * name_str = "ADC12B::IMR"; };
template<> struct address_map< 0x400a8030 > { static constexpr const char * name_str = "ADC12B::CDR[%s]"; };
template<> struct address_map< 0x400a8064 > { static constexpr const char * name_str = "ADC12B::ACR"; };
template<> struct address_map< 0x400a8068 > { static constexpr const char * name_str = "ADC12B::EMR"; };
template<> struct address_map< 0x400a8100 > { static constexpr const char * name_str = "ADC12B::RPR"; };
template<> struct address_map< 0x400a8104 > { static constexpr const char * name_str = "ADC12B::RCR"; };
template<> struct address_map< 0x400a8110 > { static constexpr const char * name_str = "ADC12B::RNPR"; };
template<> struct address_map< 0x400a8114 > { static constexpr const char * name_str = "ADC12B::RNCR"; };
template<> struct address_map< 0x400a8120 > { static constexpr const char * name_str = "ADC12B::PTCR"; };
template<> struct address_map< 0x400a8124 > { static constexpr const char * name_str = "ADC12B::PTSR"; };
template<> struct address_map< 0x400ac000 > { static constexpr const char * name_str = "ADC::CR"; };
template<> struct address_map< 0x400ac004 > { static constexpr const char * name_str = "ADC::MR"; };
template<> struct address_map< 0x400ac010 > { static constexpr const char * name_str = "ADC::CHER"; };
template<> struct address_map< 0x400ac014 > { static constexpr const char * name_str = "ADC::CHDR"; };
template<> struct address_map< 0x400ac018 > { static constexpr const char * name_str = "ADC::CHSR"; };
template<> struct address_map< 0x400ac01c > { static constexpr const char * name_str = "ADC::SR"; };
template<> struct address_map< 0x400ac020 > { static constexpr const char * name_str = "ADC::LCDR"; };
template<> struct address_map< 0x400ac024 > { static constexpr const char * name_str = "ADC::IER"; };
template<> struct address_map< 0x400ac028 > { static constexpr const char * name_str = "ADC::IDR"; };
template<> struct address_map< 0x400ac02c > { static constexpr const char * name_str = "ADC::IMR"; };
template<> struct address_map< 0x400ac030 > { static constexpr const char * name_str = "ADC::CDR[%s]"; };
template<> struct address_map< 0x400ac100 > { static constexpr const char * name_str = "ADC::RPR"; };
template<> struct address_map< 0x400ac104 > { static constexpr const char * name_str = "ADC::RCR"; };
template<> struct address_map< 0x400ac110 > { static constexpr const char * name_str = "ADC::RNPR"; };
template<> struct address_map< 0x400ac114 > { static constexpr const char * name_str = "ADC::RNCR"; };
template<> struct address_map< 0x400ac120 > { static constexpr const char * name_str = "ADC::PTCR"; };
template<> struct address_map< 0x400ac124 > { static constexpr const char * name_str = "ADC::PTSR"; };
template<> struct address_map< 0x400b0000 > { static constexpr const char * name_str = "DMAC::GCFG"; };
template<> struct address_map< 0x400b0004 > { static constexpr const char * name_str = "DMAC::EN"; };
template<> struct address_map< 0x400b0008 > { static constexpr const char * name_str = "DMAC::SREQ"; };
template<> struct address_map< 0x400b000c > { static constexpr const char * name_str = "DMAC::CREQ"; };
template<> struct address_map< 0x400b0010 > { static constexpr const char * name_str = "DMAC::LAST"; };
template<> struct address_map< 0x400b0018 > { static constexpr const char * name_str = "DMAC::EBCIER"; };
template<> struct address_map< 0x400b001c > { static constexpr const char * name_str = "DMAC::EBCIDR"; };
template<> struct address_map< 0x400b0020 > { static constexpr const char * name_str = "DMAC::EBCIMR"; };
template<> struct address_map< 0x400b0024 > { static constexpr const char * name_str = "DMAC::EBCISR"; };
template<> struct address_map< 0x400b0028 > { static constexpr const char * name_str = "DMAC::CHER"; };
template<> struct address_map< 0x400b002c > { static constexpr const char * name_str = "DMAC::CHDR"; };
template<> struct address_map< 0x400b0030 > { static constexpr const char * name_str = "DMAC::CHSR"; };
template<> struct address_map< 0x400b003c > { static constexpr const char * name_str = "DMAC::SADDR0"; };
template<> struct address_map< 0x400b0040 > { static constexpr const char * name_str = "DMAC::DADDR0"; };
template<> struct address_map< 0x400b0044 > { static constexpr const char * name_str = "DMAC::DSCR0"; };
template<> struct address_map< 0x400b0048 > { static constexpr const char * name_str = "DMAC::CTRLA0"; };
template<> struct address_map< 0x400b004c > { static constexpr const char * name_str = "DMAC::CTRLB0"; };
template<> struct address_map< 0x400b0050 > { static constexpr const char * name_str = "DMAC::CFG0"; };
template<> struct address_map< 0x400b0064 > { static constexpr const char * name_str = "DMAC::SADDR1"; };
template<> struct address_map< 0x400b0068 > { static constexpr const char * name_str = "DMAC::DADDR1"; };
template<> struct address_map< 0x400b006c > { static constexpr const char * name_str = "DMAC::DSCR1"; };
template<> struct address_map< 0x400b0070 > { static constexpr const char * name_str = "DMAC::CTRLA1"; };
template<> struct address_map< 0x400b0074 > { static constexpr const char * name_str = "DMAC::CTRLB1"; };
template<> struct address_map< 0x400b0078 > { static constexpr const char * name_str = "DMAC::CFG1"; };
template<> struct address_map< 0x400b008c > { static constexpr const char * name_str = "DMAC::SADDR2"; };
template<> struct address_map< 0x400b0090 > { static constexpr const char * name_str = "DMAC::DADDR2"; };
template<> struct address_map< 0x400b0094 > { static constexpr const char * name_str = "DMAC::DSCR2"; };
template<> struct address_map< 0x400b0098 > { static constexpr const char * name_str = "DMAC::CTRLA2"; };
template<> struct address_map< 0x400b009c > { static constexpr const char * name_str = "DMAC::CTRLB2"; };
template<> struct address_map< 0x400b00a0 > { static constexpr const char * name_str = "DMAC::CFG2"; };
template<> struct address_map< 0x400b00b4 > { static constexpr const char * name_str = "DMAC::SADDR3"; };
template<> struct address_map< 0x400b00b8 > { static constexpr const char * name_str = "DMAC::DADDR3"; };
template<> struct address_map< 0x400b00bc > { static constexpr const char * name_str = "DMAC::DSCR3"; };
template<> struct address_map< 0x400b00c0 > { static constexpr const char * name_str = "DMAC::CTRLA3"; };
template<> struct address_map< 0x400b00c4 > { static constexpr const char * name_str = "DMAC::CTRLB3"; };
template<> struct address_map< 0x400b00c8 > { static constexpr const char * name_str = "DMAC::CFG3"; };
template<> struct address_map< 0x400b01e4 > { static constexpr const char * name_str = "DMAC::WPMR"; };
template<> struct address_map< 0x400b01e8 > { static constexpr const char * name_str = "DMAC::WPSR"; };
template<> struct address_map< 0x400e0000 > { static constexpr const char * name_str = "SMC::CFG"; };
template<> struct address_map< 0x400e0004 > { static constexpr const char * name_str = "SMC::CTRL"; };
template<> struct address_map< 0x400e0008 > { static constexpr const char * name_str = "SMC::SR"; };
template<> struct address_map< 0x400e000c > { static constexpr const char * name_str = "SMC::IER"; };
template<> struct address_map< 0x400e0010 > { static constexpr const char * name_str = "SMC::IDR"; };
template<> struct address_map< 0x400e0014 > { static constexpr const char * name_str = "SMC::IMR"; };
template<> struct address_map< 0x400e0018 > { static constexpr const char * name_str = "SMC::ADDR"; };
template<> struct address_map< 0x400e001c > { static constexpr const char * name_str = "SMC::BANK"; };
template<> struct address_map< 0x400e0020 > { static constexpr const char * name_str = "SMC::ECC_CTRL"; };
template<> struct address_map< 0x400e0024 > { static constexpr const char * name_str = "SMC::ECC_MD"; };
template<> struct address_map< 0x400e0028 > { static constexpr const char * name_str = "SMC::ECC_SR1"; };
template<> struct address_map< 0x400e002c > { static constexpr const char * name_str = "SMC::ECC_PR0"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR0, SMC::ECC_PR0_W8BIT, SMC::ECC_PR0_W9BIT */
template<> struct address_map< 0x400e0030 > { static constexpr const char * name_str = "SMC::ECC_PR1"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR1, SMC::ECC_PR1_W8BIT, SMC::ECC_PR1_W9BIT */
template<> struct address_map< 0x400e0034 > { static constexpr const char * name_str = "SMC::ECC_SR2"; };
template<> struct address_map< 0x400e0038 > { static constexpr const char * name_str = "SMC::ECC_PR2"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR2, SMC::ECC_PR2_W8BIT */
template<> struct address_map< 0x400e003c > { static constexpr const char * name_str = "SMC::ECC_PR3"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR3, SMC::ECC_PR3_W8BIT */
template<> struct address_map< 0x400e0040 > { static constexpr const char * name_str = "SMC::ECC_PR4"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR4, SMC::ECC_PR4_W8BIT */
template<> struct address_map< 0x400e0044 > { static constexpr const char * name_str = "SMC::ECC_PR5"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR5, SMC::ECC_PR5_W8BIT */
template<> struct address_map< 0x400e0048 > { static constexpr const char * name_str = "SMC::ECC_PR6"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR6, SMC::ECC_PR6_W8BIT */
template<> struct address_map< 0x400e004c > { static constexpr const char * name_str = "SMC::ECC_PR7"; };  /* svd2hpp: duplicate address for: SMC::ECC_PR7, SMC::ECC_PR7_W8BIT */
template<> struct address_map< 0x400e0050 > { static constexpr const char * name_str = "SMC::ECC_PR8"; };
template<> struct address_map< 0x400e0054 > { static constexpr const char * name_str = "SMC::ECC_PR9"; };
template<> struct address_map< 0x400e0058 > { static constexpr const char * name_str = "SMC::ECC_PR10"; };
template<> struct address_map< 0x400e005c > { static constexpr const char * name_str = "SMC::ECC_PR11"; };
template<> struct address_map< 0x400e0060 > { static constexpr const char * name_str = "SMC::ECC_PR12"; };
template<> struct address_map< 0x400e0064 > { static constexpr const char * name_str = "SMC::ECC_PR13"; };
template<> struct address_map< 0x400e0068 > { static constexpr const char * name_str = "SMC::ECC_PR14"; };
template<> struct address_map< 0x400e006c > { static constexpr const char * name_str = "SMC::ECC_PR15"; };
template<> struct address_map< 0x400e0070 > { static constexpr const char * name_str = "SMC::SETUP0"; };
template<> struct address_map< 0x400e0074 > { static constexpr const char * name_str = "SMC::PULSE0"; };
template<> struct address_map< 0x400e0078 > { static constexpr const char * name_str = "SMC::CYCLE0"; };
template<> struct address_map< 0x400e007c > { static constexpr const char * name_str = "SMC::TIMINGS0"; };
template<> struct address_map< 0x400e0080 > { static constexpr const char * name_str = "SMC::MODE0"; };
template<> struct address_map< 0x400e0084 > { static constexpr const char * name_str = "SMC::SETUP1"; };
template<> struct address_map< 0x400e0088 > { static constexpr const char * name_str = "SMC::PULSE1"; };
template<> struct address_map< 0x400e008c > { static constexpr const char * name_str = "SMC::CYCLE1"; };
template<> struct address_map< 0x400e0090 > { static constexpr const char * name_str = "SMC::TIMINGS1"; };
template<> struct address_map< 0x400e0094 > { static constexpr const char * name_str = "SMC::MODE1"; };
template<> struct address_map< 0x400e0098 > { static constexpr const char * name_str = "SMC::SETUP2"; };
template<> struct address_map< 0x400e009c > { static constexpr const char * name_str = "SMC::PULSE2"; };
template<> struct address_map< 0x400e00a0 > { static constexpr const char * name_str = "SMC::CYCLE2"; };
template<> struct address_map< 0x400e00a4 > { static constexpr const char * name_str = "SMC::TIMINGS2"; };
template<> struct address_map< 0x400e00a8 > { static constexpr const char * name_str = "SMC::MODE2"; };
template<> struct address_map< 0x400e00ac > { static constexpr const char * name_str = "SMC::SETUP3"; };
template<> struct address_map< 0x400e00b0 > { static constexpr const char * name_str = "SMC::PULSE3"; };
template<> struct address_map< 0x400e00b4 > { static constexpr const char * name_str = "SMC::CYCLE3"; };
template<> struct address_map< 0x400e00b8 > { static constexpr const char * name_str = "SMC::TIMINGS3"; };
template<> struct address_map< 0x400e00bc > { static constexpr const char * name_str = "SMC::MODE3"; };
template<> struct address_map< 0x400e0110 > { static constexpr const char * name_str = "SMC::OCMS"; };
template<> struct address_map< 0x400e0114 > { static constexpr const char * name_str = "SMC::KEY1"; };
template<> struct address_map< 0x400e0118 > { static constexpr const char * name_str = "SMC::KEY2"; };
template<> struct address_map< 0x400e01e4 > { static constexpr const char * name_str = "SMC::WPCR"; };
template<> struct address_map< 0x400e01e8 > { static constexpr const char * name_str = "SMC::WPSR"; };
template<> struct address_map< 0x400e0200 > { static constexpr const char * name_str = "MATRIX::MCFG[%s]"; };
template<> struct address_map< 0x400e0240 > { static constexpr const char * name_str = "MATRIX::SCFG[%s]"; };
template<> struct address_map< 0x400e0280 > { static constexpr const char * name_str = "MATRIX::PRAS0"; };
template<> struct address_map< 0x400e0288 > { static constexpr const char * name_str = "MATRIX::PRAS1"; };
template<> struct address_map< 0x400e0290 > { static constexpr const char * name_str = "MATRIX::PRAS2"; };
template<> struct address_map< 0x400e0298 > { static constexpr const char * name_str = "MATRIX::PRAS3"; };
template<> struct address_map< 0x400e02a0 > { static constexpr const char * name_str = "MATRIX::PRAS4"; };
template<> struct address_map< 0x400e02a8 > { static constexpr const char * name_str = "MATRIX::PRAS5"; };
template<> struct address_map< 0x400e02b0 > { static constexpr const char * name_str = "MATRIX::PRAS6"; };
template<> struct address_map< 0x400e02b8 > { static constexpr const char * name_str = "MATRIX::PRAS7"; };
template<> struct address_map< 0x400e02c0 > { static constexpr const char * name_str = "MATRIX::PRAS8"; };
template<> struct address_map< 0x400e02c8 > { static constexpr const char * name_str = "MATRIX::PRAS9"; };
template<> struct address_map< 0x400e0300 > { static constexpr const char * name_str = "MATRIX::MRCR"; };
template<> struct address_map< 0x400e03e4 > { static constexpr const char * name_str = "MATRIX::WPMR"; };
template<> struct address_map< 0x400e03e8 > { static constexpr const char * name_str = "MATRIX::WPSR"; };
template<> struct address_map< 0x400e0400 > { static constexpr const char * name_str = "PMC::PMC_SCER"; };
template<> struct address_map< 0x400e0404 > { static constexpr const char * name_str = "PMC::PMC_SCDR"; };
template<> struct address_map< 0x400e0408 > { static constexpr const char * name_str = "PMC::PMC_SCSR"; };
template<> struct address_map< 0x400e0410 > { static constexpr const char * name_str = "PMC::PMC_PCER0"; };
template<> struct address_map< 0x400e0414 > { static constexpr const char * name_str = "PMC::PMC_PCDR0"; };
template<> struct address_map< 0x400e0418 > { static constexpr const char * name_str = "PMC::PMC_PCSR0"; };
template<> struct address_map< 0x400e041c > { static constexpr const char * name_str = "PMC::CKGR_UCKR"; };
template<> struct address_map< 0x400e0420 > { static constexpr const char * name_str = "PMC::CKGR_MOR"; };
template<> struct address_map< 0x400e0424 > { static constexpr const char * name_str = "PMC::CKGR_MCFR"; };
template<> struct address_map< 0x400e0428 > { static constexpr const char * name_str = "PMC::CKGR_PLLAR"; };
template<> struct address_map< 0x400e0430 > { static constexpr const char * name_str = "PMC::PMC_MCKR"; };
template<> struct address_map< 0x400e0440 > { static constexpr const char * name_str = "PMC::PMC_PCK[%s]"; };
template<> struct address_map< 0x400e0460 > { static constexpr const char * name_str = "PMC::PMC_IER"; };
template<> struct address_map< 0x400e0464 > { static constexpr const char * name_str = "PMC::PMC_IDR"; };
template<> struct address_map< 0x400e0468 > { static constexpr const char * name_str = "PMC::PMC_SR"; };
template<> struct address_map< 0x400e046c > { static constexpr const char * name_str = "PMC::PMC_IMR"; };
template<> struct address_map< 0x400e0470 > { static constexpr const char * name_str = "PMC::PMC_FSMR"; };
template<> struct address_map< 0x400e0474 > { static constexpr const char * name_str = "PMC::PMC_FSPR"; };
template<> struct address_map< 0x400e0478 > { static constexpr const char * name_str = "PMC::PMC_FOCR"; };
template<> struct address_map< 0x400e04e4 > { static constexpr const char * name_str = "PMC::PMC_WPMR"; };
template<> struct address_map< 0x400e04e8 > { static constexpr const char * name_str = "PMC::PMC_WPSR"; };
template<> struct address_map< 0x400e0600 > { static constexpr const char * name_str = "UART::CR"; };
template<> struct address_map< 0x400e0604 > { static constexpr const char * name_str = "UART::MR"; };
template<> struct address_map< 0x400e0608 > { static constexpr const char * name_str = "UART::IER"; };
template<> struct address_map< 0x400e060c > { static constexpr const char * name_str = "UART::IDR"; };
template<> struct address_map< 0x400e0610 > { static constexpr const char * name_str = "UART::IMR"; };
template<> struct address_map< 0x400e0614 > { static constexpr const char * name_str = "UART::SR"; };
template<> struct address_map< 0x400e0618 > { static constexpr const char * name_str = "UART::RHR"; };
template<> struct address_map< 0x400e061c > { static constexpr const char * name_str = "UART::THR"; };
template<> struct address_map< 0x400e0620 > { static constexpr const char * name_str = "UART::BRGR"; };
template<> struct address_map< 0x400e0700 > { static constexpr const char * name_str = "UART::RPR"; };
template<> struct address_map< 0x400e0704 > { static constexpr const char * name_str = "UART::RCR"; };
template<> struct address_map< 0x400e0708 > { static constexpr const char * name_str = "UART::TPR"; };
template<> struct address_map< 0x400e070c > { static constexpr const char * name_str = "UART::TCR"; };
template<> struct address_map< 0x400e0710 > { static constexpr const char * name_str = "UART::RNPR"; };
template<> struct address_map< 0x400e0714 > { static constexpr const char * name_str = "UART::RNCR"; };
template<> struct address_map< 0x400e0718 > { static constexpr const char * name_str = "UART::TNPR"; };
template<> struct address_map< 0x400e071c > { static constexpr const char * name_str = "UART::TNCR"; };
template<> struct address_map< 0x400e0720 > { static constexpr const char * name_str = "UART::PTCR"; };
template<> struct address_map< 0x400e0724 > { static constexpr const char * name_str = "UART::PTSR"; };
template<> struct address_map< 0x400e0740 > { static constexpr const char * name_str = "CHIPID::CIDR"; };
template<> struct address_map< 0x400e0744 > { static constexpr const char * name_str = "CHIPID::EXID"; };
template<> struct address_map< 0x400e0800 > { static constexpr const char * name_str = "EFC0::FMR"; };
template<> struct address_map< 0x400e0804 > { static constexpr const char * name_str = "EFC0::FCR"; };
template<> struct address_map< 0x400e0808 > { static constexpr const char * name_str = "EFC0::FSR"; };
template<> struct address_map< 0x400e080c > { static constexpr const char * name_str = "EFC0::FRR"; };
template<> struct address_map< 0x400e0a00 > { static constexpr const char * name_str = "EFC1::FMR"; };
template<> struct address_map< 0x400e0a04 > { static constexpr const char * name_str = "EFC1::FCR"; };
template<> struct address_map< 0x400e0a08 > { static constexpr const char * name_str = "EFC1::FSR"; };
template<> struct address_map< 0x400e0a0c > { static constexpr const char * name_str = "EFC1::FRR"; };
template<> struct address_map< 0x400e0c00 > { static constexpr const char * name_str = "PIOA::PER"; };
template<> struct address_map< 0x400e0c04 > { static constexpr const char * name_str = "PIOA::PDR"; };
template<> struct address_map< 0x400e0c08 > { static constexpr const char * name_str = "PIOA::PSR"; };
template<> struct address_map< 0x400e0c10 > { static constexpr const char * name_str = "PIOA::OER"; };
template<> struct address_map< 0x400e0c14 > { static constexpr const char * name_str = "PIOA::ODR"; };
template<> struct address_map< 0x400e0c18 > { static constexpr const char * name_str = "PIOA::OSR"; };
template<> struct address_map< 0x400e0c20 > { static constexpr const char * name_str = "PIOA::IFER"; };
template<> struct address_map< 0x400e0c24 > { static constexpr const char * name_str = "PIOA::IFDR"; };
template<> struct address_map< 0x400e0c28 > { static constexpr const char * name_str = "PIOA::IFSR"; };
template<> struct address_map< 0x400e0c30 > { static constexpr const char * name_str = "PIOA::SODR"; };
template<> struct address_map< 0x400e0c34 > { static constexpr const char * name_str = "PIOA::CODR"; };
template<> struct address_map< 0x400e0c38 > { static constexpr const char * name_str = "PIOA::ODSR"; };
template<> struct address_map< 0x400e0c3c > { static constexpr const char * name_str = "PIOA::PDSR"; };
template<> struct address_map< 0x400e0c40 > { static constexpr const char * name_str = "PIOA::IER"; };
template<> struct address_map< 0x400e0c44 > { static constexpr const char * name_str = "PIOA::IDR"; };
template<> struct address_map< 0x400e0c48 > { static constexpr const char * name_str = "PIOA::IMR"; };
template<> struct address_map< 0x400e0c4c > { static constexpr const char * name_str = "PIOA::ISR"; };
template<> struct address_map< 0x400e0c50 > { static constexpr const char * name_str = "PIOA::MDER"; };
template<> struct address_map< 0x400e0c54 > { static constexpr const char * name_str = "PIOA::MDDR"; };
template<> struct address_map< 0x400e0c58 > { static constexpr const char * name_str = "PIOA::MDSR"; };
template<> struct address_map< 0x400e0c60 > { static constexpr const char * name_str = "PIOA::PUDR"; };
template<> struct address_map< 0x400e0c64 > { static constexpr const char * name_str = "PIOA::PUER"; };
template<> struct address_map< 0x400e0c68 > { static constexpr const char * name_str = "PIOA::PUSR"; };
template<> struct address_map< 0x400e0c70 > { static constexpr const char * name_str = "PIOA::ABSR"; };
template<> struct address_map< 0x400e0c80 > { static constexpr const char * name_str = "PIOA::SCIFSR"; };
template<> struct address_map< 0x400e0c84 > { static constexpr const char * name_str = "PIOA::DIFSR"; };
template<> struct address_map< 0x400e0c88 > { static constexpr const char * name_str = "PIOA::IFDGSR"; };
template<> struct address_map< 0x400e0c8c > { static constexpr const char * name_str = "PIOA::SCDR"; };
template<> struct address_map< 0x400e0ca0 > { static constexpr const char * name_str = "PIOA::OWER"; };
template<> struct address_map< 0x400e0ca4 > { static constexpr const char * name_str = "PIOA::OWDR"; };
template<> struct address_map< 0x400e0ca8 > { static constexpr const char * name_str = "PIOA::OWSR"; };
template<> struct address_map< 0x400e0cb0 > { static constexpr const char * name_str = "PIOA::AIMER"; };
template<> struct address_map< 0x400e0cb4 > { static constexpr const char * name_str = "PIOA::AIMDR"; };
template<> struct address_map< 0x400e0cb8 > { static constexpr const char * name_str = "PIOA::AIMMR"; };
template<> struct address_map< 0x400e0cc0 > { static constexpr const char * name_str = "PIOA::ESR"; };
template<> struct address_map< 0x400e0cc4 > { static constexpr const char * name_str = "PIOA::LSR"; };
template<> struct address_map< 0x400e0cc8 > { static constexpr const char * name_str = "PIOA::ELSR"; };
template<> struct address_map< 0x400e0cd0 > { static constexpr const char * name_str = "PIOA::FELLSR"; };
template<> struct address_map< 0x400e0cd4 > { static constexpr const char * name_str = "PIOA::REHLSR"; };
template<> struct address_map< 0x400e0cd8 > { static constexpr const char * name_str = "PIOA::FRLHSR"; };
template<> struct address_map< 0x400e0ce0 > { static constexpr const char * name_str = "PIOA::LOCKSR"; };
template<> struct address_map< 0x400e0ce4 > { static constexpr const char * name_str = "PIOA::WPMR"; };
template<> struct address_map< 0x400e0ce8 > { static constexpr const char * name_str = "PIOA::WPSR"; };
template<> struct address_map< 0x400e0e00 > { static constexpr const char * name_str = "PIOB::PER"; };
template<> struct address_map< 0x400e0e04 > { static constexpr const char * name_str = "PIOB::PDR"; };
template<> struct address_map< 0x400e0e08 > { static constexpr const char * name_str = "PIOB::PSR"; };
template<> struct address_map< 0x400e0e10 > { static constexpr const char * name_str = "PIOB::OER"; };
template<> struct address_map< 0x400e0e14 > { static constexpr const char * name_str = "PIOB::ODR"; };
template<> struct address_map< 0x400e0e18 > { static constexpr const char * name_str = "PIOB::OSR"; };
template<> struct address_map< 0x400e0e20 > { static constexpr const char * name_str = "PIOB::IFER"; };
template<> struct address_map< 0x400e0e24 > { static constexpr const char * name_str = "PIOB::IFDR"; };
template<> struct address_map< 0x400e0e28 > { static constexpr const char * name_str = "PIOB::IFSR"; };
template<> struct address_map< 0x400e0e30 > { static constexpr const char * name_str = "PIOB::SODR"; };
template<> struct address_map< 0x400e0e34 > { static constexpr const char * name_str = "PIOB::CODR"; };
template<> struct address_map< 0x400e0e38 > { static constexpr const char * name_str = "PIOB::ODSR"; };
template<> struct address_map< 0x400e0e3c > { static constexpr const char * name_str = "PIOB::PDSR"; };
template<> struct address_map< 0x400e0e40 > { static constexpr const char * name_str = "PIOB::IER"; };
template<> struct address_map< 0x400e0e44 > { static constexpr const char * name_str = "PIOB::IDR"; };
template<> struct address_map< 0x400e0e48 > { static constexpr const char * name_str = "PIOB::IMR"; };
template<> struct address_map< 0x400e0e4c > { static constexpr const char * name_str = "PIOB::ISR"; };
template<> struct address_map< 0x400e0e50 > { static constexpr const char * name_str = "PIOB::MDER"; };
template<> struct address_map< 0x400e0e54 > { static constexpr const char * name_str = "PIOB::MDDR"; };
template<> struct address_map< 0x400e0e58 > { static constexpr const char * name_str = "PIOB::MDSR"; };
template<> struct address_map< 0x400e0e60 > { static constexpr const char * name_str = "PIOB::PUDR"; };
template<> struct address_map< 0x400e0e64 > { static constexpr const char * name_str = "PIOB::PUER"; };
template<> struct address_map< 0x400e0e68 > { static constexpr const char * name_str = "PIOB::PUSR"; };
template<> struct address_map< 0x400e0e70 > { static constexpr const char * name_str = "PIOB::ABSR"; };
template<> struct address_map< 0x400e0e80 > { static constexpr const char * name_str = "PIOB::SCIFSR"; };
template<> struct address_map< 0x400e0e84 > { static constexpr const char * name_str = "PIOB::DIFSR"; };
template<> struct address_map< 0x400e0e88 > { static constexpr const char * name_str = "PIOB::IFDGSR"; };
template<> struct address_map< 0x400e0e8c > { static constexpr const char * name_str = "PIOB::SCDR"; };
template<> struct address_map< 0x400e0ea0 > { static constexpr const char * name_str = "PIOB::OWER"; };
template<> struct address_map< 0x400e0ea4 > { static constexpr const char * name_str = "PIOB::OWDR"; };
template<> struct address_map< 0x400e0ea8 > { static constexpr const char * name_str = "PIOB::OWSR"; };
template<> struct address_map< 0x400e0eb0 > { static constexpr const char * name_str = "PIOB::AIMER"; };
template<> struct address_map< 0x400e0eb4 > { static constexpr const char * name_str = "PIOB::AIMDR"; };
template<> struct address_map< 0x400e0eb8 > { static constexpr const char * name_str = "PIOB::AIMMR"; };
template<> struct address_map< 0x400e0ec0 > { static constexpr const char * name_str = "PIOB::ESR"; };
template<> struct address_map< 0x400e0ec4 > { static constexpr const char * name_str = "PIOB::LSR"; };
template<> struct address_map< 0x400e0ec8 > { static constexpr const char * name_str = "PIOB::ELSR"; };
template<> struct address_map< 0x400e0ed0 > { static constexpr const char * name_str = "PIOB::FELLSR"; };
template<> struct address_map< 0x400e0ed4 > { static constexpr const char * name_str = "PIOB::REHLSR"; };
template<> struct address_map< 0x400e0ed8 > { static constexpr const char * name_str = "PIOB::FRLHSR"; };
template<> struct address_map< 0x400e0ee0 > { static constexpr const char * name_str = "PIOB::LOCKSR"; };
template<> struct address_map< 0x400e0ee4 > { static constexpr const char * name_str = "PIOB::WPMR"; };
template<> struct address_map< 0x400e0ee8 > { static constexpr const char * name_str = "PIOB::WPSR"; };
template<> struct address_map< 0x400e1000 > { static constexpr const char * name_str = "PIOC::PER"; };
template<> struct address_map< 0x400e1004 > { static constexpr const char * name_str = "PIOC::PDR"; };
template<> struct address_map< 0x400e1008 > { static constexpr const char * name_str = "PIOC::PSR"; };
template<> struct address_map< 0x400e1010 > { static constexpr const char * name_str = "PIOC::OER"; };
template<> struct address_map< 0x400e1014 > { static constexpr const char * name_str = "PIOC::ODR"; };
template<> struct address_map< 0x400e1018 > { static constexpr const char * name_str = "PIOC::OSR"; };
template<> struct address_map< 0x400e1020 > { static constexpr const char * name_str = "PIOC::IFER"; };
template<> struct address_map< 0x400e1024 > { static constexpr const char * name_str = "PIOC::IFDR"; };
template<> struct address_map< 0x400e1028 > { static constexpr const char * name_str = "PIOC::IFSR"; };
template<> struct address_map< 0x400e1030 > { static constexpr const char * name_str = "PIOC::SODR"; };
template<> struct address_map< 0x400e1034 > { static constexpr const char * name_str = "PIOC::CODR"; };
template<> struct address_map< 0x400e1038 > { static constexpr const char * name_str = "PIOC::ODSR"; };
template<> struct address_map< 0x400e103c > { static constexpr const char * name_str = "PIOC::PDSR"; };
template<> struct address_map< 0x400e1040 > { static constexpr const char * name_str = "PIOC::IER"; };
template<> struct address_map< 0x400e1044 > { static constexpr const char * name_str = "PIOC::IDR"; };
template<> struct address_map< 0x400e1048 > { static constexpr const char * name_str = "PIOC::IMR"; };
template<> struct address_map< 0x400e104c > { static constexpr const char * name_str = "PIOC::ISR"; };
template<> struct address_map< 0x400e1050 > { static constexpr const char * name_str = "PIOC::MDER"; };
template<> struct address_map< 0x400e1054 > { static constexpr const char * name_str = "PIOC::MDDR"; };
template<> struct address_map< 0x400e1058 > { static constexpr const char * name_str = "PIOC::MDSR"; };
template<> struct address_map< 0x400e1060 > { static constexpr const char * name_str = "PIOC::PUDR"; };
template<> struct address_map< 0x400e1064 > { static constexpr const char * name_str = "PIOC::PUER"; };
template<> struct address_map< 0x400e1068 > { static constexpr const char * name_str = "PIOC::PUSR"; };
template<> struct address_map< 0x400e1070 > { static constexpr const char * name_str = "PIOC::ABSR"; };
template<> struct address_map< 0x400e1080 > { static constexpr const char * name_str = "PIOC::SCIFSR"; };
template<> struct address_map< 0x400e1084 > { static constexpr const char * name_str = "PIOC::DIFSR"; };
template<> struct address_map< 0x400e1088 > { static constexpr const char * name_str = "PIOC::IFDGSR"; };
template<> struct address_map< 0x400e108c > { static constexpr const char * name_str = "PIOC::SCDR"; };
template<> struct address_map< 0x400e10a0 > { static constexpr const char * name_str = "PIOC::OWER"; };
template<> struct address_map< 0x400e10a4 > { static constexpr const char * name_str = "PIOC::OWDR"; };
template<> struct address_map< 0x400e10a8 > { static constexpr const char * name_str = "PIOC::OWSR"; };
template<> struct address_map< 0x400e10b0 > { static constexpr const char * name_str = "PIOC::AIMER"; };
template<> struct address_map< 0x400e10b4 > { static constexpr const char * name_str = "PIOC::AIMDR"; };
template<> struct address_map< 0x400e10b8 > { static constexpr const char * name_str = "PIOC::AIMMR"; };
template<> struct address_map< 0x400e10c0 > { static constexpr const char * name_str = "PIOC::ESR"; };
template<> struct address_map< 0x400e10c4 > { static constexpr const char * name_str = "PIOC::LSR"; };
template<> struct address_map< 0x400e10c8 > { static constexpr const char * name_str = "PIOC::ELSR"; };
template<> struct address_map< 0x400e10d0 > { static constexpr const char * name_str = "PIOC::FELLSR"; };
template<> struct address_map< 0x400e10d4 > { static constexpr const char * name_str = "PIOC::REHLSR"; };
template<> struct address_map< 0x400e10d8 > { static constexpr const char * name_str = "PIOC::FRLHSR"; };
template<> struct address_map< 0x400e10e0 > { static constexpr const char * name_str = "PIOC::LOCKSR"; };
template<> struct address_map< 0x400e10e4 > { static constexpr const char * name_str = "PIOC::WPMR"; };
template<> struct address_map< 0x400e10e8 > { static constexpr const char * name_str = "PIOC::WPSR"; };
template<> struct address_map< 0x400e1200 > { static constexpr const char * name_str = "RSTC::CR"; };
template<> struct address_map< 0x400e1204 > { static constexpr const char * name_str = "RSTC::SR"; };
template<> struct address_map< 0x400e1208 > { static constexpr const char * name_str = "RSTC::MR"; };
template<> struct address_map< 0x400e1210 > { static constexpr const char * name_str = "SUPC::CR"; };
template<> struct address_map< 0x400e1214 > { static constexpr const char * name_str = "SUPC::SMMR"; };
template<> struct address_map< 0x400e1218 > { static constexpr const char * name_str = "SUPC::MR"; };
template<> struct address_map< 0x400e121c > { static constexpr const char * name_str = "SUPC::WUMR"; };
template<> struct address_map< 0x400e1220 > { static constexpr const char * name_str = "SUPC::WUIR"; };
template<> struct address_map< 0x400e1224 > { static constexpr const char * name_str = "SUPC::SR"; };
template<> struct address_map< 0x400e1230 > { static constexpr const char * name_str = "RTT::MR"; };
template<> struct address_map< 0x400e1234 > { static constexpr const char * name_str = "RTT::AR"; };
template<> struct address_map< 0x400e1238 > { static constexpr const char * name_str = "RTT::VR"; };
template<> struct address_map< 0x400e123c > { static constexpr const char * name_str = "RTT::SR"; };
template<> struct address_map< 0x400e1250 > { static constexpr const char * name_str = "WDT::CR"; };
template<> struct address_map< 0x400e1254 > { static constexpr const char * name_str = "WDT::MR"; };
template<> struct address_map< 0x400e1258 > { static constexpr const char * name_str = "WDT::SR"; };
template<> struct address_map< 0x400e1260 > { static constexpr const char * name_str = "RTC::CR"; };
template<> struct address_map< 0x400e1264 > { static constexpr const char * name_str = "RTC::MR"; };
template<> struct address_map< 0x400e1268 > { static constexpr const char * name_str = "RTC::TIMR"; };
template<> struct address_map< 0x400e126c > { static constexpr const char * name_str = "RTC::CALR"; };
template<> struct address_map< 0x400e1270 > { static constexpr const char * name_str = "RTC::TIMALR"; };
template<> struct address_map< 0x400e1274 > { static constexpr const char * name_str = "RTC::CALALR"; };
template<> struct address_map< 0x400e1278 > { static constexpr const char * name_str = "RTC::SR"; };
template<> struct address_map< 0x400e127c > { static constexpr const char * name_str = "RTC::SCCR"; };
template<> struct address_map< 0x400e1280 > { static constexpr const char * name_str = "RTC::IER"; };
template<> struct address_map< 0x400e1284 > { static constexpr const char * name_str = "RTC::IDR"; };
template<> struct address_map< 0x400e1288 > { static constexpr const char * name_str = "RTC::IMR"; };
template<> struct address_map< 0x400e128c > { static constexpr const char * name_str = "RTC::VER"; };
template<> struct address_map< 0x400e1290 > { static constexpr const char * name_str = "GPBR::GPBR[%s]"; };
template<> struct address_map< 0x400e1344 > { static constexpr const char * name_str = "RTC::WPMR"; };

} // namespace mptl

#endif // ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
