/*
 * OpenMPTL - C++ Microprocessor Template Library
 *
 * This program is a derivative representation of a CMSIS System View
 * Description (SVD) file, and is subject to the corresponding license
 * (see "License.html" in the parent directory).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

////////////////////////////////////////////////////////////////////////
//
//  Import from CMSIS-SVD: "Fujitsu/S6E1A1.svd"
//
//  name: S6E1A1
//  version: 1.2
//  description: S6E1A1 Series
//  --------------------------------------------------------------------
//
//  C++ Header file, containing architecture specific register
//  declarations for use in OpenMPTL. It has been converted directly
//  from a CMSIS-SVD file.
//
//  https://digint.ch/openmptl
//  https://github.com/posborne/cmsis-svd
//

#ifndef ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
#define ARCH_REG_ADDRESS_MAP_HPP_INCLUDED

#warning "using untested register declarations"

#include <register_type.hpp>

namespace mptl {

template<reg_addr_t addr>
struct address_map {
  static constexpr const char * name_str = nullptr;
};

template<> struct address_map< 0x40000004 > { static constexpr const char * name_str = "FLASH_IF::FRWTR"; };
template<> struct address_map< 0x40000008 > { static constexpr const char * name_str = "FLASH_IF::FSTR"; };
template<> struct address_map< 0x40000010 > { static constexpr const char * name_str = "FLASH_IF::FSYNDN"; };
template<> struct address_map< 0x40000020 > { static constexpr const char * name_str = "FLASH_IF::FICR"; };
template<> struct address_map< 0x40000024 > { static constexpr const char * name_str = "FLASH_IF::FISR"; };
template<> struct address_map< 0x40000028 > { static constexpr const char * name_str = "FLASH_IF::FICLR"; };
template<> struct address_map< 0x40000100 > { static constexpr const char * name_str = "FLASH_IF::CRTRMM"; };
template<> struct address_map< 0x40000200 > { static constexpr const char * name_str = "UNIQUE_ID::UIDR0"; };
template<> struct address_map< 0x40000204 > { static constexpr const char * name_str = "UNIQUE_ID::UIDR1"; };
template<> struct address_map< 0x40010000 > { static constexpr const char * name_str = "CLOCK::SCM_CTL"; };
template<> struct address_map< 0x40010004 > { static constexpr const char * name_str = "CLOCK::SCM_STR"; };
template<> struct address_map< 0x40010008 > { static constexpr const char * name_str = "CLOCK::STB_CTL"; };
template<> struct address_map< 0x4001000c > { static constexpr const char * name_str = "CLOCK::RST_STR"; };
template<> struct address_map< 0x40010010 > { static constexpr const char * name_str = "CLOCK::BSC_PSR"; };
template<> struct address_map< 0x40010014 > { static constexpr const char * name_str = "CLOCK::APBC0_PSR"; };
template<> struct address_map< 0x40010018 > { static constexpr const char * name_str = "CLOCK::APBC1_PSR"; };
template<> struct address_map< 0x40010020 > { static constexpr const char * name_str = "CLOCK::SWC_PSR"; };
template<> struct address_map< 0x40010030 > { static constexpr const char * name_str = "CLOCK::CSW_TMR"; };
template<> struct address_map< 0x40010034 > { static constexpr const char * name_str = "CLOCK::PSW_TMR"; };
template<> struct address_map< 0x40010038 > { static constexpr const char * name_str = "CLOCK::PLL_CTL1"; };
template<> struct address_map< 0x4001003c > { static constexpr const char * name_str = "CLOCK::PLL_CTL2"; };
template<> struct address_map< 0x40010040 > { static constexpr const char * name_str = "CLOCK::CSV_CTL"; };
template<> struct address_map< 0x40010044 > { static constexpr const char * name_str = "CLOCK::CSV_STR"; };
template<> struct address_map< 0x40010048 > { static constexpr const char * name_str = "CLOCK::FCSWH_CTL"; };
template<> struct address_map< 0x4001004c > { static constexpr const char * name_str = "CLOCK::FCSWL_CTL"; };
template<> struct address_map< 0x40010050 > { static constexpr const char * name_str = "CLOCK::FCSWD_CTL"; };
template<> struct address_map< 0x40010054 > { static constexpr const char * name_str = "CLOCK::DBWDT_CTL"; };
template<> struct address_map< 0x40010060 > { static constexpr const char * name_str = "CLOCK::INT_ENR"; };
template<> struct address_map< 0x40010064 > { static constexpr const char * name_str = "CLOCK::INT_STR"; };
template<> struct address_map< 0x40010068 > { static constexpr const char * name_str = "CLOCK::INT_CLR"; };
template<> struct address_map< 0x40011000 > { static constexpr const char * name_str = "HWWDT::WDG_LDR"; };
template<> struct address_map< 0x40011004 > { static constexpr const char * name_str = "HWWDT::WDG_VLR"; };
template<> struct address_map< 0x40011008 > { static constexpr const char * name_str = "HWWDT::WDG_CTL"; };
template<> struct address_map< 0x4001100c > { static constexpr const char * name_str = "HWWDT::WDG_ICL"; };
template<> struct address_map< 0x40011010 > { static constexpr const char * name_str = "HWWDT::WDG_RIS"; };
template<> struct address_map< 0x40011c00 > { static constexpr const char * name_str = "HWWDT::WDG_LCK"; };
template<> struct address_map< 0x40012000 > { static constexpr const char * name_str = "SWWDT::WDOGLOAD"; };
template<> struct address_map< 0x40012004 > { static constexpr const char * name_str = "SWWDT::WDOGVALUE"; };
template<> struct address_map< 0x40012008 > { static constexpr const char * name_str = "SWWDT::WDOGCONTROL"; };
template<> struct address_map< 0x4001200c > { static constexpr const char * name_str = "SWWDT::WDOGINTCLR"; };
template<> struct address_map< 0x40012010 > { static constexpr const char * name_str = "SWWDT::WDOGRIS"; };
template<> struct address_map< 0x40012018 > { static constexpr const char * name_str = "SWWDT::WDOGSPMC"; };
template<> struct address_map< 0x40012c00 > { static constexpr const char * name_str = "SWWDT::WDOGLOCK"; };
template<> struct address_map< 0x40015000 > { static constexpr const char * name_str = "DTIM::TIMER1LOAD"; };
template<> struct address_map< 0x40015004 > { static constexpr const char * name_str = "DTIM::TIMER1VALUE"; };
template<> struct address_map< 0x40015008 > { static constexpr const char * name_str = "DTIM::TIMER1CONTROL"; };
template<> struct address_map< 0x4001500c > { static constexpr const char * name_str = "DTIM::TIMER1INTCLR"; };
template<> struct address_map< 0x40015010 > { static constexpr const char * name_str = "DTIM::TIMER1RIS"; };
template<> struct address_map< 0x40015014 > { static constexpr const char * name_str = "DTIM::TIMER1MIS"; };
template<> struct address_map< 0x40015018 > { static constexpr const char * name_str = "DTIM::TIMER1BGLOAD"; };
template<> struct address_map< 0x40015020 > { static constexpr const char * name_str = "DTIM::TIMER2LOAD"; };
template<> struct address_map< 0x40015024 > { static constexpr const char * name_str = "DTIM::TIMER2VALUE"; };
template<> struct address_map< 0x40015028 > { static constexpr const char * name_str = "DTIM::TIMER2CONTROL"; };
template<> struct address_map< 0x4001502c > { static constexpr const char * name_str = "DTIM::TIMER2INTCLR"; };
template<> struct address_map< 0x40015030 > { static constexpr const char * name_str = "DTIM::TIMER2RIS"; };
template<> struct address_map< 0x40015034 > { static constexpr const char * name_str = "DTIM::TIMER2MIS"; };
template<> struct address_map< 0x40015038 > { static constexpr const char * name_str = "DTIM::TIMER2BGLOAD"; };
template<> struct address_map< 0x40020102 > { static constexpr const char * name_str = "MFT0::OCU_OCCP0"; };
template<> struct address_map< 0x40020106 > { static constexpr const char * name_str = "MFT0::OCU_OCCP1"; };
template<> struct address_map< 0x4002010a > { static constexpr const char * name_str = "MFT0::OCU_OCCP2"; };
template<> struct address_map< 0x4002010e > { static constexpr const char * name_str = "MFT0::OCU_OCCP3"; };
template<> struct address_map< 0x40020112 > { static constexpr const char * name_str = "MFT0::OCU_OCCP4"; };
template<> struct address_map< 0x40020116 > { static constexpr const char * name_str = "MFT0::OCU_OCCP5"; };
template<> struct address_map< 0x40020118 > { static constexpr const char * name_str = "MFT0::OCU_OCSA10"; };
template<> struct address_map< 0x40020119 > { static constexpr const char * name_str = "MFT0::OCU_OCSB10"; };
template<> struct address_map< 0x4002011a > { static constexpr const char * name_str = "MFT0::OCU_OCSD10"; };
template<> struct address_map< 0x4002011c > { static constexpr const char * name_str = "MFT0::OCU_OCSA32"; };
template<> struct address_map< 0x4002011d > { static constexpr const char * name_str = "MFT0::OCU_OCSB32"; };
template<> struct address_map< 0x4002011e > { static constexpr const char * name_str = "MFT0::OCU_OCSD32"; };
template<> struct address_map< 0x40020120 > { static constexpr const char * name_str = "MFT0::OCU_OCSA54"; };
template<> struct address_map< 0x40020121 > { static constexpr const char * name_str = "MFT0::OCU_OCSB54"; };
template<> struct address_map< 0x40020122 > { static constexpr const char * name_str = "MFT0::OCU_OCSD54"; };
template<> struct address_map< 0x40020125 > { static constexpr const char * name_str = "MFT0::OCU_OCSC"; };
template<> struct address_map< 0x40020128 > { static constexpr const char * name_str = "MFT0::OCU_OCSE0"; };
template<> struct address_map< 0x4002012c > { static constexpr const char * name_str = "MFT0::OCU_OCSE1"; };
template<> struct address_map< 0x40020130 > { static constexpr const char * name_str = "MFT0::OCU_OCSE2"; };
template<> struct address_map< 0x40020134 > { static constexpr const char * name_str = "MFT0::OCU_OCSE3"; };
template<> struct address_map< 0x40020138 > { static constexpr const char * name_str = "MFT0::OCU_OCSE4"; };
template<> struct address_map< 0x4002013c > { static constexpr const char * name_str = "MFT0::OCU_OCSE5"; };
template<> struct address_map< 0x40020142 > { static constexpr const char * name_str = "MFT0::FRT_TCCP0"; };
template<> struct address_map< 0x40020146 > { static constexpr const char * name_str = "MFT0::FRT_TCDT0"; };
template<> struct address_map< 0x40020148 > { static constexpr const char * name_str = "MFT0::FRT_TCSA0"; };
template<> struct address_map< 0x4002014a > { static constexpr const char * name_str = "MFT0::FRT_TCSC0"; };
template<> struct address_map< 0x4002014e > { static constexpr const char * name_str = "MFT0::FRT_TCCP1"; };
template<> struct address_map< 0x40020152 > { static constexpr const char * name_str = "MFT0::FRT_TCDT1"; };
template<> struct address_map< 0x40020154 > { static constexpr const char * name_str = "MFT0::FRT_TCSA1"; };
template<> struct address_map< 0x40020156 > { static constexpr const char * name_str = "MFT0::FRT_TCSC1"; };
template<> struct address_map< 0x4002015a > { static constexpr const char * name_str = "MFT0::FRT_TCCP2"; };
template<> struct address_map< 0x4002015e > { static constexpr const char * name_str = "MFT0::FRT_TCDT2"; };
template<> struct address_map< 0x40020160 > { static constexpr const char * name_str = "MFT0::FRT_TCSA2"; };
template<> struct address_map< 0x40020162 > { static constexpr const char * name_str = "MFT0::FRT_TCSC2"; };
template<> struct address_map< 0x40020164 > { static constexpr const char * name_str = "MFT0::FRT_TCAL"; };
template<> struct address_map< 0x40020168 > { static constexpr const char * name_str = "MFT0::OCU_OCFS10"; };
template<> struct address_map< 0x40020169 > { static constexpr const char * name_str = "MFT0::OCU_OCFS32"; };
template<> struct address_map< 0x4002016a > { static constexpr const char * name_str = "MFT0::OCU_OCFS54"; };
template<> struct address_map< 0x4002016c > { static constexpr const char * name_str = "MFT0::ICU_ICFS10"; };
template<> struct address_map< 0x4002016d > { static constexpr const char * name_str = "MFT0::ICU_ICFS32"; };
template<> struct address_map< 0x40020170 > { static constexpr const char * name_str = "MFT0::ADCMP_ACFS10"; };
template<> struct address_map< 0x40020171 > { static constexpr const char * name_str = "MFT0::ADCMP_ACFS32"; };
template<> struct address_map< 0x40020172 > { static constexpr const char * name_str = "MFT0::ADCMP_ACFS54"; };
template<> struct address_map< 0x40020176 > { static constexpr const char * name_str = "MFT0::ICU_ICCP0"; };
template<> struct address_map< 0x4002017a > { static constexpr const char * name_str = "MFT0::ICU_ICCP1"; };
template<> struct address_map< 0x4002017e > { static constexpr const char * name_str = "MFT0::ICU_ICCP2"; };
template<> struct address_map< 0x40020182 > { static constexpr const char * name_str = "MFT0::ICU_ICCP3"; };
template<> struct address_map< 0x40020184 > { static constexpr const char * name_str = "MFT0::ICU_ICSA10"; };
template<> struct address_map< 0x40020185 > { static constexpr const char * name_str = "MFT0::ICU_ICSB10"; };
template<> struct address_map< 0x40020188 > { static constexpr const char * name_str = "MFT0::ICU_ICSA32"; };
template<> struct address_map< 0x40020189 > { static constexpr const char * name_str = "MFT0::ICU_ICSB32"; };
template<> struct address_map< 0x4002018e > { static constexpr const char * name_str = "MFT0::WFG_WFTF10"; };
template<> struct address_map< 0x40020190 > { static constexpr const char * name_str = "MFT0::WFG_WFTA10"; };
template<> struct address_map< 0x40020192 > { static constexpr const char * name_str = "MFT0::WFG_WFTB10"; };
template<> struct address_map< 0x40020196 > { static constexpr const char * name_str = "MFT0::WFG_WFTF32"; };
template<> struct address_map< 0x40020198 > { static constexpr const char * name_str = "MFT0::WFG_WFTA32"; };
template<> struct address_map< 0x4002019a > { static constexpr const char * name_str = "MFT0::WFG_WFTB32"; };
template<> struct address_map< 0x4002019e > { static constexpr const char * name_str = "MFT0::WFG_WFTF54"; };
template<> struct address_map< 0x400201a0 > { static constexpr const char * name_str = "MFT0::WFG_WFTA54"; };
template<> struct address_map< 0x400201a2 > { static constexpr const char * name_str = "MFT0::WFG_WFTB54"; };
template<> struct address_map< 0x400201a4 > { static constexpr const char * name_str = "MFT0::WFG_WFSA10"; };
template<> struct address_map< 0x400201a8 > { static constexpr const char * name_str = "MFT0::WFG_WFSA32"; };
template<> struct address_map< 0x400201ac > { static constexpr const char * name_str = "MFT0::WFG_WFSA54"; };
template<> struct address_map< 0x400201b0 > { static constexpr const char * name_str = "MFT0::WFG_WFIR"; };
template<> struct address_map< 0x400201b4 > { static constexpr const char * name_str = "MFT0::WFG_NZCL"; };
template<> struct address_map< 0x400201ba > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP0"; };
template<> struct address_map< 0x400201be > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP1"; };
template<> struct address_map< 0x400201c2 > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP2"; };
template<> struct address_map< 0x400201c6 > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP3"; };
template<> struct address_map< 0x400201ca > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP4"; };
template<> struct address_map< 0x400201ce > { static constexpr const char * name_str = "MFT0::ADCMP_ACMP5"; };
template<> struct address_map< 0x400201d0 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSA"; };
template<> struct address_map< 0x400201d4 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC0"; };
template<> struct address_map< 0x400201d5 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD0"; };
template<> struct address_map< 0x400201d8 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC1"; };
template<> struct address_map< 0x400201d9 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD1"; };
template<> struct address_map< 0x400201dc > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC2"; };
template<> struct address_map< 0x400201dd > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD2"; };
template<> struct address_map< 0x400201e0 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC3"; };
template<> struct address_map< 0x400201e1 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD3"; };
template<> struct address_map< 0x400201e4 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC4"; };
template<> struct address_map< 0x400201e5 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD4"; };
template<> struct address_map< 0x400201e8 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSC5"; };
template<> struct address_map< 0x400201e9 > { static constexpr const char * name_str = "MFT0::ADCMP_ACSD5"; };
template<> struct address_map< 0x40024000 > { static constexpr const char * name_str = "MFT_PPG::TTCR0"; };
template<> struct address_map< 0x40024009 > { static constexpr const char * name_str = "MFT_PPG::COMP0"; };
template<> struct address_map< 0x4002400c > { static constexpr const char * name_str = "MFT_PPG::COMP2"; };
template<> struct address_map< 0x40024011 > { static constexpr const char * name_str = "MFT_PPG::COMP4"; };
template<> struct address_map< 0x40024014 > { static constexpr const char * name_str = "MFT_PPG::COMP6"; };
template<> struct address_map< 0x40024020 > { static constexpr const char * name_str = "MFT_PPG::TTCR1"; };
template<> struct address_map< 0x40024029 > { static constexpr const char * name_str = "MFT_PPG::COMP1"; };
template<> struct address_map< 0x4002402c > { static constexpr const char * name_str = "MFT_PPG::COMP3"; };
template<> struct address_map< 0x40024031 > { static constexpr const char * name_str = "MFT_PPG::COMP5"; };
template<> struct address_map< 0x40024034 > { static constexpr const char * name_str = "MFT_PPG::COMP7"; };
template<> struct address_map< 0x40024040 > { static constexpr const char * name_str = "MFT_PPG::TTCR2"; };
template<> struct address_map< 0x40024049 > { static constexpr const char * name_str = "MFT_PPG::COMP8"; };
template<> struct address_map< 0x4002404c > { static constexpr const char * name_str = "MFT_PPG::COMP10"; };
template<> struct address_map< 0x40024051 > { static constexpr const char * name_str = "MFT_PPG::COMP12"; };
template<> struct address_map< 0x40024054 > { static constexpr const char * name_str = "MFT_PPG::COMP14"; };
template<> struct address_map< 0x40024100 > { static constexpr const char * name_str = "MFT_PPG::TRG0"; };
template<> struct address_map< 0x40024104 > { static constexpr const char * name_str = "MFT_PPG::REVC0"; };
template<> struct address_map< 0x40024140 > { static constexpr const char * name_str = "MFT_PPG::TRG1"; };
template<> struct address_map< 0x40024144 > { static constexpr const char * name_str = "MFT_PPG::REVC1"; };
template<> struct address_map< 0x40024200 > { static constexpr const char * name_str = "MFT_PPG::PPGC1"; };
template<> struct address_map< 0x40024201 > { static constexpr const char * name_str = "MFT_PPG::PPGC0"; };
template<> struct address_map< 0x40024204 > { static constexpr const char * name_str = "MFT_PPG::PPGC3"; };
template<> struct address_map< 0x40024205 > { static constexpr const char * name_str = "MFT_PPG::PPGC2"; };
template<> struct address_map< 0x40024208 > { static constexpr const char * name_str = "MFT_PPG::PRLL0"; };
template<> struct address_map< 0x40024209 > { static constexpr const char * name_str = "MFT_PPG::PRLH0"; };
template<> struct address_map< 0x4002420c > { static constexpr const char * name_str = "MFT_PPG::PRLL1"; };
template<> struct address_map< 0x4002420d > { static constexpr const char * name_str = "MFT_PPG::PRLH1"; };
template<> struct address_map< 0x40024210 > { static constexpr const char * name_str = "MFT_PPG::PRLL2"; };
template<> struct address_map< 0x40024211 > { static constexpr const char * name_str = "MFT_PPG::PRLH2"; };
template<> struct address_map< 0x40024214 > { static constexpr const char * name_str = "MFT_PPG::PRLL3"; };
template<> struct address_map< 0x40024215 > { static constexpr const char * name_str = "MFT_PPG::PRLH3"; };
template<> struct address_map< 0x40024218 > { static constexpr const char * name_str = "MFT_PPG::GATEC0"; };
template<> struct address_map< 0x40024240 > { static constexpr const char * name_str = "MFT_PPG::PPGC5"; };
template<> struct address_map< 0x40024241 > { static constexpr const char * name_str = "MFT_PPG::PPGC4"; };
template<> struct address_map< 0x40024244 > { static constexpr const char * name_str = "MFT_PPG::PPGC7"; };
template<> struct address_map< 0x40024245 > { static constexpr const char * name_str = "MFT_PPG::PPGC6"; };
template<> struct address_map< 0x40024248 > { static constexpr const char * name_str = "MFT_PPG::PRLL4"; };
template<> struct address_map< 0x40024249 > { static constexpr const char * name_str = "MFT_PPG::PRLH4"; };
template<> struct address_map< 0x4002424c > { static constexpr const char * name_str = "MFT_PPG::PRLL5"; };
template<> struct address_map< 0x4002424d > { static constexpr const char * name_str = "MFT_PPG::PRLH5"; };
template<> struct address_map< 0x40024250 > { static constexpr const char * name_str = "MFT_PPG::PRLL6"; };
template<> struct address_map< 0x40024251 > { static constexpr const char * name_str = "MFT_PPG::PRLH6"; };
template<> struct address_map< 0x40024254 > { static constexpr const char * name_str = "MFT_PPG::PRLL7"; };
template<> struct address_map< 0x40024255 > { static constexpr const char * name_str = "MFT_PPG::PRLH7"; };
template<> struct address_map< 0x40024258 > { static constexpr const char * name_str = "MFT_PPG::GATEC4"; };
template<> struct address_map< 0x40024280 > { static constexpr const char * name_str = "MFT_PPG::PPGC9"; };
template<> struct address_map< 0x40024281 > { static constexpr const char * name_str = "MFT_PPG::PPGC8"; };
template<> struct address_map< 0x40024284 > { static constexpr const char * name_str = "MFT_PPG::PPGC11"; };
template<> struct address_map< 0x40024285 > { static constexpr const char * name_str = "MFT_PPG::PPGC10"; };
template<> struct address_map< 0x40024288 > { static constexpr const char * name_str = "MFT_PPG::PRLL8"; };
template<> struct address_map< 0x40024289 > { static constexpr const char * name_str = "MFT_PPG::PRLH8"; };
template<> struct address_map< 0x4002428c > { static constexpr const char * name_str = "MFT_PPG::PRLL9"; };
template<> struct address_map< 0x4002428d > { static constexpr const char * name_str = "MFT_PPG::PRLH9"; };
template<> struct address_map< 0x40024290 > { static constexpr const char * name_str = "MFT_PPG::PRLL10"; };
template<> struct address_map< 0x40024291 > { static constexpr const char * name_str = "MFT_PPG::PRLH10"; };
template<> struct address_map< 0x40024294 > { static constexpr const char * name_str = "MFT_PPG::PRLL11"; };
template<> struct address_map< 0x40024295 > { static constexpr const char * name_str = "MFT_PPG::PRLH11"; };
template<> struct address_map< 0x40024298 > { static constexpr const char * name_str = "MFT_PPG::GATEC8"; };
template<> struct address_map< 0x400242c0 > { static constexpr const char * name_str = "MFT_PPG::PPGC13"; };
template<> struct address_map< 0x400242c1 > { static constexpr const char * name_str = "MFT_PPG::PPGC12"; };
template<> struct address_map< 0x400242c4 > { static constexpr const char * name_str = "MFT_PPG::PPGC15"; };
template<> struct address_map< 0x400242c5 > { static constexpr const char * name_str = "MFT_PPG::PPGC14"; };
template<> struct address_map< 0x400242c8 > { static constexpr const char * name_str = "MFT_PPG::PRLL12"; };
template<> struct address_map< 0x400242c9 > { static constexpr const char * name_str = "MFT_PPG::PRLH12"; };
template<> struct address_map< 0x400242cc > { static constexpr const char * name_str = "MFT_PPG::PRLL13"; };
template<> struct address_map< 0x400242cd > { static constexpr const char * name_str = "MFT_PPG::PRLH13"; };
template<> struct address_map< 0x400242d0 > { static constexpr const char * name_str = "MFT_PPG::PRLL14"; };
template<> struct address_map< 0x400242d1 > { static constexpr const char * name_str = "MFT_PPG::PRLH14"; };
template<> struct address_map< 0x400242d4 > { static constexpr const char * name_str = "MFT_PPG::PRLL15"; };
template<> struct address_map< 0x400242d5 > { static constexpr const char * name_str = "MFT_PPG::PRLH15"; };
template<> struct address_map< 0x400242d8 > { static constexpr const char * name_str = "MFT_PPG::GATEC12"; };
template<> struct address_map< 0x40024300 > { static constexpr const char * name_str = "MFT_PPG::PPGC17"; };
template<> struct address_map< 0x40024301 > { static constexpr const char * name_str = "MFT_PPG::PPGC16"; };
template<> struct address_map< 0x40024304 > { static constexpr const char * name_str = "MFT_PPG::PPGC19"; };
template<> struct address_map< 0x40024305 > { static constexpr const char * name_str = "MFT_PPG::PPGC18"; };
template<> struct address_map< 0x40024308 > { static constexpr const char * name_str = "MFT_PPG::PRLL16"; };
template<> struct address_map< 0x40024309 > { static constexpr const char * name_str = "MFT_PPG::PRLH16"; };
template<> struct address_map< 0x4002430c > { static constexpr const char * name_str = "MFT_PPG::PRLL17"; };
template<> struct address_map< 0x4002430d > { static constexpr const char * name_str = "MFT_PPG::PRLH17"; };
template<> struct address_map< 0x40024310 > { static constexpr const char * name_str = "MFT_PPG::PRLL18"; };
template<> struct address_map< 0x40024311 > { static constexpr const char * name_str = "MFT_PPG::PRLH18"; };
template<> struct address_map< 0x40024314 > { static constexpr const char * name_str = "MFT_PPG::PRLL19"; };
template<> struct address_map< 0x40024315 > { static constexpr const char * name_str = "MFT_PPG::PRLH19"; };
template<> struct address_map< 0x40024318 > { static constexpr const char * name_str = "MFT_PPG::GATEC16"; };
template<> struct address_map< 0x40024340 > { static constexpr const char * name_str = "MFT_PPG::PPGC21"; };
template<> struct address_map< 0x40024341 > { static constexpr const char * name_str = "MFT_PPG::PPGC20"; };
template<> struct address_map< 0x40024344 > { static constexpr const char * name_str = "MFT_PPG::PPGC23"; };
template<> struct address_map< 0x40024345 > { static constexpr const char * name_str = "MFT_PPG::PPGC22"; };
template<> struct address_map< 0x40024348 > { static constexpr const char * name_str = "MFT_PPG::PRLL20"; };
template<> struct address_map< 0x40024349 > { static constexpr const char * name_str = "MFT_PPG::PRLH20"; };
template<> struct address_map< 0x4002434c > { static constexpr const char * name_str = "MFT_PPG::PRLL21"; };
template<> struct address_map< 0x4002434d > { static constexpr const char * name_str = "MFT_PPG::PRLH21"; };
template<> struct address_map< 0x40024350 > { static constexpr const char * name_str = "MFT_PPG::PRLL22"; };
template<> struct address_map< 0x40024351 > { static constexpr const char * name_str = "MFT_PPG::PRLH22"; };
template<> struct address_map< 0x40024354 > { static constexpr const char * name_str = "MFT_PPG::PRLL23"; };
template<> struct address_map< 0x40024355 > { static constexpr const char * name_str = "MFT_PPG::PRLH23"; };
template<> struct address_map< 0x40024358 > { static constexpr const char * name_str = "MFT_PPG::GATEC20"; };
template<> struct address_map< 0x40024380 > { static constexpr const char * name_str = "MFT_PPG::IGBTC"; };
template<> struct address_map< 0x40025000 > { static constexpr const char * name_str = "BT0::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLL, BT0::PWM_PCSR, BT0::RT_PCSR */
template<> struct address_map< 0x40025004 > { static constexpr const char * name_str = "BT0::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT0::PPG_PRLH, BT0::PWC_DTBF, BT0::PWM_PDUT */
template<> struct address_map< 0x40025008 > { static constexpr const char * name_str = "BT0::RT_TMR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMR, BT0::PWM_TMR, BT0::RT_TMR */
template<> struct address_map< 0x4002500c > { static constexpr const char * name_str = "BT0::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR, BT0::PWC_TMCR, BT0::PWM_TMCR, BT0::RT_TMCR */
template<> struct address_map< 0x40025010 > { static constexpr const char * name_str = "BT0::RT_STC"; };  /* svd2hpp: duplicate address for: BT0::PPG_STC, BT0::PWC_STC, BT0::PWM_STC, BT0::RT_STC */
template<> struct address_map< 0x40025011 > { static constexpr const char * name_str = "BT0::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT0::PPG_TMCR2, BT0::PWC_TMCR2, BT0::PWM_TMCR2, BT0::RT_TMCR2 */
template<> struct address_map< 0x40025040 > { static constexpr const char * name_str = "BT1::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLL, BT1::PWM_PCSR, BT1::RT_PCSR */
template<> struct address_map< 0x40025044 > { static constexpr const char * name_str = "BT1::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT1::PPG_PRLH, BT1::PWC_DTBF, BT1::PWM_PDUT */
template<> struct address_map< 0x40025048 > { static constexpr const char * name_str = "BT1::RT_TMR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMR, BT1::PWM_TMR, BT1::RT_TMR */
template<> struct address_map< 0x4002504c > { static constexpr const char * name_str = "BT1::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR, BT1::PWC_TMCR, BT1::PWM_TMCR, BT1::RT_TMCR */
template<> struct address_map< 0x40025050 > { static constexpr const char * name_str = "BT1::RT_STC"; };  /* svd2hpp: duplicate address for: BT1::PPG_STC, BT1::PWC_STC, BT1::PWM_STC, BT1::RT_STC */
template<> struct address_map< 0x40025051 > { static constexpr const char * name_str = "BT1::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT1::PPG_TMCR2, BT1::PWC_TMCR2, BT1::PWM_TMCR2, BT1::RT_TMCR2 */
template<> struct address_map< 0x40025080 > { static constexpr const char * name_str = "BT2::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLL, BT2::PWM_PCSR, BT2::RT_PCSR */
template<> struct address_map< 0x40025084 > { static constexpr const char * name_str = "BT2::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT2::PPG_PRLH, BT2::PWC_DTBF, BT2::PWM_PDUT */
template<> struct address_map< 0x40025088 > { static constexpr const char * name_str = "BT2::RT_TMR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMR, BT2::PWM_TMR, BT2::RT_TMR */
template<> struct address_map< 0x4002508c > { static constexpr const char * name_str = "BT2::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR, BT2::PWC_TMCR, BT2::PWM_TMCR, BT2::RT_TMCR */
template<> struct address_map< 0x40025090 > { static constexpr const char * name_str = "BT2::RT_STC"; };  /* svd2hpp: duplicate address for: BT2::PPG_STC, BT2::PWC_STC, BT2::PWM_STC, BT2::RT_STC */
template<> struct address_map< 0x40025091 > { static constexpr const char * name_str = "BT2::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT2::PPG_TMCR2, BT2::PWC_TMCR2, BT2::PWM_TMCR2, BT2::RT_TMCR2 */
template<> struct address_map< 0x400250c0 > { static constexpr const char * name_str = "BT3::RT_PCSR"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLL, BT3::PWM_PCSR, BT3::RT_PCSR */
template<> struct address_map< 0x400250c4 > { static constexpr const char * name_str = "BT3::PWC_DTBF"; };  /* svd2hpp: duplicate address for: BT3::PPG_PRLH, BT3::PWC_DTBF, BT3::PWM_PDUT */
template<> struct address_map< 0x400250c8 > { static constexpr const char * name_str = "BT3::RT_TMR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMR, BT3::PWM_TMR, BT3::RT_TMR */
template<> struct address_map< 0x400250cc > { static constexpr const char * name_str = "BT3::RT_TMCR"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR, BT3::PWC_TMCR, BT3::PWM_TMCR, BT3::RT_TMCR */
template<> struct address_map< 0x400250d0 > { static constexpr const char * name_str = "BT3::RT_STC"; };  /* svd2hpp: duplicate address for: BT3::PPG_STC, BT3::PWC_STC, BT3::PWM_STC, BT3::RT_STC */
template<> struct address_map< 0x400250d1 > { static constexpr const char * name_str = "BT3::RT_TMCR2"; };  /* svd2hpp: duplicate address for: BT3::PPG_TMCR2, BT3::PWC_TMCR2, BT3::PWM_TMCR2, BT3::RT_TMCR2 */
template<> struct address_map< 0x40025100 > { static constexpr const char * name_str = "BTIOSEL03::BTSEL0123"; };
template<> struct address_map< 0x40025ffc > { static constexpr const char * name_str = "SBSSR::BTSSSR"; };
template<> struct address_map< 0x40026000 > { static constexpr const char * name_str = "QPRC0::QPCR"; };
template<> struct address_map< 0x40026004 > { static constexpr const char * name_str = "QPRC0::QRCR"; };
template<> struct address_map< 0x40026008 > { static constexpr const char * name_str = "QPRC0::QPCCR"; };
template<> struct address_map< 0x4002600c > { static constexpr const char * name_str = "QPRC0::QPRCR"; };
template<> struct address_map< 0x40026010 > { static constexpr const char * name_str = "QPRC0::QMPR"; };
template<> struct address_map< 0x40026014 > { static constexpr const char * name_str = "QPRC0::QICRL"; };
template<> struct address_map< 0x40026015 > { static constexpr const char * name_str = "QPRC0::QICRH"; };
template<> struct address_map< 0x40026018 > { static constexpr const char * name_str = "QPRC0::QCRL"; };
template<> struct address_map< 0x40026019 > { static constexpr const char * name_str = "QPRC0::QCRH"; };
template<> struct address_map< 0x4002601c > { static constexpr const char * name_str = "QPRC0::QECR"; };
template<> struct address_map< 0x4002603c > { static constexpr const char * name_str = "QPRC0::QPRCRR"; };
template<> struct address_map< 0x40026100 > { static constexpr const char * name_str = "QPRC0_NF::NFCTLA"; };
template<> struct address_map< 0x40026104 > { static constexpr const char * name_str = "QPRC0_NF::NFCTLB"; };
template<> struct address_map< 0x40026108 > { static constexpr const char * name_str = "QPRC0_NF::NFCTLZ"; };
template<> struct address_map< 0x40027000 > { static constexpr const char * name_str = "ADC0::ADSR"; };
template<> struct address_map< 0x40027001 > { static constexpr const char * name_str = "ADC0::ADCR"; };
template<> struct address_map< 0x40027008 > { static constexpr const char * name_str = "ADC0::SFNS"; };
template<> struct address_map< 0x40027009 > { static constexpr const char * name_str = "ADC0::SCCR"; };
template<> struct address_map< 0x4002700c > { static constexpr const char * name_str = "ADC0::SCFD"; };
template<> struct address_map< 0x40027010 > { static constexpr const char * name_str = "ADC0::SCIS2"; };
template<> struct address_map< 0x40027011 > { static constexpr const char * name_str = "ADC0::SCIS3"; };
template<> struct address_map< 0x40027014 > { static constexpr const char * name_str = "ADC0::SCIS0"; };
template<> struct address_map< 0x40027015 > { static constexpr const char * name_str = "ADC0::SCIS1"; };
template<> struct address_map< 0x40027018 > { static constexpr const char * name_str = "ADC0::PFNS"; };
template<> struct address_map< 0x40027019 > { static constexpr const char * name_str = "ADC0::PCCR"; };
template<> struct address_map< 0x4002701c > { static constexpr const char * name_str = "ADC0::PCFD"; };
template<> struct address_map< 0x40027020 > { static constexpr const char * name_str = "ADC0::PCIS"; };
template<> struct address_map< 0x40027024 > { static constexpr const char * name_str = "ADC0::CMPCR"; };
template<> struct address_map< 0x40027026 > { static constexpr const char * name_str = "ADC0::CMPD"; };
template<> struct address_map< 0x40027028 > { static constexpr const char * name_str = "ADC0::ADSS2"; };
template<> struct address_map< 0x40027029 > { static constexpr const char * name_str = "ADC0::ADSS3"; };
template<> struct address_map< 0x4002702c > { static constexpr const char * name_str = "ADC0::ADSS0"; };
template<> struct address_map< 0x4002702d > { static constexpr const char * name_str = "ADC0::ADSS1"; };
template<> struct address_map< 0x40027030 > { static constexpr const char * name_str = "ADC0::ADST1"; };
template<> struct address_map< 0x40027031 > { static constexpr const char * name_str = "ADC0::ADST0"; };
template<> struct address_map< 0x40027034 > { static constexpr const char * name_str = "ADC0::ADCT"; };
template<> struct address_map< 0x40027038 > { static constexpr const char * name_str = "ADC0::PRTSL"; };
template<> struct address_map< 0x40027039 > { static constexpr const char * name_str = "ADC0::SCTSL"; };
template<> struct address_map< 0x4002703c > { static constexpr const char * name_str = "ADC0::ADCEN"; };
template<> struct address_map< 0x40027044 > { static constexpr const char * name_str = "ADC0::WCMRCIF"; };
template<> struct address_map< 0x40027048 > { static constexpr const char * name_str = "ADC0::WCMRCOT"; };
template<> struct address_map< 0x4002704c > { static constexpr const char * name_str = "ADC0::WCMPCR"; };
template<> struct address_map< 0x4002704d > { static constexpr const char * name_str = "ADC0::WCMPSR"; };
template<> struct address_map< 0x40027050 > { static constexpr const char * name_str = "ADC0::WCMPDL"; };
template<> struct address_map< 0x40027052 > { static constexpr const char * name_str = "ADC0::WCMPDH"; };
template<> struct address_map< 0x4002e000 > { static constexpr const char * name_str = "CRTRIM::MCR_PSR"; };
template<> struct address_map< 0x4002e004 > { static constexpr const char * name_str = "CRTRIM::MCR_FTRM"; };
template<> struct address_map< 0x4002e008 > { static constexpr const char * name_str = "CRTRIM::MCR_TTRM"; };
template<> struct address_map< 0x4002e00c > { static constexpr const char * name_str = "CRTRIM::MCR_RLR"; };
template<> struct address_map< 0x40030000 > { static constexpr const char * name_str = "EXTI::ENIR"; };
template<> struct address_map< 0x40030004 > { static constexpr const char * name_str = "EXTI::EIRR"; };
template<> struct address_map< 0x40030008 > { static constexpr const char * name_str = "EXTI::EICL"; };
template<> struct address_map< 0x4003000c > { static constexpr const char * name_str = "EXTI::ELVR"; };
template<> struct address_map< 0x40030010 > { static constexpr const char * name_str = "EXTI::ELVR1"; };
template<> struct address_map< 0x40030014 > { static constexpr const char * name_str = "EXTI::NMIRR"; };
template<> struct address_map< 0x40030018 > { static constexpr const char * name_str = "EXTI::NMICL"; };
template<> struct address_map< 0x40031000 > { static constexpr const char * name_str = "INTREQ::DRQSEL"; };
template<> struct address_map< 0x4003100c > { static constexpr const char * name_str = "INTREQ::IRQCMODE"; };
template<> struct address_map< 0x40031010 > { static constexpr const char * name_str = "INTREQ::EXC02MON"; };
template<> struct address_map< 0x40031014 > { static constexpr const char * name_str = "INTREQ::IRQ00MON"; };
template<> struct address_map< 0x40031018 > { static constexpr const char * name_str = "INTREQ::IRQ01MON"; };
template<> struct address_map< 0x4003101c > { static constexpr const char * name_str = "INTREQ::IRQ02MON"; };
template<> struct address_map< 0x40031020 > { static constexpr const char * name_str = "INTREQ::IRQ03MON"; };
template<> struct address_map< 0x40031024 > { static constexpr const char * name_str = "INTREQ::IRQ04MON"; };
template<> struct address_map< 0x40031028 > { static constexpr const char * name_str = "INTREQ::IRQ05MON"; };
template<> struct address_map< 0x4003102c > { static constexpr const char * name_str = "INTREQ::IRQ06MON"; };
template<> struct address_map< 0x40031030 > { static constexpr const char * name_str = "INTREQ::IRQ07MON"; };
template<> struct address_map< 0x40031034 > { static constexpr const char * name_str = "INTREQ::IRQ08MON"; };
template<> struct address_map< 0x40031038 > { static constexpr const char * name_str = "INTREQ::IRQ09MON"; };
template<> struct address_map< 0x4003103c > { static constexpr const char * name_str = "INTREQ::IRQ10MON"; };
template<> struct address_map< 0x40031040 > { static constexpr const char * name_str = "INTREQ::IRQ11MON"; };
template<> struct address_map< 0x40031044 > { static constexpr const char * name_str = "INTREQ::IRQ12MON"; };
template<> struct address_map< 0x40031048 > { static constexpr const char * name_str = "INTREQ::IRQ13MON"; };
template<> struct address_map< 0x4003104c > { static constexpr const char * name_str = "INTREQ::IRQ14MON"; };
template<> struct address_map< 0x40031050 > { static constexpr const char * name_str = "INTREQ::IRQ15MON"; };
template<> struct address_map< 0x40031054 > { static constexpr const char * name_str = "INTREQ::IRQ16MON"; };
template<> struct address_map< 0x40031058 > { static constexpr const char * name_str = "INTREQ::IRQ17MON"; };
template<> struct address_map< 0x4003105c > { static constexpr const char * name_str = "INTREQ::IRQ18MON"; };
template<> struct address_map< 0x40031060 > { static constexpr const char * name_str = "INTREQ::IRQ19MON"; };
template<> struct address_map< 0x40031064 > { static constexpr const char * name_str = "INTREQ::IRQ20MON"; };
template<> struct address_map< 0x40031068 > { static constexpr const char * name_str = "INTREQ::IRQ21MON"; };
template<> struct address_map< 0x4003106c > { static constexpr const char * name_str = "INTREQ::IRQ22MON"; };
template<> struct address_map< 0x40031070 > { static constexpr const char * name_str = "INTREQ::IRQ23MON"; };
template<> struct address_map< 0x40031074 > { static constexpr const char * name_str = "INTREQ::IRQ24MON"; };
template<> struct address_map< 0x40031078 > { static constexpr const char * name_str = "INTREQ::IRQ25MON"; };
template<> struct address_map< 0x4003107c > { static constexpr const char * name_str = "INTREQ::IRQ26MON"; };
template<> struct address_map< 0x40031080 > { static constexpr const char * name_str = "INTREQ::IRQ27MON"; };
template<> struct address_map< 0x40031084 > { static constexpr const char * name_str = "INTREQ::IRQ28MON"; };
template<> struct address_map< 0x40031088 > { static constexpr const char * name_str = "INTREQ::IRQ29MON"; };
template<> struct address_map< 0x4003108c > { static constexpr const char * name_str = "INTREQ::IRQ30MON"; };
template<> struct address_map< 0x40031090 > { static constexpr const char * name_str = "INTREQ::IRQ31MON"; };
template<> struct address_map< 0x40031210 > { static constexpr const char * name_str = "INTREQ::RCINTSEL0"; };
template<> struct address_map< 0x40031214 > { static constexpr const char * name_str = "INTREQ::RCINTSEL1"; };
template<> struct address_map< 0x40033000 > { static constexpr const char * name_str = "GPIO::PFR0"; };
template<> struct address_map< 0x40033004 > { static constexpr const char * name_str = "GPIO::PFR1"; };
template<> struct address_map< 0x40033008 > { static constexpr const char * name_str = "GPIO::PFR2"; };
template<> struct address_map< 0x4003300c > { static constexpr const char * name_str = "GPIO::PFR3"; };
template<> struct address_map< 0x40033010 > { static constexpr const char * name_str = "GPIO::PFR4"; };
template<> struct address_map< 0x40033014 > { static constexpr const char * name_str = "GPIO::PFR5"; };
template<> struct address_map< 0x40033018 > { static constexpr const char * name_str = "GPIO::PFR6"; };
template<> struct address_map< 0x40033020 > { static constexpr const char * name_str = "GPIO::PFR8"; };
template<> struct address_map< 0x40033038 > { static constexpr const char * name_str = "GPIO::PFRE"; };
template<> struct address_map< 0x40033100 > { static constexpr const char * name_str = "GPIO::PCR0"; };
template<> struct address_map< 0x40033104 > { static constexpr const char * name_str = "GPIO::PCR1"; };
template<> struct address_map< 0x40033108 > { static constexpr const char * name_str = "GPIO::PCR2"; };
template<> struct address_map< 0x4003310c > { static constexpr const char * name_str = "GPIO::PCR3"; };
template<> struct address_map< 0x40033110 > { static constexpr const char * name_str = "GPIO::PCR4"; };
template<> struct address_map< 0x40033114 > { static constexpr const char * name_str = "GPIO::PCR5"; };
template<> struct address_map< 0x40033118 > { static constexpr const char * name_str = "GPIO::PCR6"; };
template<> struct address_map< 0x40033120 > { static constexpr const char * name_str = "GPIO::PCR8"; };
template<> struct address_map< 0x40033138 > { static constexpr const char * name_str = "GPIO::PCRE"; };
template<> struct address_map< 0x40033200 > { static constexpr const char * name_str = "GPIO::DDR0"; };
template<> struct address_map< 0x40033204 > { static constexpr const char * name_str = "GPIO::DDR1"; };
template<> struct address_map< 0x40033208 > { static constexpr const char * name_str = "GPIO::DDR2"; };
template<> struct address_map< 0x4003320c > { static constexpr const char * name_str = "GPIO::DDR3"; };
template<> struct address_map< 0x40033210 > { static constexpr const char * name_str = "GPIO::DDR4"; };
template<> struct address_map< 0x40033214 > { static constexpr const char * name_str = "GPIO::DDR5"; };
template<> struct address_map< 0x40033218 > { static constexpr const char * name_str = "GPIO::DDR6"; };
template<> struct address_map< 0x40033220 > { static constexpr const char * name_str = "GPIO::DDR8"; };
template<> struct address_map< 0x40033238 > { static constexpr const char * name_str = "GPIO::DDRE"; };
template<> struct address_map< 0x40033300 > { static constexpr const char * name_str = "GPIO::PDIR0"; };
template<> struct address_map< 0x40033304 > { static constexpr const char * name_str = "GPIO::PDIR1"; };
template<> struct address_map< 0x40033308 > { static constexpr const char * name_str = "GPIO::PDIR2"; };
template<> struct address_map< 0x4003330c > { static constexpr const char * name_str = "GPIO::PDIR3"; };
template<> struct address_map< 0x40033310 > { static constexpr const char * name_str = "GPIO::PDIR4"; };
template<> struct address_map< 0x40033314 > { static constexpr const char * name_str = "GPIO::PDIR5"; };
template<> struct address_map< 0x40033318 > { static constexpr const char * name_str = "GPIO::PDIR6"; };
template<> struct address_map< 0x40033320 > { static constexpr const char * name_str = "GPIO::PDIR8"; };
template<> struct address_map< 0x40033338 > { static constexpr const char * name_str = "GPIO::PDIRE"; };
template<> struct address_map< 0x40033400 > { static constexpr const char * name_str = "GPIO::PDOR0"; };
template<> struct address_map< 0x40033404 > { static constexpr const char * name_str = "GPIO::PDOR1"; };
template<> struct address_map< 0x40033408 > { static constexpr const char * name_str = "GPIO::PDOR2"; };
template<> struct address_map< 0x4003340c > { static constexpr const char * name_str = "GPIO::PDOR3"; };
template<> struct address_map< 0x40033410 > { static constexpr const char * name_str = "GPIO::PDOR4"; };
template<> struct address_map< 0x40033414 > { static constexpr const char * name_str = "GPIO::PDOR5"; };
template<> struct address_map< 0x40033418 > { static constexpr const char * name_str = "GPIO::PDOR6"; };
template<> struct address_map< 0x40033420 > { static constexpr const char * name_str = "GPIO::PDOR8"; };
template<> struct address_map< 0x40033438 > { static constexpr const char * name_str = "GPIO::PDORE"; };
template<> struct address_map< 0x40033500 > { static constexpr const char * name_str = "GPIO::ADE"; };
template<> struct address_map< 0x40033580 > { static constexpr const char * name_str = "GPIO::SPSR"; };
template<> struct address_map< 0x40033600 > { static constexpr const char * name_str = "GPIO::EPFR00"; };
template<> struct address_map< 0x40033604 > { static constexpr const char * name_str = "GPIO::EPFR01"; };
template<> struct address_map< 0x40033608 > { static constexpr const char * name_str = "GPIO::EPFR02"; };
template<> struct address_map< 0x4003360c > { static constexpr const char * name_str = "GPIO::EPFR03"; };
template<> struct address_map< 0x40033610 > { static constexpr const char * name_str = "GPIO::EPFR04"; };
template<> struct address_map< 0x40033614 > { static constexpr const char * name_str = "GPIO::EPFR05"; };
template<> struct address_map< 0x40033618 > { static constexpr const char * name_str = "GPIO::EPFR06"; };
template<> struct address_map< 0x4003361c > { static constexpr const char * name_str = "GPIO::EPFR07"; };
template<> struct address_map< 0x40033620 > { static constexpr const char * name_str = "GPIO::EPFR08"; };
template<> struct address_map< 0x40033624 > { static constexpr const char * name_str = "GPIO::EPFR09"; };
template<> struct address_map< 0x40033630 > { static constexpr const char * name_str = "GPIO::EPFR12"; };
template<> struct address_map< 0x40033634 > { static constexpr const char * name_str = "GPIO::EPFR13"; };
template<> struct address_map< 0x40033638 > { static constexpr const char * name_str = "GPIO::EPFR14"; };
template<> struct address_map< 0x4003363c > { static constexpr const char * name_str = "GPIO::EPFR15"; };
template<> struct address_map< 0x40033640 > { static constexpr const char * name_str = "GPIO::EPFR16"; };
template<> struct address_map< 0x40033644 > { static constexpr const char * name_str = "GPIO::EPFR17"; };
template<> struct address_map< 0x40033648 > { static constexpr const char * name_str = "GPIO::EPFR18"; };
template<> struct address_map< 0x40033654 > { static constexpr const char * name_str = "GPIO::EPFR21"; };
template<> struct address_map< 0x40033658 > { static constexpr const char * name_str = "GPIO::EPFR22"; };
template<> struct address_map< 0x40033700 > { static constexpr const char * name_str = "GPIO::PZR0"; };
template<> struct address_map< 0x40033704 > { static constexpr const char * name_str = "GPIO::PZR1"; };
template<> struct address_map< 0x40033708 > { static constexpr const char * name_str = "GPIO::PZR2"; };
template<> struct address_map< 0x4003370c > { static constexpr const char * name_str = "GPIO::PZR3"; };
template<> struct address_map< 0x40033710 > { static constexpr const char * name_str = "GPIO::PZR4"; };
template<> struct address_map< 0x40033714 > { static constexpr const char * name_str = "GPIO::PZR5"; };
template<> struct address_map< 0x40033718 > { static constexpr const char * name_str = "GPIO::PZR6"; };
template<> struct address_map< 0x40033720 > { static constexpr const char * name_str = "GPIO::PZR8"; };
template<> struct address_map< 0x40033738 > { static constexpr const char * name_str = "GPIO::PZRE"; };
template<> struct address_map< 0x40033900 > { static constexpr const char * name_str = "GPIO::FPOER0"; };
template<> struct address_map< 0x40033904 > { static constexpr const char * name_str = "GPIO::FPOER1"; };
template<> struct address_map< 0x40033908 > { static constexpr const char * name_str = "GPIO::FPOER2"; };
template<> struct address_map< 0x4003390c > { static constexpr const char * name_str = "GPIO::FPOER3"; };
template<> struct address_map< 0x40033910 > { static constexpr const char * name_str = "GPIO::FPOER4"; };
template<> struct address_map< 0x40033914 > { static constexpr const char * name_str = "GPIO::FPOER5"; };
template<> struct address_map< 0x40033918 > { static constexpr const char * name_str = "GPIO::FPOER6"; };
template<> struct address_map< 0x40033920 > { static constexpr const char * name_str = "GPIO::FPOER8"; };
template<> struct address_map< 0x40033938 > { static constexpr const char * name_str = "GPIO::FPOERE"; };
template<> struct address_map< 0x40035000 > { static constexpr const char * name_str = "LVD::LVD_CTL"; };
template<> struct address_map< 0x40035004 > { static constexpr const char * name_str = "LVD::LVD_STR"; };
template<> struct address_map< 0x40035008 > { static constexpr const char * name_str = "LVD::LVD_CLR"; };
template<> struct address_map< 0x4003500c > { static constexpr const char * name_str = "LVD::LVD_RLR"; };
template<> struct address_map< 0x40035010 > { static constexpr const char * name_str = "LVD::LVD_STR2"; };
template<> struct address_map< 0x40035100 > { static constexpr const char * name_str = "DS::REG_CTL"; };
template<> struct address_map< 0x40035104 > { static constexpr const char * name_str = "DS::RCK_CTL"; };
template<> struct address_map< 0x40035800 > { static constexpr const char * name_str = "DS::PMD_CTL"; };
template<> struct address_map< 0x40035804 > { static constexpr const char * name_str = "DS::WRFSR"; };
template<> struct address_map< 0x40035808 > { static constexpr const char * name_str = "DS::WIFSR"; };
template<> struct address_map< 0x4003580c > { static constexpr const char * name_str = "DS::WIER"; };
template<> struct address_map< 0x40035810 > { static constexpr const char * name_str = "DS::WILVR"; };
template<> struct address_map< 0x40035814 > { static constexpr const char * name_str = "DS::DSRAMR"; };
template<> struct address_map< 0x40035900 > { static constexpr const char * name_str = "DS::BUR01"; };
template<> struct address_map< 0x40035901 > { static constexpr const char * name_str = "DS::BUR02"; };
template<> struct address_map< 0x40035902 > { static constexpr const char * name_str = "DS::BUR03"; };
template<> struct address_map< 0x40035903 > { static constexpr const char * name_str = "DS::BUR04"; };
template<> struct address_map< 0x40035904 > { static constexpr const char * name_str = "DS::BUR05"; };
template<> struct address_map< 0x40035905 > { static constexpr const char * name_str = "DS::BUR06"; };
template<> struct address_map< 0x40035906 > { static constexpr const char * name_str = "DS::BUR07"; };
template<> struct address_map< 0x40035907 > { static constexpr const char * name_str = "DS::BUR08"; };
template<> struct address_map< 0x40035908 > { static constexpr const char * name_str = "DS::BUR09"; };
template<> struct address_map< 0x40035909 > { static constexpr const char * name_str = "DS::BUR10"; };
template<> struct address_map< 0x4003590a > { static constexpr const char * name_str = "DS::BUR11"; };
template<> struct address_map< 0x4003590b > { static constexpr const char * name_str = "DS::BUR12"; };
template<> struct address_map< 0x4003590c > { static constexpr const char * name_str = "DS::BUR13"; };
template<> struct address_map< 0x4003590d > { static constexpr const char * name_str = "DS::BUR14"; };
template<> struct address_map< 0x4003590e > { static constexpr const char * name_str = "DS::BUR15"; };
template<> struct address_map< 0x4003590f > { static constexpr const char * name_str = "DS::BUR16"; };
template<> struct address_map< 0x40038000 > { static constexpr const char * name_str = "MFS0::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SMR, MFS0::I2C_SMR, MFS0::LIN_SMR, MFS0::UART_SMR */
template<> struct address_map< 0x40038001 > { static constexpr const char * name_str = "MFS0::LIN_SCR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SCR, MFS0::I2C_IBCR, MFS0::LIN_SCR, MFS0::UART_SCR */
template<> struct address_map< 0x40038004 > { static constexpr const char * name_str = "MFS0::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_ESCR, MFS0::I2C_IBSR, MFS0::LIN_ESCR, MFS0::UART_ESCR */
template<> struct address_map< 0x40038005 > { static constexpr const char * name_str = "MFS0::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SSR, MFS0::I2C_SSR, MFS0::LIN_SSR, MFS0::UART_SSR */
template<> struct address_map< 0x40038008 > { static constexpr const char * name_str = "MFS0::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_RDR, MFS0::CSIO_TDR, MFS0::I2C_RDR, MFS0::I2C_TDR, MFS0::LIN_RDR, MFS0::LIN_TDR, MFS0::UART_RDR, MFS0::UART_TDR */
template<> struct address_map< 0x4003800c > { static constexpr const char * name_str = "MFS0::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_BGR, MFS0::I2C_BGR, MFS0::LIN_BGR, MFS0::UART_BGR */
template<> struct address_map< 0x40038010 > { static constexpr const char * name_str = "MFS0::I2C_ISBA"; };
template<> struct address_map< 0x40038011 > { static constexpr const char * name_str = "MFS0::I2C_ISMK"; };
template<> struct address_map< 0x40038014 > { static constexpr const char * name_str = "MFS0::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FCR0, MFS0::I2C_FCR0, MFS0::LIN_FCR0, MFS0::UART_FCR0 */
template<> struct address_map< 0x40038015 > { static constexpr const char * name_str = "MFS0::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FCR1, MFS0::I2C_FCR1, MFS0::LIN_FCR1, MFS0::UART_FCR1 */
template<> struct address_map< 0x40038018 > { static constexpr const char * name_str = "MFS0::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FBYTE1, MFS0::I2C_FBYTE1, MFS0::LIN_FBYTE1, MFS0::UART_FBYTE1 */
template<> struct address_map< 0x40038019 > { static constexpr const char * name_str = "MFS0::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_FBYTE2, MFS0::I2C_FBYTE2, MFS0::LIN_FBYTE2, MFS0::UART_FBYTE2 */
template<> struct address_map< 0x4003801c > { static constexpr const char * name_str = "MFS0::I2C_NFCR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SCSTR0, MFS0::I2C_NFCR */
template<> struct address_map< 0x4003801d > { static constexpr const char * name_str = "MFS0::I2C_EIBCR"; };  /* svd2hpp: duplicate address for: MFS0::CSIO_SCSTR1, MFS0::I2C_EIBCR */
template<> struct address_map< 0x40038020 > { static constexpr const char * name_str = "MFS0::CSIO_SCSTR2"; };
template<> struct address_map< 0x40038024 > { static constexpr const char * name_str = "MFS0::CSIO_SACSR"; };
template<> struct address_map< 0x40038028 > { static constexpr const char * name_str = "MFS0::CSIO_STMR"; };
template<> struct address_map< 0x4003802c > { static constexpr const char * name_str = "MFS0::CSIO_STMCR"; };
template<> struct address_map< 0x40038030 > { static constexpr const char * name_str = "MFS0::CSIO_SCSCR"; };
template<> struct address_map< 0x40038034 > { static constexpr const char * name_str = "MFS0::CSIO_SCSFR0"; };
template<> struct address_map< 0x40038035 > { static constexpr const char * name_str = "MFS0::CSIO_SCSFR1"; };
template<> struct address_map< 0x40038038 > { static constexpr const char * name_str = "MFS0::CSIO_SCSFR2"; };
template<> struct address_map< 0x4003803c > { static constexpr const char * name_str = "MFS0::CSIO_TBYTE0"; };
template<> struct address_map< 0x4003803d > { static constexpr const char * name_str = "MFS0::CSIO_TBYTE1"; };
template<> struct address_map< 0x40038040 > { static constexpr const char * name_str = "MFS0::CSIO_TBYTE2"; };
template<> struct address_map< 0x40038041 > { static constexpr const char * name_str = "MFS0::CSIO_TBYTE3"; };
template<> struct address_map< 0x40038100 > { static constexpr const char * name_str = "MFS1::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SMR, MFS1::I2C_SMR, MFS1::LIN_SMR, MFS1::UART_SMR */
template<> struct address_map< 0x40038101 > { static constexpr const char * name_str = "MFS1::LIN_SCR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SCR, MFS1::I2C_IBCR, MFS1::LIN_SCR, MFS1::UART_SCR */
template<> struct address_map< 0x40038104 > { static constexpr const char * name_str = "MFS1::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_ESCR, MFS1::I2C_IBSR, MFS1::LIN_ESCR, MFS1::UART_ESCR */
template<> struct address_map< 0x40038105 > { static constexpr const char * name_str = "MFS1::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SSR, MFS1::I2C_SSR, MFS1::LIN_SSR, MFS1::UART_SSR */
template<> struct address_map< 0x40038108 > { static constexpr const char * name_str = "MFS1::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_RDR, MFS1::CSIO_TDR, MFS1::I2C_RDR, MFS1::I2C_TDR, MFS1::LIN_RDR, MFS1::LIN_TDR, MFS1::UART_RDR, MFS1::UART_TDR */
template<> struct address_map< 0x4003810c > { static constexpr const char * name_str = "MFS1::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_BGR, MFS1::I2C_BGR, MFS1::LIN_BGR, MFS1::UART_BGR */
template<> struct address_map< 0x40038110 > { static constexpr const char * name_str = "MFS1::I2C_ISBA"; };
template<> struct address_map< 0x40038111 > { static constexpr const char * name_str = "MFS1::I2C_ISMK"; };
template<> struct address_map< 0x40038114 > { static constexpr const char * name_str = "MFS1::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FCR0, MFS1::I2C_FCR0, MFS1::LIN_FCR0, MFS1::UART_FCR0 */
template<> struct address_map< 0x40038115 > { static constexpr const char * name_str = "MFS1::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FCR1, MFS1::I2C_FCR1, MFS1::LIN_FCR1, MFS1::UART_FCR1 */
template<> struct address_map< 0x40038118 > { static constexpr const char * name_str = "MFS1::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FBYTE1, MFS1::I2C_FBYTE1, MFS1::LIN_FBYTE1, MFS1::UART_FBYTE1 */
template<> struct address_map< 0x40038119 > { static constexpr const char * name_str = "MFS1::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_FBYTE2, MFS1::I2C_FBYTE2, MFS1::LIN_FBYTE2, MFS1::UART_FBYTE2 */
template<> struct address_map< 0x4003811c > { static constexpr const char * name_str = "MFS1::I2C_NFCR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SCSTR0, MFS1::I2C_NFCR */
template<> struct address_map< 0x4003811d > { static constexpr const char * name_str = "MFS1::I2C_EIBCR"; };  /* svd2hpp: duplicate address for: MFS1::CSIO_SCSTR1, MFS1::I2C_EIBCR */
template<> struct address_map< 0x40038120 > { static constexpr const char * name_str = "MFS1::CSIO_SCSTR2"; };
template<> struct address_map< 0x40038124 > { static constexpr const char * name_str = "MFS1::CSIO_SACSR"; };
template<> struct address_map< 0x40038128 > { static constexpr const char * name_str = "MFS1::CSIO_STMR"; };
template<> struct address_map< 0x4003812c > { static constexpr const char * name_str = "MFS1::CSIO_STMCR"; };
template<> struct address_map< 0x40038130 > { static constexpr const char * name_str = "MFS1::CSIO_SCSCR"; };
template<> struct address_map< 0x40038134 > { static constexpr const char * name_str = "MFS1::CSIO_SCSFR0"; };
template<> struct address_map< 0x40038135 > { static constexpr const char * name_str = "MFS1::CSIO_SCSFR1"; };
template<> struct address_map< 0x40038138 > { static constexpr const char * name_str = "MFS1::CSIO_SCSFR2"; };
template<> struct address_map< 0x4003813c > { static constexpr const char * name_str = "MFS1::CSIO_TBYTE0"; };
template<> struct address_map< 0x4003813d > { static constexpr const char * name_str = "MFS1::CSIO_TBYTE1"; };
template<> struct address_map< 0x40038140 > { static constexpr const char * name_str = "MFS1::CSIO_TBYTE2"; };
template<> struct address_map< 0x40038141 > { static constexpr const char * name_str = "MFS1::CSIO_TBYTE3"; };
template<> struct address_map< 0x40038300 > { static constexpr const char * name_str = "MFS3::I2C_SMR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SMR, MFS3::I2C_SMR, MFS3::LIN_SMR, MFS3::UART_SMR */
template<> struct address_map< 0x40038301 > { static constexpr const char * name_str = "MFS3::LIN_SCR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SCR, MFS3::I2C_IBCR, MFS3::LIN_SCR, MFS3::UART_SCR */
template<> struct address_map< 0x40038304 > { static constexpr const char * name_str = "MFS3::I2C_IBSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_ESCR, MFS3::I2C_IBSR, MFS3::LIN_ESCR, MFS3::UART_ESCR */
template<> struct address_map< 0x40038305 > { static constexpr const char * name_str = "MFS3::I2C_SSR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SSR, MFS3::I2C_SSR, MFS3::LIN_SSR, MFS3::UART_SSR */
template<> struct address_map< 0x40038308 > { static constexpr const char * name_str = "MFS3::I2C_TDR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_RDR, MFS3::CSIO_TDR, MFS3::I2C_RDR, MFS3::I2C_TDR, MFS3::LIN_RDR, MFS3::LIN_TDR, MFS3::UART_RDR, MFS3::UART_TDR */
template<> struct address_map< 0x4003830c > { static constexpr const char * name_str = "MFS3::I2C_BGR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_BGR, MFS3::I2C_BGR, MFS3::LIN_BGR, MFS3::UART_BGR */
template<> struct address_map< 0x40038310 > { static constexpr const char * name_str = "MFS3::I2C_ISBA"; };
template<> struct address_map< 0x40038311 > { static constexpr const char * name_str = "MFS3::I2C_ISMK"; };
template<> struct address_map< 0x40038314 > { static constexpr const char * name_str = "MFS3::I2C_FCR0"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FCR0, MFS3::I2C_FCR0, MFS3::LIN_FCR0, MFS3::UART_FCR0 */
template<> struct address_map< 0x40038315 > { static constexpr const char * name_str = "MFS3::I2C_FCR1"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FCR1, MFS3::I2C_FCR1, MFS3::LIN_FCR1, MFS3::UART_FCR1 */
template<> struct address_map< 0x40038318 > { static constexpr const char * name_str = "MFS3::I2C_FBYTE1"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FBYTE1, MFS3::I2C_FBYTE1, MFS3::LIN_FBYTE1, MFS3::UART_FBYTE1 */
template<> struct address_map< 0x40038319 > { static constexpr const char * name_str = "MFS3::I2C_FBYTE2"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_FBYTE2, MFS3::I2C_FBYTE2, MFS3::LIN_FBYTE2, MFS3::UART_FBYTE2 */
template<> struct address_map< 0x4003831c > { static constexpr const char * name_str = "MFS3::I2C_NFCR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SCSTR0, MFS3::I2C_NFCR */
template<> struct address_map< 0x4003831d > { static constexpr const char * name_str = "MFS3::I2C_EIBCR"; };  /* svd2hpp: duplicate address for: MFS3::CSIO_SCSTR1, MFS3::I2C_EIBCR */
template<> struct address_map< 0x40038320 > { static constexpr const char * name_str = "MFS3::CSIO_SCSTR2"; };
template<> struct address_map< 0x40038324 > { static constexpr const char * name_str = "MFS3::CSIO_SACSR"; };
template<> struct address_map< 0x40038328 > { static constexpr const char * name_str = "MFS3::CSIO_STMR"; };
template<> struct address_map< 0x4003832c > { static constexpr const char * name_str = "MFS3::CSIO_STMCR"; };
template<> struct address_map< 0x40038330 > { static constexpr const char * name_str = "MFS3::CSIO_SCSCR"; };
template<> struct address_map< 0x40038334 > { static constexpr const char * name_str = "MFS3::CSIO_SCSFR0"; };
template<> struct address_map< 0x40038335 > { static constexpr const char * name_str = "MFS3::CSIO_SCSFR1"; };
template<> struct address_map< 0x40038338 > { static constexpr const char * name_str = "MFS3::CSIO_SCSFR2"; };
template<> struct address_map< 0x4003833c > { static constexpr const char * name_str = "MFS3::CSIO_TBYTE0"; };
template<> struct address_map< 0x4003833d > { static constexpr const char * name_str = "MFS3::CSIO_TBYTE1"; };
template<> struct address_map< 0x40038340 > { static constexpr const char * name_str = "MFS3::CSIO_TBYTE2"; };
template<> struct address_map< 0x40038341 > { static constexpr const char * name_str = "MFS3::CSIO_TBYTE3"; };
template<> struct address_map< 0x40039000 > { static constexpr const char * name_str = "CRC::CRCCR"; };
template<> struct address_map< 0x40039004 > { static constexpr const char * name_str = "CRC::CRCINIT"; };
template<> struct address_map< 0x40039008 > { static constexpr const char * name_str = "CRC::CRCIN"; };
template<> struct address_map< 0x4003900c > { static constexpr const char * name_str = "CRC::CRCR"; };
template<> struct address_map< 0x4003a000 > { static constexpr const char * name_str = "WC::WCRD"; };
template<> struct address_map< 0x4003a001 > { static constexpr const char * name_str = "WC::WCRL"; };
template<> struct address_map< 0x4003a002 > { static constexpr const char * name_str = "WC::WCCR"; };
template<> struct address_map< 0x4003a010 > { static constexpr const char * name_str = "WC::CLK_SEL"; };
template<> struct address_map< 0x4003a014 > { static constexpr const char * name_str = "WC::CLK_EN"; };
template<> struct address_map< 0x4003b000 > { static constexpr const char * name_str = "RTC::WTCR1"; };
template<> struct address_map< 0x4003b004 > { static constexpr const char * name_str = "RTC::WTCR2"; };
template<> struct address_map< 0x4003b008 > { static constexpr const char * name_str = "RTC::WTBR"; };
template<> struct address_map< 0x4003b00c > { static constexpr const char * name_str = "RTC::WTSR"; };
template<> struct address_map< 0x4003b00d > { static constexpr const char * name_str = "RTC::WTMIR"; };
template<> struct address_map< 0x4003b00e > { static constexpr const char * name_str = "RTC::WTHR"; };
template<> struct address_map< 0x4003b00f > { static constexpr const char * name_str = "RTC::WTDR"; };
template<> struct address_map< 0x4003b010 > { static constexpr const char * name_str = "RTC::WTDW"; };
template<> struct address_map< 0x4003b011 > { static constexpr const char * name_str = "RTC::WTMOR"; };
template<> struct address_map< 0x4003b012 > { static constexpr const char * name_str = "RTC::WTYR"; };
template<> struct address_map< 0x4003b015 > { static constexpr const char * name_str = "RTC::ALMIR"; };
template<> struct address_map< 0x4003b016 > { static constexpr const char * name_str = "RTC::ALHR"; };
template<> struct address_map< 0x4003b017 > { static constexpr const char * name_str = "RTC::ALDR"; };
template<> struct address_map< 0x4003b019 > { static constexpr const char * name_str = "RTC::ALMOR"; };
template<> struct address_map< 0x4003b01a > { static constexpr const char * name_str = "RTC::ALYR"; };
template<> struct address_map< 0x4003b01c > { static constexpr const char * name_str = "RTC::WTTR"; };
template<> struct address_map< 0x4003b020 > { static constexpr const char * name_str = "RTC::WTCLKS"; };
template<> struct address_map< 0x4003b021 > { static constexpr const char * name_str = "RTC::WTCLKM"; };
template<> struct address_map< 0x4003b024 > { static constexpr const char * name_str = "RTC::WTCAL"; };
template<> struct address_map< 0x4003b026 > { static constexpr const char * name_str = "RTC::WTCALEN"; };
template<> struct address_map< 0x4003b028 > { static constexpr const char * name_str = "RTC::WTDIV"; };
template<> struct address_map< 0x4003b029 > { static constexpr const char * name_str = "RTC::WTDIVEN"; };
template<> struct address_map< 0x4003b02c > { static constexpr const char * name_str = "RTC::WTCALPRD"; };
template<> struct address_map< 0x4003b030 > { static constexpr const char * name_str = "RTC::WTCOSEL"; };
template<> struct address_map< 0x4003c000 > { static constexpr const char * name_str = "LSCRP::LCR_PRSLD"; };
template<> struct address_map< 0x4003c100 > { static constexpr const char * name_str = "PCG::CKEN0"; };
template<> struct address_map< 0x4003c104 > { static constexpr const char * name_str = "PCG::MRST0"; };
template<> struct address_map< 0x4003c110 > { static constexpr const char * name_str = "PCG::CKEN1"; };
template<> struct address_map< 0x4003c114 > { static constexpr const char * name_str = "PCG::MRST1"; };
template<> struct address_map< 0x4003c120 > { static constexpr const char * name_str = "PCG::CKEN2"; };
template<> struct address_map< 0x4003c124 > { static constexpr const char * name_str = "PCG::MRST2"; };
template<> struct address_map< 0x40060000 > { static constexpr const char * name_str = "DMAC::DMACR"; };
template<> struct address_map< 0x40060010 > { static constexpr const char * name_str = "DMAC::DMACA0"; };
template<> struct address_map< 0x40060014 > { static constexpr const char * name_str = "DMAC::DMACB0"; };
template<> struct address_map< 0x40060018 > { static constexpr const char * name_str = "DMAC::DMACSA0"; };
template<> struct address_map< 0x4006001c > { static constexpr const char * name_str = "DMAC::DMACDA0"; };
template<> struct address_map< 0x40060020 > { static constexpr const char * name_str = "DMAC::DMACA1"; };
template<> struct address_map< 0x40060024 > { static constexpr const char * name_str = "DMAC::DMACB1"; };
template<> struct address_map< 0x40060028 > { static constexpr const char * name_str = "DMAC::DMACSA1"; };
template<> struct address_map< 0x4006002c > { static constexpr const char * name_str = "DMAC::DMACDA1"; };
template<> struct address_map< 0x40060030 > { static constexpr const char * name_str = "DMAC::DMACA2"; };
template<> struct address_map< 0x40060034 > { static constexpr const char * name_str = "DMAC::DMACB2"; };
template<> struct address_map< 0x40060038 > { static constexpr const char * name_str = "DMAC::DMACSA2"; };
template<> struct address_map< 0x4006003c > { static constexpr const char * name_str = "DMAC::DMACDA2"; };
template<> struct address_map< 0x40060040 > { static constexpr const char * name_str = "DMAC::DMACA3"; };
template<> struct address_map< 0x40060044 > { static constexpr const char * name_str = "DMAC::DMACB3"; };
template<> struct address_map< 0x40060048 > { static constexpr const char * name_str = "DMAC::DMACSA3"; };
template<> struct address_map< 0x4006004c > { static constexpr const char * name_str = "DMAC::DMACDA3"; };
template<> struct address_map< 0x40060050 > { static constexpr const char * name_str = "DMAC::DMACA4"; };
template<> struct address_map< 0x40060054 > { static constexpr const char * name_str = "DMAC::DMACB4"; };
template<> struct address_map< 0x40060058 > { static constexpr const char * name_str = "DMAC::DMACSA4"; };
template<> struct address_map< 0x4006005c > { static constexpr const char * name_str = "DMAC::DMACDA4"; };
template<> struct address_map< 0x40060060 > { static constexpr const char * name_str = "DMAC::DMACA5"; };
template<> struct address_map< 0x40060064 > { static constexpr const char * name_str = "DMAC::DMACB5"; };
template<> struct address_map< 0x40060068 > { static constexpr const char * name_str = "DMAC::DMACSA5"; };
template<> struct address_map< 0x4006006c > { static constexpr const char * name_str = "DMAC::DMACDA5"; };
template<> struct address_map< 0x40060070 > { static constexpr const char * name_str = "DMAC::DMACA6"; };
template<> struct address_map< 0x40060074 > { static constexpr const char * name_str = "DMAC::DMACB6"; };
template<> struct address_map< 0x40060078 > { static constexpr const char * name_str = "DMAC::DMACSA6"; };
template<> struct address_map< 0x4006007c > { static constexpr const char * name_str = "DMAC::DMACDA6"; };
template<> struct address_map< 0x40060080 > { static constexpr const char * name_str = "DMAC::DMACA7"; };
template<> struct address_map< 0x40060084 > { static constexpr const char * name_str = "DMAC::DMACB7"; };
template<> struct address_map< 0x40060088 > { static constexpr const char * name_str = "DMAC::DMACSA7"; };
template<> struct address_map< 0x4006008c > { static constexpr const char * name_str = "DMAC::DMACDA7"; };
template<> struct address_map< 0xf0001000 > { static constexpr const char * name_str = "MTB_DWT::CMP_ADDR_START"; };
template<> struct address_map< 0xf0001004 > { static constexpr const char * name_str = "MTB_DWT::CMP_DATA_START"; };
template<> struct address_map< 0xf0001008 > { static constexpr const char * name_str = "MTB_DWT::CMP_MASK_START"; };
template<> struct address_map< 0xf0001010 > { static constexpr const char * name_str = "MTB_DWT::CMP_ADDR_STOP"; };
template<> struct address_map< 0xf0001014 > { static constexpr const char * name_str = "MTB_DWT::CMP_DATA_STOP"; };
template<> struct address_map< 0xf0001018 > { static constexpr const char * name_str = "MTB_DWT::CMP_MASK_STOP"; };
template<> struct address_map< 0xf0001020 > { static constexpr const char * name_str = "MTB_DWT::FCT"; };
template<> struct address_map< 0xf0001fd0 > { static constexpr const char * name_str = "MTB_DWT::PID4"; };
template<> struct address_map< 0xf0001fd4 > { static constexpr const char * name_str = "MTB_DWT::PID5"; };
template<> struct address_map< 0xf0001fd8 > { static constexpr const char * name_str = "MTB_DWT::PID6"; };
template<> struct address_map< 0xf0001fdc > { static constexpr const char * name_str = "MTB_DWT::PID7"; };
template<> struct address_map< 0xf0001fe0 > { static constexpr const char * name_str = "MTB_DWT::PID0"; };
template<> struct address_map< 0xf0001fe4 > { static constexpr const char * name_str = "MTB_DWT::PID1"; };
template<> struct address_map< 0xf0001fe8 > { static constexpr const char * name_str = "MTB_DWT::PID2"; };
template<> struct address_map< 0xf0001fec > { static constexpr const char * name_str = "MTB_DWT::PID3"; };
template<> struct address_map< 0xf0001ff0 > { static constexpr const char * name_str = "MTB_DWT::CID0"; };
template<> struct address_map< 0xf0001ff4 > { static constexpr const char * name_str = "MTB_DWT::CID1"; };
template<> struct address_map< 0xf0001ff8 > { static constexpr const char * name_str = "MTB_DWT::CID2"; };
template<> struct address_map< 0xf0001ffc > { static constexpr const char * name_str = "MTB_DWT::CID3"; };
template<> struct address_map< 0xf8000000 > { static constexpr const char * name_str = "FASTIO::FPDIR0"; };
template<> struct address_map< 0xf8000004 > { static constexpr const char * name_str = "FASTIO::FPDIR1"; };
template<> struct address_map< 0xf8000008 > { static constexpr const char * name_str = "FASTIO::FPDIR2"; };
template<> struct address_map< 0xf800000c > { static constexpr const char * name_str = "FASTIO::FPDIR3"; };
template<> struct address_map< 0xf8000010 > { static constexpr const char * name_str = "FASTIO::FPDIR4"; };
template<> struct address_map< 0xf8000014 > { static constexpr const char * name_str = "FASTIO::FPDIR5"; };
template<> struct address_map< 0xf8000018 > { static constexpr const char * name_str = "FASTIO::FPDIR6"; };
template<> struct address_map< 0xf8000020 > { static constexpr const char * name_str = "FASTIO::FPDIR8"; };
template<> struct address_map< 0xf8000038 > { static constexpr const char * name_str = "FASTIO::FPDIRE"; };
template<> struct address_map< 0xf8000040 > { static constexpr const char * name_str = "FASTIO::FPDOR0"; };
template<> struct address_map< 0xf8000044 > { static constexpr const char * name_str = "FASTIO::FPDOR1"; };
template<> struct address_map< 0xf8000048 > { static constexpr const char * name_str = "FASTIO::FPDOR2"; };
template<> struct address_map< 0xf800004c > { static constexpr const char * name_str = "FASTIO::FPDOR3"; };
template<> struct address_map< 0xf8000050 > { static constexpr const char * name_str = "FASTIO::FPDOR4"; };
template<> struct address_map< 0xf8000054 > { static constexpr const char * name_str = "FASTIO::FPDOR5"; };
template<> struct address_map< 0xf8000058 > { static constexpr const char * name_str = "FASTIO::FPDOR6"; };
template<> struct address_map< 0xf8000060 > { static constexpr const char * name_str = "FASTIO::FPDOR8"; };
template<> struct address_map< 0xf8000078 > { static constexpr const char * name_str = "FASTIO::FPDORE"; };
template<> struct address_map< 0xf8000080 > { static constexpr const char * name_str = "FASTIO::M_FPDIR0"; };
template<> struct address_map< 0xf8000084 > { static constexpr const char * name_str = "FASTIO::M_FPDIR1"; };
template<> struct address_map< 0xf80000c0 > { static constexpr const char * name_str = "FASTIO::M_FPDOR0"; };
template<> struct address_map< 0xf80000c4 > { static constexpr const char * name_str = "FASTIO::M_FPDOR1"; };

} // namespace mptl

#endif // ARCH_REG_ADDRESS_MAP_HPP_INCLUDED
